objects/Account_Plan__c.object
<CustomObject>
    <description>Account Plans - Clone of 62-Org Account Plans</description>
    <fields>
        <fullName>Primary_AccountAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Relationship_Map__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Customer Relationship Maps</relationshipLabel>
        <relationshipName>Customer_Relationship_Maps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Relationship Maps</relationshipLabel>
        <relationshipName>Customer_Relationship_Maps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PP_S10__c</fullName>
        <label>PP_S10</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S11__c</fullName>
        <label>PP_S11</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S12__c</fullName>
        <label>PP_S12</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S1__c</fullName>
        <label>PP_S1</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S2__c</fullName>
        <label>PP_S2</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S3__c</fullName>
        <label>PP_S3</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S4__c</fullName>
        <label>PP_S4</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S5__c</fullName>
        <label>PP_S5</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S6__c</fullName>
        <label>PP_S6</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S7__c</fullName>
        <label>PP_S7</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S8__c</fullName>
        <label>PP_S8</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_S9__c</fullName>
        <label>PP_S9</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <label>Reports To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RM_S10__c</fullName>
        <label>RM_S10</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_S1__c</fullName>
        <inlineHelpText>1 - Disagree
2 - Somewhat disagree 
3 - Somewhat agree
4 - Agree</inlineHelpText>
        <label>RM_S1</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_S2__c</fullName>
        <label>RM_S2</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_S3__c</fullName>
        <label>RM_S3</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_S4__c</fullName>
        <label>RM_S4</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_S5__c</fullName>
        <label>RM_S5</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_S6__c</fullName>
        <label>RM_S6</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_S7__c</fullName>
        <label>RM_S7</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_S8__c</fullName>
        <label>RM_S8</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RM_S9__c</fullName>
        <label>RM_S9</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Somewhat Disagree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Somewhat Agree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Agree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Customer Relationship Map</label>
    <nameField>
        <displayFormat>CRM-{0000}</displayFormat>
        <label>Customer Relationship Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Relationship Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestABPRelationshipMeterTotalScore.cls
/**********************************************************
* Class Name: TestABPRelationshipMeterTotalScore
* Author: HP/Akash Garg
* Date:18/10/2012 
* Requirement:  
* Description: Test class for RelationshipMeterTotalScore
***********************************************************/
@isTest(SeeAllData=true)
public class TestABPRelationshipMeterTotalScore
{
    static testMethod void myTest() 
    {
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        Account_Plan__c acp = new Account_Plan__c(Primary_AccountAccount__c = acc.id, Name = 'Test Account Plan');
        insert acp;
        Contact con = new Contact(LastName = 'test', Email = 'test@test.com',Title='abc');
        insert con;
        
        RelationshipMeterTotalScore rmts = new RelationshipMeterTotalScore();

        List<Customer_Relationship_Map__c> crmlist = new List<Customer_Relationship_Map__c>();

        Customer_Relationship_Map__c crm1 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S1__c = '1 - Disagree',RM_S1__c = '3 - Somewhat agree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm2 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S2__c = '1 - Disagree',RM_S2__c = '3 - Somewhat agree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm3 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S3__c = '1 - Disagree',RM_S3__c = '3 - Somewhat agree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm4 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S4__c = '1 - Disagree',RM_S4__c = '3 - Somewhat agree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm5 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S5__c = '1 - Disagree',RM_S5__c = '3 - Somewhat agree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm6 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S6__c = '1 - Disagree',RM_S6__c = '3 - Somewhat agree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm7 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S7__c = '1 - Disagree',RM_S7__c = '3 - Somewhat agree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm8 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S8__c = '1 - Disagree',RM_S8__c = '3 - Somewhat agree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm9 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S9__c = '1 - Disagree',RM_S9__c = '3 - Somewhat agree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm10 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S10__c = '1 - Disagree',RM_S10__c = '3 - Somewhat agree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm11 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S11__c = '1 - Disagree', Contact__c = con.id,Parent_Contact__c = 'test');
        Customer_Relationship_Map__c crm12 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id, PP_S12__c = '1 - Disagree', Contact__c = con.id,Parent_Contact__c = 'test');

        crmlist.add(crm1);
        crmlist.add(crm2);
        crmlist.add(crm3);
        crmlist.add(crm4);
        crmlist.add(crm5);
        crmlist.add(crm6);
        crmlist.add(crm7);
        crmlist.add(crm8);
        crmlist.add(crm9);
        crmlist.add(crm10);
        crmlist.add(crm11);
        crmlist.add(crm12);

        insert crmlist;

        ABPRelationshipMeterTotalScore.RelationshipMeter(crmlist);
    }
}