objects/Account_Plan__c.object
<CustomObject>
    <description>Account Plans - Clone of 62-Org Account Plans</description>
    <fields>
        <fullName>Primary_AccountAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BU_Growth_Strategy__c.object
<CustomObject>
    <fields>
        <fullName>BU_Plan__c</fullName>
        <label>BU Plan</label>
        <referenceTo>Business_Unit_Plan__c</referenceTo>
        <relationshipLabel>BU Growth Strategies</relationshipLabel>
        <relationshipName>BU_Growth_Strategies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BU Growth Strategy</label>
    <nameField>
        <label>BU Growth Strategy</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BU Growth Strategies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Business_Unit_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Business Unit Plans</relationshipLabel>
        <relationshipName>Business_Unit_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Business Unit Plan</label>
    <nameField>
        <label>BU Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Unit Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Business_Priority__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Customer Business Priorities</relationshipLabel>
        <relationshipName>Customer_Business_Priorities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Business Priority</label>
    <nameField>
        <label>Customer Business Priority Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Business Priority</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestABPPickCBPContactJunction.cls
/**********************************************************
* Class Name: TestABPPickCBPContactJunction
* Author: HP/Akash Garg
* Date:18/10/2012 
* Requirement:  
* Description: Test class for PickCBPContactJunction
***********************************************************/
@isTest(SeeAllData=true)
public class TestABPPickCBPContactJunction
{
    static testMethod void myTest() 
    {
        Account acc = new Account(Name = 'Test Account4');
        insert acc;
        Contact con1 = new Contact(AccountId = acc.id, LastName = 'abc', Email = 'test@test.com', Phone__c = '123456789');
        insert con1;
        Opportunity op = new Opportunity(AccountId = acc.id, StageName = '01 - Understand Customer', Name = 'abc', CloseDate = system.today()+ 30);
        insert op;
        Account_Plan__c acp = new Account_Plan__c(Primary_AccountAccount__c = acc.id, Name = 'Test Account Plan');
        insert acp;
        Customer_Business_Priority__c cbp = new Customer_Business_Priority__c(Account_Plan__c = acp.id);
        insert cbp;

        Business_Unit_Plan__c bup = new Business_Unit_Plan__c(Name = 'abc', Account_Plan__c = acp.id);
        insert bup;
        BU_Growth_Strategy__c bugs = new BU_Growth_Strategy__c(BU_Plan__c = bup.id);
        //insert bugs;
        
        List<BU_Growth_Strategy__c> buglist = new List<BU_Growth_Strategy__c>();
        buglist.add(bugs);
        insert buglist; 
        
        ApexPages.currentPage().getParameters().put('id', cbp.id);
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(buglist);
        
        PickCBPContactJunction pbcp = new PickCBPContactJunction(sc);
        //List<CustomerPriority> cbpList = new List<CustomerPriority>();
        //pbcp.getBusinessPriorities();
        pbcp.processSelected();
        pbcp.search();
        pbcp.getIsPickCbpListEmpty();
        pbcp.cancel();
        pbcp.runSearch('abc');
    }
}