objects/Account_Plan__c.object
<CustomObject>
    <description>Account Plans - Clone of 62-Org Account Plans</description>
    <fields>
        <fullName>Integration_status_execSummaryReport__c</fullName>
        <label>Summary PPT Integration Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_AccountAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Business_Unit_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Business Unit Plans</relationshipLabel>
        <relationshipName>Business_Unit_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Business Unit Plan</label>
    <nameField>
        <label>BU Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Unit Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Relationship_Map__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Customer Relationship Maps</relationshipLabel>
        <relationshipName>Customer_Relationship_Maps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Relationship Maps</relationshipLabel>
        <relationshipName>Customer_Relationship_Maps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Contact__c</fullName>
        <label>Reports To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer Relationship Map</label>
    <nameField>
        <displayFormat>CRM-{0000}</displayFormat>
        <label>Customer Relationship Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Relationship Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TibcoSecurity__c.object
<CustomObject>
    <fields>
        <fullName>TargetSystemName__c</fullName>
        <label>TargetSystemName</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TibcoPassword__c</fullName>
        <label>TibcoPassword</label>
        <length>80</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>TibcoSecurity</label>
    <nameField>
        <label>Tibco UserName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TibcoSecurities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExstreamCalloutControllerTest.cls
@isTest
public class ExstreamCalloutControllerTest{





static testMethod void testCallout() 
    {
        ExstreamCalloutController ex = new ExstreamCalloutController();
        List<TibcoSecurity__c> lstTibcoSec = new List<TibcoSecurity__c>();
        TibcoSecurity__c tibcoSec = new TibcoSecurity__c(Name='tibadmin', TargetSystemName__c='Exstream', TibcoPassword__c='tibadmin');
        lstTibcoSec.add(tibcoSec);
        insert lstTibcoSec;
        
        
    
        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Account_Plan__c acp = new Account_Plan__c(Primary_AccountAccount__c = acc.id, Name = 'Test Account Plan');
        insert acp;

          
        String id = acp.id; 
        ExstreamCalloutController.invokeTibcoService(id,'Customer');
        
        
        Contact con = new Contact(LastName = 'test', Email = 'test@test.com',Title='abc');
        insert con;

        Contact con2 = new Contact(LastName = 'test2', Email = 'test2@test.com');
        insert con2;
        
        List<Customer_Relationship_Map__c> crm = new List<Customer_Relationship_Map__c>();

        Customer_Relationship_Map__c crm1 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id,Contact__c = con.id,Parent_Contact__c = 'test');
        crm.add(crm1);

        Customer_Relationship_Map__c crm2 = new Customer_Relationship_Map__c(Account_Plan__c = acp.id,Contact__c = con2.id,Parent_Contact__c = 'test2');
        crm.add(crm2);

        insert crm;
      
       List< Business_Unit_Plan__c> lstBUPlan = new List< Business_Unit_Plan__c>();
       Business_Unit_Plan__c bup = new Business_Unit_Plan__c(Name = 'abc', Account_Plan__c = acp.id);
       lstBUPlan.add(bup);
       insert lstBUPlan;
        
        String buId = bup.id; 
        
        ExstreamCalloutController.invokeTibcoService(id,'Exec');
        ExstreamCalloutController.invokeTibcoService(id,'Customer');
        ExstreamCalloutController.invokeTibcoService(buId,'BUPlan');
        ExstreamCalloutController.testSOAPFault(id,'Exec');
        ExstreamCalloutController.testException(id,'Exec');
        
        String status = '';
        System.AssertNotEquals(status, acp.Integration_status_execSummaryReport__c);
        
    }


}