objects/Account_Plan__c.object
<CustomObject>
    <description>Account Plans - Clone of 62-Org Account Plans</description>
    <fields>
        <fullName>Primary_AccountAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Business_Unit_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Business Unit Plans</relationshipLabel>
        <relationshipName>Business_Unit_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BU_Name__c</fullName>
        <label>BG Name</label>
        <picklist>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FY11_Revenue_actuals__c</fullName>
        <label>FY11 Sales (actuals) ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY12_Revenue_YTD__c</fullName>
        <label>FY12 Sales (actuals) ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY13_Projected_Revenue__c</fullName>
        <label>FY13 Projected Sales ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY14_Projected_Revenue__c</fullName>
        <label>FY14 Projected Sales ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY15_Projected_Revenue__c</fullName>
        <label>FY15 Projected Sales ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FY16_Projected_Revenue__c</fullName>
        <label>FY16 Projected Sales ($)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year_over_Year_1__c</fullName>
        <formula>( FY12_Revenue_YTD__c - FY11_Revenue_actuals__c ) / FY11_Revenue_actuals__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year over Year 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Year_over_Year_2__c</fullName>
        <formula>(FY13_Projected_Revenue__c - FY12_Revenue_YTD__c) / FY12_Revenue_YTD__c</formula>
        <label>Year over Year 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Year_over_Year_3__c</fullName>
        <formula>(FY14_Projected_Revenue__c - FY13_Projected_Revenue__c)/FY13_Projected_Revenue__c</formula>
        <label>Year over Year 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Year_over_Year_4__c</fullName>
        <formula>(FY15_Projected_Revenue__c - FY14_Projected_Revenue__c)/FY14_Projected_Revenue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year over Year 4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Business Unit Plan</label>
    <nameField>
        <label>BU Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Unit Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BUaggregationControllerTest.cls
@isTest
private class  BUaggregationControllerTest{
static testMethod void myTest() 
    {
        Account acc = new Account(Name='testacc1',Source_System_Account_ID__c='56544565');
        insert acc ;  
        Account_Plan__c newAP = new Account_Plan__c(Name='Sample Account plan',Primary_AccountAccount__c=acc.id);
        insert newAP;
        Business_Unit_Plan__c newBUP = new Business_Unit_Plan__c(Account_Plan__c=newAP.id,Name='test BU',BU_Name__c='ES',FY11_Revenue_actuals__c=10,FY12_Revenue_YTD__c=20,FY13_Projected_Revenue__c=30,FY14_Projected_Revenue__c=40,FY15_Projected_Revenue__c=50,FY16_Projected_Revenue__c=60);
        insert newBUP;
        List<AggregateResult> results = [SELECT BU_Name__c red,SUM(FY11_Revenue_actuals__c) totalfy11, SUM(FY12_Revenue_YTD__c) fy12Sum, SUM(FY13_Projected_Revenue__c) totalfy13, SUM(FY14_Projected_Revenue__c) totalfy14, SUM(FY15_Projected_Revenue__c) totalfy15, SUM(FY16_Projected_Revenue__c) totalfy16, AVG(Year_over_Year_1__c) YOY1,AVG(Year_over_Year_2__c)YOY2,AVG(Year_over_Year_3__c) YOY3,AVG(Year_over_Year_4__c) YOY4 FROM Business_Unit_Plan__c where Account_Plan__c = :newAp.Id group by BU_Name__c ];  //and BU_Name__c != 'HPFS'                 
               
        ApexPages.StandardController sc = new ApexPages.StandardController(newAP);
        BUaggregationController ars = new  BUaggregationController(sc);
        ars.results = results;
          //Butotals butot = new BuTotals();
          
       //  BUaggregationController.Butotals oc =  ars.new Butotals();
        ars.getResults();
        ars.back();
       
        
       }   
}