objects/Admin_Profiles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Profiles Names to give permissions</description>
    <fields>
        <fullName>Module__c</fullName>
        <description>This field is used to store module name for which profile name should be used.</description>
        <label>Module</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_ID__c</fullName>
        <description>This field is used to store profile Id</description>
        <label>Profile ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Admin Profiles</label>
</CustomObject>

objects/Campaign_Influence__c.object
<CustomObject>
    <description>SFDC R3.0_Julalin_20/09/2012: New Custom is created as per the requirement #
Custom Campaign Influence is created to replace all the functionality of Standard Campaign Influence</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC R3.0_Julalin_20/09/2012: New field is created as per the requirement #3217</description>
        <label>Campaign Name</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC R3.0_Julalin_20/09/2012: New field is created as per the requirement #3217</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaign Influence</relationshipLabel>
        <relationshipName>Campaign_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Influence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Influence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Vertica</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Channel_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Alliance and Channel Partners</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <picklist>
            <picklistValues>
                <fullName>Alliance Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Alliance and Channel Partners</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Partner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance and Channel Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Installation_Management__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Installation Managements</relationshipLabel>
        <relationshipName>Install_Mgmts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Installation Management</label>
    <nameField>
        <displayFormat>INT MGMT-{00000}</displayFormat>
        <label>Install MGMT Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installation Managements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Authorized_Buyer__c</fullName>
        <description>Authorized Buyer</description>
        <label>Authorized Buyer</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <description>Yes/No Option in case there is no Budget.</description>
        <label>Budget</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SFDC R2.0: New field is created as per the requirement #
Custom lookup on campaign</description>
        <label>Primary Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_State__c</fullName>
        <description>State of Lead whether assigned,accepted or rejected</description>
        <label>Lead Acceptance</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Assignment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <description>Estimated Value of Lead</description>
        <label>Estimated Lead Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Service_Solution__c</fullName>
        <description>List of Product/Service/Solution</description>
        <inlineHelpText>What is the lead interested in?</inlineHelpText>
        <label>Product/Service/Solution</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>SFDC R2.0_Bala_16/07/2012: New field is created as per the requirement #</description>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeframe_to_Buy_1__c</fullName>
        <description>Timeframe to Buy the product</description>
        <label>Timeframe to Buy</label>
        <picklist>
            <picklistValues>
                <fullName>&lt; 1 Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt; 1 Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - 3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - 6 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 - 12 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt; 1 Year</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Product_Interest__c.object
<CustomObject>
    <description>To store the list of product in which lead is interested</description>
    <fields>
        <fullName>Business_Group__c</fullName>
        <description>Will show the Business Group of Product</description>
        <formula>TEXT( Product__r.Business_Group__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Lead</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Product Interests</relationshipLabel>
        <relationshipName>Leads_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Product</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Interests</relationshipLabel>
        <relationshipName>Product_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Interest</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>Product Interest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Related_Opportunities__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>Related_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Related Opportunities (Junction Lookup)</relationshipLabel>
        <relationshipName>Related_Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Opportunities</label>
    <nameField>
        <displayFormat>RO-{000000}</displayFormat>
        <label>Related Opportunities ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Process_Linkage__c.object
<CustomObject>
    <fields>
        <fullName>ID_Type__c</fullName>
        <label>ID Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deal Registration #</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eclipse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Opportunity ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRIS config ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed BG Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OnlinePriceBook ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PreSalesSupport - RMX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quicksilver DealONE Id</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smartquote ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WBS Code</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quote_IDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Process Linkage</label>
    <nameField>
        <displayFormat>Q-{000000000}</displayFormat>
        <label>Quote ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Process Linkage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TurnValidationOff__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Used to turn the validation rule off during migration</description>
    <fields>
        <fullName>Username__c</fullName>
        <description>The email of the username</description>
        <label>Username</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>TurnValidationOff</label>
</CustomObject>

classes/TestingSetupDataUtil.cls
/**********************************************************
* Class Name: TestingSetupDataUtil
* Author: Accenture
* Date: 09-May-2012 
* Description: This class is used as a util class to create test data in test methods.
***********************************************************/
@isTest(SeeAllData=True)
public class TestingSetupDataUtil{
/* 
* Insert a Case record
* @param - String reason, String origin, String status, String ownerId
* @returns - Case 
*/
public static Case createCase(String reason, String origin, String status, String ownerId) {
    Case objCase = new Case();
    objCase.Reason = reason;
    objCase.Origin = origin;
    objCase.Status = status;
    objCase.OwnerId = ownerId;
    return objCase;
}

/* 
* 
 a TurnValidationOff__c record
* @param - String userName
* @returns - TurnValidationOff__c 
*/ /* 
public static TurnValidationOff__c createTurnValidationOff(String userName) {
    TurnValidationOff__c objTurnValidationOff = new TurnValidationOff__c(); 
    objTurnValidationOff.Username__c = userName;
    return objTurnValidationOff;
}
*/
    /* 
* Insert a Admin_Profiles__c record
* @param - String name, String module, Id profileId
* @returns - Admin_Profiles__c 
*/  
public static Admin_Profiles__c createAdminProfile(String name, String module, Id profileId) {
    Admin_Profiles__c objAdminProfiles = new Admin_Profiles__c(); 
    objAdminProfiles.Name = name;
    objAdminProfiles.Module__c = module;
    objAdminProfiles.Profile_ID__c = Userinfo.getProfileId();
    return objAdminProfiles;
}

/* 
* Insert a Related_Opportunities__c record
* @param - Id optyId, Id relatedOptyId
* @returns - Related_Opportunities__c 
*/      
public static Related_Opportunities__c createRelatedOpportunities(Id optyId, Id relatedOptyId) {
    Related_Opportunities__c objRelatedOpportunities = new Related_Opportunities__c();
    objRelatedOpportunities.Opportunity__c = optyId;
    objRelatedOpportunities.Related_Opportunity__c = relatedOptyId;
    return objRelatedOpportunities;
}

/* 
* Insert a Sales_Process_Linkage__c record
* @param - String optyId
* @returns - Sales_Process_Linkage__c 
*/  
public static Sales_Process_Linkage__c createSalesProcessLinkage(String optyId) {
    Sales_Process_Linkage__c objSalesProcessLinkage = new Sales_Process_Linkage__c();
    objSalesProcessLinkage.Opportunity__c = optyId;
    objSalesProcessLinkage.ID_Type__c = 'Eclipse';
    Double randomstr = Math.round(Math.random()*Math.pow(10, 7))+0.0100011;
    objSalesProcessLinkage.ID__c =string.valueOf(randomstr).substring(0,6);
    return objSalesProcessLinkage;
}
/**
* Create a queue
* @return - Queue Id
*/    
public static ID fetchQueue() {
    String queueId = '';
        User queue = [Select Id From User Where UserType  = 'Queue' Limit 1];
        if (queue != null ) {
            queueId = queue.Id;
            return queueId;
        }else{
        return null;
        }  
    }

/**
    * Insert a lead record
    * @param - String leadLastName, String leadCompany, String leadStatus, String leadState, String phone, String email
    * @returns - Lead 
    */
public static Lead createLead(String leadLastName, String leadCompany, String leadStatus, String leadState, String phone, String email) {
        Lead lead = new Lead();
        lead.LastName = leadLastName;
        lead.company = leadCompany;
        lead.Status = leadStatus;
        lead.Lead_State__c = leadState;
        lead.Phone = phone ;
        lead.email = email;
        lead.Budget__c = 'Yes';
        lead.Authorized_Buyer__c = 'No';
        lead.Timeframe_to_Buy_1__c = '< 1 Month';
        lead.Product_Service_Solution__c = 'PSS';
        //insert lead;
        return lead;
    } 

/**
* Insert a Account record
* @param - String accountName, String accountEmail,String recordType
* @returns - Account 
*/
public static Account createAccount(String accountName, String accountEmail,String recordType) {
    String RecordTypeId = RecordTypeIdHelper.getRecordTypeId('Account',recordType);
    Account account = new Account();
    account.Account_E_mail__c = accountEmail;
    account.Name = accountName;
    account.RecordTypeId = RecordTypeId;
    account.CurrencyIsoCode='USD';
    // Karthik : Aug 06, 2013 : Providing Correct Shipping Country : Start
    account.ShippingCountry='United States';
    // Karthik : Aug 06, 2013 : Providing Correct Shipping Country : End
    return account;
    }
    
 /**
* Insert a Contact record on an existing account
* @param - String accountId, String contactLastName
* @returns - Contact 
*/
public static Contact createContact(String accountId, String contactLastName) {
    Contact contact = new Contact();
    contact.AccountId = accountId;
    contact.LastName = contactLastName;
    contact.Phone = '55555';
    contact.Email = 'test@hp.com';
    return contact;
    }

/**
* Insert a Opportunity record
* @param - String opportunityAccountId, String OpportunityName, Date CloseDate
* @returns - opportunity 
*/    
public static Opportunity createOpportunity(String opportunityAccountId, String OpportunityName, Date CloseDate) {
        Opportunity opportunity = new Opportunity();
        opportunity.Name = OpportunityName;
        opportunity.CloseDate = CloseDate;      
        opportunity.AccountId = opportunityAccountId;
        opportunity.StageName = '01 - Understand Customer';
        opportunity.CurrencyIsoCode= 'USD';
        return opportunity;
    }  
    
/**
* Insert a OpportunityTeamMember record
* @param - ID UserId ,String TeamMemberRole,ID OpportunityId
* @returns - OpportunityTeamMember 
*/  
public static OpportunityTeamMember createOpportunityTeamMember(ID UserId ,String TeamMemberRole,ID OpportunityId ){
OpportunityTeamMember objOpportunityTeamMember  = new OpportunityTeamMember();
objOpportunityTeamMember.UserId = UserId ;
objOpportunityTeamMember.TeamMemberRole = TeamMemberRole;
objOpportunityTeamMember.OpportunityId = OpportunityId; 
return objOpportunityTeamMember ;
}
/**
* Insert a Campaign record
* @param - Boolean IsActive ,Integer ActualCost,Integer BudgetedCost,String Name,String OwnerId ,String Description ,
            Date EndDate,Integer ExpectedResponse ,Integer ExpectedRevenue,Integer  NumberSent,Date StartDate ,String Status ,String Type
* @returns - Campaign
*/
public static Campaign createCampaign(Boolean IsActive ,Integer ActualCost,Integer BudgetedCost,String Name,String OwnerId ,String Description ,
            Date EndDate,Integer ExpectedResponse ,Integer ExpectedRevenue,Integer  NumberSent,Date StartDate ,String Status ,String Type) {
       Campaign objCampaign = new Campaign();
       objCampaign.IsActive = IsActive;
       objCampaign.ActualCost = ActualCost;
       objCampaign.BudgetedCost = BudgetedCost;
       objCampaign.Name = Name;
       objCampaign.OwnerId = OwnerId;
       objCampaign.Description = Description;
       objCampaign.EndDate = EndDate;
       objCampaign.ExpectedResponse = ExpectedResponse;
       objCampaign.ExpectedRevenue = ExpectedRevenue;
       objCampaign.NumberSent = NumberSent;
       objCampaign.StartDate = StartDate;
       objCampaign.Status = Status;
       objCampaign.Type = Type;
       return objCampaign;
   }
/**
* Insert a CampaignMember record
* @param - String CampaignId,String ContactId,Boolean Primary,String LeadId
* @returns - CampaignMember 
*/   
   
   public static CampaignMember createCampaignMember(String CampaignId,String ContactId,Boolean Primary,String LeadId){
        CampaignMember objCampaignMember = new CampaignMember();
        objCampaignMember.CampaignId = CampaignId;
        objCampaignMember.ContactId = ContactId;
        objCampaignMember.Primary__c = Primary;
        objCampaignMember.LeadId = LeadId;
        return objCampaignMember;
    }
/**
* Insert a User record
* @param - String alias,String email,String EmailAddress,String emailencodingkey,String lastname,String languagelocalekey,String localesidkey,String timezonesidkey,String username,String EmployeeNumber,ID profileId
* @returns - User 
*/    
    public static User createUser(String alias,String email,String EmailAddress,String emailencodingkey,String lastname,String languagelocalekey,String localesidkey,String timezonesidkey,String username,String EmployeeNumber,ID profileId){
        User internalUser = new User();
        internalUser.alias = alias ;
        internalUser.email=email; 
        internalUser.Email_Address__c=EmailAddress;
        internalUser.emailencodingkey=emailencodingkey;
        internalUser.lastname=lastname;  
        internalUser.languagelocalekey=languagelocalekey; 
        internalUser.localesidkey=localesidkey;
        internalUser.timezonesidkey=timezonesidkey;
        internalUser.username=username;
        internalUser.EmployeeNumber = EmployeeNumber ;
        internalUser.Legacy_Employee_Ref__c = EmployeeNumber ;
        internalUser.ProfileId = profileId ;
        internalUser.Adoption_Role_Type__c='Account Executive';
        return internalUser;
    }

/**
* Insert a User record
* @param - String userId, String mangerId
* @returns - User 
*/    
    public static User updateUserWithManager(Id userId, Id mangerId){
        User updateUser = new User(Id = userId); 
        updateUser.ManagerId = mangerId;
        return updateUser;
    }     
/**
* Insert a AccountTeamMember record
* @param - ID UserId,String TeamMemberRole ,ID AccountId
* @returns - AccountTeamMember 
*/    
    public static AccountTeamMember createAccTeamMembers(ID UserId,String TeamMemberRole ,ID AccountId){
    AccountTeamMember objAccTeamMembers = new AccountTeamMember();
    objAccTeamMembers.UserId = UserId;
    objAccTeamMembers.TeamMemberRole = TeamMemberRole ;
    objAccTeamMembers.AccountId = AccountId ;
    return objAccTeamMembers;
    }
    
/* 
* Insert a UserAccountTeamMember record
* @param - ID UserId,String TeamMemberRole ,ID OwnerId, String OpportunityAccessLevel, String CaseAccessLevel, String AccountAccessLevel
* @returns - UserAccountTeamMember 
*/    
    public static UserAccountTeamMember createUserAccTeamMembers(ID UserId,String TeamMemberRole ,ID OwnerId, String OpportunityAccessLevel, String CaseAccessLevel, String AccountAccessLevel ){
    UserAccountTeamMember objUserAccTeamMembers = new UserAccountTeamMember();
    objUserAccTeamMembers.UserId = UserId;
    objUserAccTeamMembers.TeamMemberRole = TeamMemberRole ;
    objUserAccTeamMembers.OwnerId = OwnerId;
    objUserAccTeamMembers.OpportunityAccessLevel= OpportunityAccessLevel;
    objUserAccTeamMembers.CaseAccessLevel= CaseAccessLevel;
    objUserAccTeamMembers.AccountAccessLevel = AccountAccessLevel ;
    return objUserAccTeamMembers;
    }

/* 
* Insert a UserTeamMember record
* @param - ID UserId,String TeamMemberRole ,ID OwnerId, String OpportunityAccessLevel 
* @returns - UserTeamMember 
*/ 
public static UserTeamMember createTeamMembers(ID UserId,String TeamMemberRole ,ID OwnerId, String OpportunityAccessLevel ){
    UserTeamMember objTeamMembers = new UserTeamMember();
    objTeamMembers.UserId = UserId;
    objTeamMembers.TeamMemberRole = TeamMemberRole ;
    objTeamMembers .OwnerId = OwnerId;
    objTeamMembers .OpportunityAccessLevel= OpportunityAccessLevel;
    return objTeamMembers;
    }   
    
/* 
* Insert a Chanel Partner
* @param - ID Opportunity ,String PartnerType ,ID ChannelPartner
* @returns - Channel Partner 
*/ 
public static Channel_Partner__c createChannelPartner(ID Opportunity ,String PartnerType ,ID ChannelPartner){
    Channel_Partner__c objChannelPartner = new Channel_Partner__c();
    objChannelPartner.Opportunity__c = Opportunity ;
    objChannelPartner.Partner_Type__c= PartnerType ;
    objChannelPartner.Channel_Partner__c= ChannelPartner;
    return objChannelPartner;
    }   
    
    public static User testUser {
        get {
            if(testUser == null) {
                //generate Random String 
                String randomstr = Math.round(Math.random()*Math.pow(10, 7))+'';
        
                //Create user with unique alias,email,username from current running context user’s list.
                testUser = new User(Alias = 'DA_' + randomstr.substring(0,4),
                                        Email = randomstr + 'userTestSampleclassTest@hp.com',
                                        Email_Address__c=randomstr + 'userTestSampleclassTest@hp.com',
                                        LastName='Testing',
                                        EmailEncodingKey='UTF-8', 
                                        LanguageLocaleKey='en_US', 
                                        LocaleSidKey='en_US', 
                                        TimeZoneSidKey='America/Los_Angeles',
                                        ProfileId = userInfo.getProfileId(),
                                        Username = 'userTest' + randomstr + 'SampleclassTest@hp.com',
                                        EmployeeNumber = 'Emp' + randomstr.substring(0,4),
                                        Legacy_Employee_Ref__c = 'Emp' + randomstr.substring(0,4),
                                        Business_Group__c = 'PSG', 
                                        Region__c = 'EMEA');
                /* Karthik : Aug 05, 2013 : Start : Providing User Role Type Data which is Mandatory : Start */
                testUser.Adoption_Role_Type__c = 'IT';
                /* Karthik : Aug 05, 2013 : End */
                insert testUser;
            }
            return testUser;
        }
        set;}
/* 
* Insert a Product2 
* @param - Boolean isactive ,String Name,String CurrencyIsoCode,String ProductCode 
* @returns - Product2  
*/        
public static Product2 createProduct(Boolean isactive ,String Name,String CurrencyIsoCode,String ProductCode  ){
       Product2 prod = new Product2();
       prod.isActive = isactive;
       prod.Name=Name;
       prod.CurrencyIsoCode = CurrencyIsoCode;
       prod.ProductCode =ProductCode;
       return prod;
       }
/* 
* Insert a PricebookEntry 
* @param - ID prodId,Boolean isActive,ID standardPriceBook2Id,Integer UnitPrice,String CurrencyIsoCode
* @returns - PricebookEntry 
*/        
       public static PricebookEntry createPricebookEntry(ID prodId,Boolean isActive,ID standardPriceBook2Id,Integer UnitPrice,String CurrencyIsoCode){
       PricebookEntry objPricebookEntry = new PricebookEntry();
       objPricebookEntry.Product2Id = prodId;
       objPricebookEntry.isActive = isActive ;
       objPricebookEntry.priceBook2Id = standardPriceBook2Id;
       objPricebookEntry.UnitPrice=UnitPrice;
       objPricebookEntry.CurrencyIsoCode = CurrencyIsoCode ;
       insert objPricebookEntry;
       /********************** Pricebook entry with Products & Services Pricebook*******/
       
       PricebookEntry HPPricebookEntry = new PricebookEntry();
       Pricebook2 HPPricebook = [select id from Pricebook2 where Name = 'Products & Services' limit 1];
       HPPricebookEntry.Product2Id = prodId;
       HPPricebookEntry.isActive = isActive ;
       HPPricebookEntry.UseStandardPrice = false;
       HPPricebookEntry.priceBook2Id = HPPricebook.Id;
       HPPricebookEntry.UnitPrice=UnitPrice;
       HPPricebookEntry.CurrencyIsoCode = CurrencyIsoCode ;
       return HPPricebookEntry;
       }
/* 
* Insert a OpportunityLineItem 
* @param - Decimal Discount,Integer Quantity,Integer UnitPrice,ID opportunityid,ID pricebookentryid,Date ServiceDate
* @returns - OpportunityLineItem 
*/       
       public static OpportunityLineItem createOpportunityLineItem(Decimal Discount,Integer Quantity,Integer UnitPrice,ID opportunityid,ID pricebookentryid,Date ServiceDate){
       OpportunityLineItem objOpportunityLineItem = new OpportunityLineItem();
       objOpportunityLineItem.Discount=Discount;
       objOpportunityLineItem.Quantity =Quantity ;
       objOpportunityLineItem.UnitPrice =UnitPrice ;
       objOpportunityLineItem.opportunityid=opportunityid;
       objOpportunityLineItem.pricebookentryid=pricebookentryid;
       objOpportunityLineItem.ServiceDate = ServiceDate;
       return objOpportunityLineItem;       
       }
       
       
       /* 
* Insert a OpportunityLineItemSchedule 
* @param - ID OpportunityLineItemid,Double Quantity,Date ScheduleDate
* @returns - OpportunityLineItemSchedule 
*/       
       public static OpportunityLineItemSchedule createOpportunityLineItemSchedule(ID OpportunityLineItemid,Double Quantity,Date ScheduleDate){
       OpportunityLineItemSchedule objOpportunityLineItemSchedule = new OpportunityLineItemSchedule();
       objOpportunityLineItemSchedule.opportunityLineItemid=opportunityLineItemid;
       objOpportunityLineItemSchedule.Quantity =Quantity ;
       objOpportunityLineItemSchedule.ScheduleDate = ScheduleDate;
       return objOpportunityLineItemSchedule;       
       }
       
          
       /* 
* Insert a Pricebook2 
* @param - String Name,Boolean isactive
* @returns - Pricebook2 
*/        
public static Pricebook2 createPriceBook(String Name,Boolean isactive){
       Pricebook2 newBook = new Pricebook2 ();
       newBook.isActive = isactive;
       newBook.Name=Name;
       return newBook ;
       }
/* Insert a OpportunityShare 
* @param - String OpportunityAccessLevel,ID UserOrGroupId , ID OpportunityId
* @returns - OpportunityShare 
*/          
public static OpportunityShare createOpportunityShare(String OpportunityAccessLevel,ID UserOrGroupId , ID OpportunityId ){
       OpportunityShare objOpportunityShare  = new OpportunityShare();
       objOpportunityShare.OpportunityAccessLevel =OpportunityAccessLevel ;
       objOpportunityShare.UserOrGroupId =UserOrGroupId ;
       objOpportunityShare.OpportunityId =OpportunityId ;
       return objOpportunityShare ;
       }

/* Insert a Support Request 
* @param - ID OpportunityID
* @returns - Support_Request__c 
*/          
public static Support_Request__c createSupportRequest(ID OpportunityID,String RequestDescription){
       Support_Request__c objSupportRequest = new Support_Request__c();
       objSupportRequest.Opportunity__c = OpportunityId ;
       objSupportRequest.Request_Description__c = RequestDescription;
       return objSupportRequest;
       }
/* Insert a Support Request 
* @param - ID OpportunityID
* @returns - Support_Request__c 
*/          
public static Product_Interest__c createProductInterest(ID leadId, ID productId){
       Product_Interest__c objProdInterest = new Product_Interest__c();
       objProdInterest.Lead__c = leadId ;
       objProdInterest.Product__c = productId;
       return objProdInterest;
       }
       
 /* Insert a Campaign Influence 
* @param - ID OpportunityID, CampaignID Id
* @returns - Campaign Influence 
*/          
public static Campaign_Influence__c createCI(ID OpportunityId, ID CampaignId){
       Campaign_Influence__c objCI = new Campaign_Influence__c();
       objCI.Opportunity__c = OpportunityId;
       objCI.Campaign__c = CampaignId;
       return objCI;
       }
       
       /* 
* Insert a InstallationManagemnet record
* @param - String opp, String stage, String status
* @returns - Installation Managemnet
*/
public static Installation_Management__c createIM(String opp, String stage, String status) {
    Installation_Management__c objIM = new Installation_Management__c();
    objIM.Opportunity__c= opp;
    objIM.Installation_Stage__c = stage;
    objIM.Order_Status__c = status;

    return objIM;
}
     
}