objects/Approval__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Opportunity__r.Account.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Long_Name__c</fullName>
        <formula>IF( RecordType.Name=&quot;Opportunity Review&quot;  , LEFT( Opportunity__r.Account.Name, 10)&amp;&apos; - &apos; &amp;LEFT( Opportunity__r.Name , 10)&amp;&apos; - &apos;&amp;&apos;OR&apos;&amp;&apos; - &apos;&amp;Name,IF(RecordType.Name=&quot;Opportunity Business Review&quot; , LEFT( Opportunity__r.Account.Name, 10)&amp;&apos; - &apos; &amp;LEFT( Opportunity__r.Name , 10)&amp;&apos; - &apos;&amp;&apos;OBR&apos;&amp;&apos; - &apos;&amp;Name, Name))</formula>
        <label>Approval Long Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <formula>Opportunity__r.Opportunity_ID__c</formula>
        <label>Opportunity Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <formula>Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Detail__c</fullName>
        <label>Quote Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <label>Quote Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CPQ_Special_Pricing_Approval_Process__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>for CPQ Special Pricing Approval Process</description>
    <fields>
        <fullName>FieldLabel__c</fullName>
        <label>FieldLabel</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IN_OUT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if it is input Item</description>
        <label>IN/OUT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CPQ Special Pricing Approval Process</label>
</CustomObject>

classes/CPQSNDApprovalProcessCtrl.cls
/***********************************************************
Author: Shaijan Thomas
Created Date: 18-07-2013
Release: R6
Capability: CPQ
Description:Controller class for special pricing approval creation 
************************************************************/
public with sharing class CPQSNDApprovalProcessCtrl
{
    public Approval__c objApp {get;set;}
    public boolean isSaved{get;set;}
    public boolean isSubmit{set;get;}
    public approval__c approvaldetails;
    public ID OPPID{get;set;}
    public list<CPQ_Special_Pricing_Approval_Process__c> CList{get;set;}
    public CPQSNDApprovalProcessCtrl(ApexPages.StandardController controller) 
    {
        isSaved = true;
        CList = [select Name,FieldLabel__c,Section__c,IN_OUT__c,Required__c  from  CPQ_Special_Pricing_Approval_Process__c Order by Order__c];
        List<String> sAddFields = new List<String>();
        for(CPQ_Special_Pricing_Approval_Process__c obj : CList  )
            sAddFields.add(obj.Name);
        sAddFields.add('Status__c');
        sAddFields.add('Approval_Long_Name__c');
        if(!test.isRunningTest())
            controller.addFields(sAddFields);
        this.objApp = (Approval__c)controller.getRecord();
        OPPID = objApp.Opportunity__c;
        if(objApp.status__c=='Submitted' || objApp.status__c=='Approved' || objApp.status__c=='Rejected')
        {
            isSubmit=true;
            isSaved = false;
        }
        else
            isSubmit=false;
       //objApp.Quote_Detail__c = System.Label.CPQSAPUrl+'&Mode=3&I_Quote='+objApp.Quote_Number__c+ '&I_ACC_NAME='+objApp.Account_Name__c+ '&I_OPP_ID='+objApp.Opportunity_Id__c+ '&I_OPP_NAME='+objApp.Opportunity_Name__c + '&i_rpl_status='+objApp.Opportunity__r.Account.RPL_status__c+ '&I_COUNTRY='+objApp.Opportunity__r.Country__c+'&iframe=X';  
    }  
    public PageReference SaveRecord() 
    {
        update objApp;
        isSaved = false;
        return null;
    }
    public PageReference CancelRecord() 
    {
        string GetSAPURL = '/apex/CPQSAPSelectionPage?id='+objApp.Opportunity__c+'&Mode=2&pageMode=EditQuote&I_Quote='+objApp.Quote_Number__c+ '&I_ACC_NAME='+objApp.Account_Name__c+ '&I_OPP_ID='+objApp.Opportunity_Id__c+ '&I_OPP_NAME='+objApp.Opportunity_Name__c + '&i_rpl_status='+objApp.Opportunity__r.Account.RPL_status__c+ '&I_COUNTRY='+objApp.Opportunity__r.Country__c+'&Mode=2&iframe=X';
        Delete objApp;
        PageReference Page=new PageReference(GetSAPURL);
        page.setRedirect(false);
        return page;
    }
     public PageReference EditRecord() 
    {
       isSaved = true; 
       return null;
    }
}