objects/Approval__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Flow_Type__c</fullName>
        <label>Approval Flow Type</label>
        <picklist>
            <picklistValues>
                <fullName>Unanimous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sequential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approval_Type__c</fullName>
        <label>Approval Type</label>
        <picklist>
            <picklistValues>
                <fullName>Informal Contract Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Discount Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outlier Discount Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Standard Term (Contract Length)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Negotiated Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special T&amp;C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RTS Administrative Fee Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Push To</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pursuit_Budget_USD__c</fullName>
        <description>Pursuit Budget (USD)</description>
        <label>Pursuit Budget (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Approval_Matrix__c.object
<CustomObject>
    <description>Object to store the Approval Routing rules</description>
    <fields>
        <fullName>Account_Region__c</fullName>
        <label>Account Region</label>
        <picklist>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Flow_Type__c</fullName>
        <label>Approval Flow Type</label>
        <picklist>
            <picklistValues>
                <fullName>Unanimous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sequential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approval_Matrix_Name__c</fullName>
        <externalId>true</externalId>
        <label>Approval Matrix Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Approval_Type__c</fullName>
        <label>Approval Type</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity Business Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SND</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Level_13__c</fullName>
        <label>Approver Level 13</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Level_17__c</fullName>
        <label>Approver Level 17</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Level_1__c</fullName>
        <label>Approver Level 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Level_5__c</fullName>
        <label>Approver Level 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Level_9__c</fullName>
        <label>Approver Level 9</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Level_Type_13__c</fullName>
        <label>Approver Level Type 13</label>
        <picklist>
            <picklistValues>
                <fullName>Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Function</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Level_Type_17__c</fullName>
        <label>Approver Level Type 17</label>
        <picklist>
            <picklistValues>
                <fullName>Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Function</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Level_Type_1__c</fullName>
        <label>Approver Level Type 1</label>
        <picklist>
            <picklistValues>
                <fullName>Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Function</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Level_Type_5__c</fullName>
        <label>Approver Level Type 5</label>
        <picklist>
            <picklistValues>
                <fullName>Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Function</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Level_Type_9__c</fullName>
        <label>Approver Level Type 9</label>
        <picklist>
            <picklistValues>
                <fullName>Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver Role</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Function</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Owner_BG__c</fullName>
        <label>Owner BG</label>
        <picklist>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Approval Matrix</label>
    <nameField>
        <displayFormat>AM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Approval_Matrix_Element__c.object
<CustomObject>
    <description>Object to store the Approval Matrix detail information</description>
    <fields>
        <fullName>Approval_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Matrix</label>
        <referenceTo>Approval_Matrix__c</referenceTo>
        <relationshipName>Approval_Matrix_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Match_Type__c</fullName>
        <inlineHelpText>For Data Types BOOLEAN, INTEGER  use &apos;Equals&apos;
For Data Types STRING, PICKLIST, MULTIPICKLIST use &apos;Contains&apos; or &apos;Starts With&apos;
For Data Types CURRENCY use &apos;Range&apos;</inlineHelpText>
        <label>Match Type</label>
        <picklist>
            <picklistValues>
                <fullName>Equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Range</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starts With</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval__c</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value_Max__c</fullName>
        <label>Value Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value_Min__c</fullName>
        <label>Value Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Approval Matrix Item</label>
    <nameField>
        <displayFormat>MD-{00000000}</displayFormat>
        <label>Matrix Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Matrix Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/World_Region__c.object
<CustomObject>
    <description>For testing World Region</description>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>World Region</label>
    <nameField>
        <label>World Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>World Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DGApprovalReminderTest.cls
@isTest(seeAllData=true)
public Class DGApprovalReminderTest {
    public Static List<Approval_Matrix__c> matrixList=new List<Approval_Matrix__c>();
    public static List<Approval_Matrix_Element__c> matrixItemList=new List<Approval_Matrix_Element__c>();
    public static List<Opportunity> opplist=new List<Opportunity>();
    public static List<Approval__c> approvalList=new List<Approval__c>();
    public static User user2;
    
    public static void setupData(){
    
        //Approvers creation
        List<User> approversList=new List<User>();
        User app1= new User();
        app1= TestingSetupDataUtil.createUser('stAppr1','abc1@hp.com','emailap1@hp.com','UTF-8','Tertlan','en_US','en_US','America/Los_Angeles','saeestap1@hp.com','87654381',Userinfo.getProfileId());
        app1.Approver_Role__c='AP-1011';
        approversList.add(app1);
        
        
        
        insert approversList;
        
        
        
        Approval_Matrix__c am1=new Approval_Matrix__c();
        am1.Account_Region__c='ALL';
        am1.Owner_BG__c='ES;EG;SW';
        am1.Approval_Flow_Type__c='Hybrid';
        am1.Approval_Type__c='Opportunity Review';
        am1.Approval_Matrix_Name__c='ES flowType1';
        am1.Weight__c=2000000000;
        am1.Active__c=true;
        am1.Approver_Level_1__c='TestT1';
        am1.Approver_Level_Type_1__c='Approver Role';
        am1.Approver_Level_5__c='AP-1011';
        am1.Approver_Level_Type_5__c='Approver Role';
        am1.Approver_Level_9__c='AP-1011';
        am1.Approver_Level_Type_9__c='Approver Role';
        am1.Approver_Level_13__c='AP-1011';
        am1.Approver_Level_Type_13__c='Approver Role';
        am1.Approver_Level_17__c='AP-1011';
        am1.Approver_Level_Type_17__c='Approver Role';
        
        matrixList.add(am1);
        
        
        insert matrixList;
        
        
        
        Approval_Matrix_Element__c ami6=new Approval_Matrix_Element__c();
        ami6.Approval_Matrix__c=matrixList[0].id;
        ami6.Field_Name__c='Pursuit Budget (USD)';
        ami6.field_Api_name__c='Pursuit_Budget_USD__c';
        ami6.Object__c='Approval__c';
        ami6.Match_Type__c='Range';
        ami6.Value_Max__c=3000;
        ami6.Value_Min__c=0;
        matrixItemList.add(ami6);
        
        insert matrixItemList;
        
        world_region__c wr=[select ID from world_region__C where Country_Name__c='United States'];
        /*Insert Account and Opportunity*/
        Account newAcc=TestingSetupDataUtil.createAccount('ApprovalFlowTest','test_22@hp.com','Customer');
        newAcc.World_Region1__c=wr.id;
        insert newAcc;
        
        User user1 = new User();
        user1 = TestingSetupDataUtil.createUser('stTest1','abc@hp.com','email1@hp.com','UTF-8','Tertlan','en_US','en_US','America/Los_Angeles','saeest@hp.com','87654321',Userinfo.getProfileId());
        user1.Business_Group__c='ES';
        insert user1;
        
        user2 = new User();
        user2 = TestingSetupDataUtil.createUser('stTest2','abc@hp.com','email2@hp.com','UTF-8','Tertlan','en_US','en_US','America/Los_Angeles','saeest2@hp.com','87654322',Userinfo.getProfileId());
        user2.Business_Group__c='Test';
        user2.managerID=user1.id;
        insert user2;
        
        opportunity newOpp=TestingSetupDataUtil.createOpportunity(newAcc.Id, 'testOpptyForApprovalFlow', system.today()+ 30);
        newOpp.owner__c=user1.id; 
        newOpp.stageName=  '01 - Understand Customer';
        
        opplist.add(newOpp);  
        
        insert opplist;
        /* inserting approval */
        Map<String, Schema.SObjectType> m = Schema.getGlobalDescribe() ;
        Schema.SObjectType s = m.get('Approval__c') ;
        Schema.DescribeSObjectResult cfrSchema = s.getDescribe() ;
        Map<String,Schema.RecordTypeInfo> RecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
        
        Id rcdType= RecordTypeInfo.get('Opportunity Review').getRecordTypeId();
              
        Approval__c approval=new Approval__c();
        approval.opportunity__c=opplist[0].id;
        approval.RecordTypeID=rcdType;
        approval.Pursuit_Budget_USD__c=2000;
        approvalList.add(approval);
        
        insert approvalList;
        
        
        system.assertEquals(approversList[0].Approver_Role__c,'AP-1011');
        
       
    }
    
     public static testMethod void RemindermailTest() {
         Test.startTest();
         setupData();
         system.runAs(user2){
         // Add parameters to page URL
         
         ApexPages.currentPage().getParameters().put('id', approvalList[0].id);
         ApexPages.StandardController sc = new ApexPages.StandardController(approvalList[0]);
         DGPopulatingApprovers dpa=new DGPopulatingApprovers(sc);
         dpa.populateApprovers();
         DGBatchSchedulerReminder rem=new DGBatchSchedulerReminder();   

          datetime currentDateTime1 = datetime.now();
         // String min1 = String.valueOf(math.mod((currentDateTime1.minute() + 0),60));
          integer min=currentDateTime1.minute();
          integer hour1=currentDateTime1.hour();
          
          if(min==59){
              min=01;
              if(hour1==23){
               hour1=00;
              }else{
                  hour1=hour1+1;
              }
          }             
          
          
          String schExp1=hour1+' '+min+' * * * ? ';
          
          //String schExp1 = currentDateTime1.hour()+' '+(currentDateTime1.minute()+1) +' * * * ? ';
          system.schedule('DGBatchSchedulerReminder:'+datetime.now(), schExp1, rem); 

             
             
        } 
         
         
         Test.stopTest();
         
     }
}