objects/Approval__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Opportunity__r.Account.Name</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Shipping_City__c</fullName>
        <formula>Opportunity__r.Account_Shipping_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Shipping City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Description__c</fullName>
        <label>Approval Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <formula>Opportunity__r.Opportunity_ID__c</formula>
        <label>Opportunity Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <formula>Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Approach__c</fullName>
        <label>Pricing Approach</label>
        <picklist>
            <picklistValues>
                <fullName>Binding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Binding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indicative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pursuit_Budget_USD__c</fullName>
        <description>Pursuit Budget (USD)</description>
        <label>Pursuit Budget (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requestor_Comments__c</fullName>
        <label>Requestor Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Total_Opportunity_Value__c</fullName>
        <formula>Opportunity__r.Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Opportunity Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity_Pursuit_Resource_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Approval__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval</label>
        <referenceTo>Approval__c</referenceTo>
        <relationshipLabel>Opportunity Pursuit Resource Requirement</relationshipLabel>
        <relationshipName>Opportunity_Pursuit_Resource_Requirement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_End_Date__c</fullName>
        <label>Estimated End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Start_Date__c</fullName>
        <label>Estimated Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pursuit_Team_Name_Role__c</fullName>
        <label>Pursuit Team Name/Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_subregion_Country__c</fullName>
        <label>Region/subregion/Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_Hours__c</fullName>
        <label>Requested Hours</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Pursuit Resource Requirement</label>
    <nameField>
        <label>Opportunity Pursuit Resource Requirement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Pursuit Resource Requirement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DGPursuitResourcesController.cls
/*
Created by: Venkatesh S
Created on: 15/04/2013
Comments  : Controller for Component DGPursuitResourcesComponent to show Pursuit Resources as a table in Deal Goverance Email Notification
*/
public class DGPursuitResourcesController {
public string AppId{get;set;}
public List<Opportunity_Pursuit_Resource_Requirement__c> getPursuitResource() 
    {
    List<Opportunity_Pursuit_Resource_Requirement__c> listPursuitResources = [ Select Pursuit_Team_Name_Role__c, Region_subregion_Country__c, Estimated_Start_Date__c, Estimated_End_Date__c, Requested_Hours__c from Opportunity_Pursuit_Resource_Requirement__c where Approval__c=:this.AppId];
    return listPursuitResources;
    }
    
public List<approval__c> getOpportunityInfo() 
    {
    List<approval__c> ListApprovalOpportunityInfo = [ Select id, Opportunity_Id__c, Opportunity_Name__c, Account_Name__c, Account_Shipping_City__c, Total_Opportunity_Value__c, Opportunity__r.Description, Approval_Description__c, Requestor_Comments__c, Pursuit_Budget_USD__c, Pricing_Approach__c from approval__c where id=:this.AppId];
    return listApprovalOpportunityInfo;
    }
}