objects/Approval__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Description__c</fullName>
        <label>Approval Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Flow_Type__c</fullName>
        <label>Approval Flow Type</label>
        <picklist>
            <picklistValues>
                <fullName>Unanimous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sequential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approval_Type__c</fullName>
        <label>Approval Type</label>
        <picklist>
            <picklistValues>
                <fullName>Informal Contract Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Discount Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outlier Discount Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Standard Term (Contract Length)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Negotiated Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special T&amp;C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RTS Administrative Fee Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Push To</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CA_Name__c</fullName>
        <label>CA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CA_eMail__c</fullName>
        <label>CA eMail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Country_Time_Zone__c</fullName>
        <description>This time zone needs to match the country selected on this case in order to have the correct due date, considering the business hours and public holidays for that country, calculated.</description>
        <label>Case Country Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>(GMT+00:00) British Standard Time (Europe/London)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+00:00) Greenwich Mean Time (GMT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+00:00) Irish Standard Time (Europe/Dublin)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+00:00) Western European Standard Time (Europe/Lisbon)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+01:00) British Summer Time (Europe/London)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+01:00) Central European Standard Time (Europe/Amsterdam)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+01:00) Central European Standard Time (Europe/Berlin)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+01:00) Central European Standard Time (Europe/Brussels)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+01:00) Central European Standard Time (Europe/Paris)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+01:00) Central European Standard Time (Europe/Prague)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+01:00) Central European Standard Time (Europe/Rome)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+01:00) Central European Time (Africa/Algiers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+01:00) Irish Summer Time (Europe/Dublin)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+01:00) Western European Summer Time (Europe/Lisbon)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Central European Summer Time (Europe/Amsterdam)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Central European Summer Time (Europe/Berlin)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Central European Summer Time (Europe/Brussels)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Central European Summer Time (Europe/Paris)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Central European Summer Time (Europe/Prague)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Central European Summer Time (Europe/Rome)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Eastern European Standard Time (Europe/Athens)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Eastern European Standard Time (Europe/Bucharest)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Eastern European Standard Time (Europe/Helsinki)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Eastern European Standard Time (Europe/Istanbul)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Eastern European Time (Africa/Cairo)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) Israel Standard Time (Asia/Jerusalem)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+02:00) South Africa Standard Time (Africa/Johannesburg)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+03:00) Arabian Standard Time (Asia/Baghdad)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+03:00) Arabian Standard Time (Asia/Kuwait)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(GMT+03:00) Arabian Standard Time (Asia/Riyadh)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Origin__c</fullName>
        <label>Case Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <formula>Opportunity__r.Opportunity_ID__c</formula>
        <label>Opportunity Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Detail__c</fullName>
        <label>Quote Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <description>Renewal Opportunties Approval</description>
        <label>Renewal</label>
    </recordTypes>
    <recordTypes>
        <fullName>SND</fullName>
        <active>true</active>
        <label>SND</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CPQ_Quote_URL__c</fullName>
        <description>Used in CPQ Track</description>
        <label>Quote URL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Åland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_to_Market__c</fullName>
        <description>Shows if request is for direct or channel customer</description>
        <label>Route to Market</label>
        <picklist>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indirect</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Competitors__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitors</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Competitors Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CPQSAPLandingPageCS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This is using is CPQSAPLandingPageCtrl</description>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Decimal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Decimal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieldAPI__c</fullName>
        <label>FieldAPI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectAPI__c</fullName>
        <label>ObjectAPI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URLParameter__c</fullName>
        <label>URLParameter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CPQSAPLandingPageCS</label>
</CustomObject>

classes/CPQSAPLandingPageCtrl.cls
/***********************************************************
Author: Shaijan Thomas
Created Date: 22-07-2013
Release: R6
Capability: CPQ
Description:Controller class for special pricing, Quote and Request Assistance
************************************************************/
public class CPQSAPLandingPageCtrl {
    public string newPageUrl {get;set;}
    public string UrlName{get;set;}
    public string UrleMail{get;set;}
    public string SpecialPricing, QuotetoOrder, OpportunityID;
    public string QuoteNumber{get;set;}
    public list < CPQSAPLandingPageCS__c > oCustomSetting = new list < CPQSAPLandingPageCS__c > ();
    public Case oCase{get;set;}
    public Boolean showCaseEditPage{get;set;}
    public Opportunity objOppty{get;set;}
    public Boolean showOrderForm{get;set;}
    public String QuoteDetailURL{get;set;}
    
    public List<String> listDescriptionFields{get;set;}
    public Map<String,String> mapDescriptionLabelWithValue{get;set;}
    
    public CPQSAPLandingPageCtrl() {
        showCaseEditPage = false;
        showOrderForm = false;
        listDescriptionFields = new List<String>();
        mapDescriptionLabelWithValue = new Map<String,String>();
        system.debug('***Hiting URL *** '+ApexPages.currentPage());
        SpecialPricing = ApexPages.currentPage().getParameters().get('SpecialPricing');
        QuotetoOrder = ApexPages.currentPage().getParameters().get('QuotetoOrder');
        OpportunityID = ApexPages.currentPage().getParameters().get('OpportunityID');
        QuoteNumber = ApexPages.currentPage().getParameters().get('QuoteNumber');
        UrleMail = ApexPages.currentPage().getParameters().get('CAemail');
        UrlName = ApexPages.currentPage().getParameters().get('CAName');
    }
    public PageReference OnLoadCreateCaseorApproval() {
        try {
            if(ApexPages.currentPage().getParameters().get('CaseId') != null && ApexPages.currentPage().getParameters().get('CaseId') != ''){
                newPageUrl = '/' + ApexPages.currentPage().getParameters().get('CaseId');
                return null;
            }
            if(ApexPages.currentPage().getParameters().get('QuoteDetailURL') != null && ApexPages.currentPage().getParameters().get('QuoteDetailURL') != ''){
                Case objCase = [select id,CPQ_Quote_URL__c from Case where id=: ApexPages.currentPage().getParameters().get('QuoteDetailURL')];
                if(objCase != null){
                    newPageUrl = objCase.CPQ_Quote_URL__c;
                }
                return null;
            }
            string urlParameter;
            oCase = new case ();
            try {
                objOppty = [select id,Name,Opportunity_ID__c,Owner.Name,owner.Email,AccountId,Account.Name,Route_To_Market__c,Account.RPL_status__c,Country__c,Account.World_Region1__r.Name from opportunity where Opportunity_ID__c = : OpportunityID];
            } catch (exception e) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Opportunity Id is null or Invalid : ' + OpportunityID));
            }
            if (SpecialPricing == 'Y') {
                ID ApprovalRecordTypeID = Schema.SObjectType.Approval__c.getRecordTypeInfosByName().get('SND').getRecordTypeId();
                Approval__c oApproval = new Approval__c();
                oApproval.RecordTypeId = ApprovalRecordTypeID;
                oApproval.Approval_Description__c = 'Special Pricing Request for Quote : ' + QuoteNumber;
                if(objOppty != null){
                    oApproval.Quote_Detail__c = System.Label.CPQSAPUrl+'&Mode=3&I_Quote='+QuoteNumber+ '&I_ACC_NAME='+objOppty.Account.Name+ '&I_OPP_ID='+objOppty.Opportunity_ID__c+ '&I_OPP_NAME='+objOppty.Name + '&i_rpl_status='+objOppty.Account.RPL_status__c+ '&I_COUNTRY='+objOppty.Account.World_Region1__r.Name+'&iframe=X';
                    oApproval.Opportunity__c = objOppty.Id;
                }
                for (CPQSAPLandingPageCS__c oCSObj: [select Name, Date__c, Decimal__c, FieldAPI__c, ObjectAPI__c, URLParameter__c from CPQSAPLandingPageCS__c where ObjectAPI__c= 'Approval__c']){
                    urlParameter = ApexPages.currentPage().getParameters().get(oCSObj.URLParameter__c);
                    if (urlParameter != null && urlParameter != '')
                        if (oCSObj.Decimal__c) {
                            try {
                                system.debug('********urlParameter ******'+urlParameter );
                                if(urlParameter.contains(' '))
                                      urlParameter = urlParameter.removeEnd(' ').trim();
                                if(urlParameter.contains(',')){
                                    urlParameter = urlParameter.remove(',');
                                }
                                if(urlParameter.contains('-')){
                                    urlParameter = urlParameter.removeEnd('-').trim();
                                    oApproval.put(oCSObj.FieldAPI__c, Decimal.valueOf(urlParameter)*(-1.0));
                                }
                                else if(urlParameter.contains('+')){
                                    urlParameter = urlParameter.removeEnd('+').trim();
                                    oApproval.put(oCSObj.FieldAPI__c, Decimal.valueOf(urlParameter));
                                }
                                else
                                    oApproval.put(oCSObj.FieldAPI__c, Decimal.valueOf(urlParameter));
                            } catch (exception e) {
                                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, oCSObj.FieldAPI__c + ' has a value : ' + urlParameter + ', which is a invalid Integer or Decimal'));
                            }
                        } 
                        else if (oCSObj.Date__c) {
                            try {
                                oApproval.put(oCSObj.FieldAPI__c, Date.valueOf(urlParameter));
                            } catch (exception e) {
                                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, oCSObj.FieldAPI__c + ' Field found Invalid Date format : ' + urlParameter));
                            }
                        } else
                            oApproval.put(oCSObj.FieldAPI__c, urlParameter);
                }
                oApproval.CA_Name__c = UrlName;
                oApproval.CA_eMail__c = UrleMail;
                oApproval.Status__c = 'Open';
                oApproval.Case_Origin__c = 'Self Service UI';
                oApproval.Approval_Type__c = 'Special Negotiated Discount';
                oApproval.Approval_Flow_Type__c='Hybrid';
                oApproval.Case_Country_Time_Zone__c = CPQConvertTimeZone.ConvertTimeZoneValue(string.valueof(UserInfo.getTimeZone()));
                if(ApexPages.currentPage().getParameters().get('RequestType') == 'ZQ')
                    oApproval.Request_Type__c = 'New Business Quote';
                else if(ApexPages.currentPage().getParameters().get('RequestType') == 'ZQRN')
                    oApproval.Request_Type__c = 'Renewal Amendment';
                oApproval.Competitors__c = '';    
                if(ApexPages.hasMessages(ApexPages.Severity.ERROR))
                    return null;
                for (Competitors__c objOpportunityCompetitors : [Select Competitor_Name__c from  Competitors__c where Opportunity__c=:objOppty.Id])
                {
                  oApproval.Competitors__c = oApproval.Competitors__c +  objOpportunityCompetitors.Competitor_Name__c + '; \n\r';
                }
                insert oApproval;
                newPageUrl = '/apex/CPQSNDApprovalProcessPage?id=' + oApproval.id;
            }
            else{
                //ID CaseRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('CO Case').getRecordTypeId();
                if(objOppty != null){
                    oCase.Opportunity__c = objOppty.Id;
                    oCase.AccountId = objOppty.AccountId;
                    oCase.Route_to_Market__c = objOppty.Route_To_Market__c;
                    oCase.Sold_to_Party__c = objOppty.Account.Name;
                    oCase.CPQ_Quote_URL__c = System.Label.CPQSAPUrl+'&Mode=3&I_Quote='+QuoteNumber+ '&I_ACC_NAME='+objOppty.Account.Name+ '&I_OPP_ID='+objOppty.Opportunity_ID__c+ '&I_OPP_NAME='+objOppty.Name + '&i_rpl_status='+objOppty.Account.RPL_status__c+ '&I_COUNTRY='+objOppty.Account.World_Region1__r.Name+'&iframe=X';
                    system.debug('*********oCase.CPQ_Quote_URL__c*******'+oCase.CPQ_Quote_URL__c);
                    QuoteDetailURL = System.Label.CPQSAPUrl+'&Mode=3&I_Quote='+QuoteNumber+ '&I_ACC_NAME='+objOppty.Account.Name+ '&I_OPP_ID='+objOppty.Opportunity_ID__c+ '&I_OPP_NAME='+objOppty.Name + '&i_rpl_status='+objOppty.Account.RPL_status__c+ '&I_COUNTRY='+objOppty.Country__c+'&iframe=X';
                    oCase.CPQ_Quote_Number__c = QuoteNumber;
                }
                oCase.Origin='Self Service';
                oCase.Business_Type__c = 'Standard';
                oCase.Reason = 'Other';
                oCase.Description = '';
                oCase.Subject = 'Self-Service Quote Request '+QuoteNumber;
                oCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('CO Case').getRecordTypeId();
                if(QuotetoOrder == 'Y'){
                    oCustomSetting = [select Date__c, Decimal__c, FieldAPI__c, ObjectAPI__c, URLParameter__c from CPQSAPLandingPageCS__c where ObjectAPI__c ='Case' or ObjectAPI__c = 'ODescription'];
                    oCase.Request_Type__c = 'Orders';
                    showOrderForm = true;
                }
                else{
                    oCustomSetting = [select Name, Date__c, Decimal__c, FieldAPI__c, ObjectAPI__c, URLParameter__c from CPQSAPLandingPageCS__c where ObjectAPI__c= 'Case' or ObjectAPI__c = 'RDescription'];
                    if(ApexPages.currentPage().getParameters().get('RequestType') != null && ApexPages.currentPage().getParameters().get('RequestType') != ''){
                        if(ApexPages.currentPage().getParameters().get('RequestType') == 'ZQ')
                            oCase.Request_Type__c = 'New Business Quote';
                        else if(ApexPages.currentPage().getParameters().get('RequestType') == 'ZQRN')
                            oCase.Request_Type__c = 'Renewal Amendment';
                    }
                    
                }
                for (CPQSAPLandingPageCS__c oCSObj: oCustomSetting) {
                    urlParameter = ApexPages.currentPage().getParameters().get(oCSObj.URLParameter__c);
                    if (oCSObj.ObjectAPI__c == 'ODescription' || oCSObj.ObjectAPI__c == 'RDescription'){
                        //oCase.Description += '\r\n' + oCSObj.FieldAPI__c + ' : ' + urlParameter;
                        listDescriptionFields.add(oCSObj.FieldAPI__c);
                        mapDescriptionLabelWithValue.put(oCSObj.FieldAPI__c,urlParameter);
                        system.debug('*******listDescriptionFields*******'+listDescriptionFields);
                        system.debug('*******mapDescriptionLabelWithValue*******'+mapDescriptionLabelWithValue);
                    }
                    else if (urlParameter != null && urlParameter != ''){
                        if (oCSObj.Decimal__c) {
                            try {
                                if(urlParameter.contains(' '))
                                      urlParameter = urlParameter.removeEnd(' ').trim();
                                if(urlParameter.contains(',')){
                                    urlParameter = urlParameter.remove(',');
                                }
                                if(urlParameter.contains('-')){
                                    urlParameter = urlParameter.removeEnd('-').trim();
                                    oCase.put(oCSObj.FieldAPI__c, Decimal.valueOf(urlParameter)*(-1.0));
                                }
                                else if(urlParameter.contains('+')){
                                    urlParameter = urlParameter.removeEnd('+').trim();
                                    oCase.put(oCSObj.FieldAPI__c, Decimal.valueOf(urlParameter));
                                }
                                else
                                    oCase.put(oCSObj.FieldAPI__c, Decimal.valueOf(urlParameter));
                            } catch (exception e) {
                                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, oCSObj.FieldAPI__c + ' has a value : ' + urlParameter + ', which is a invalid Integer or Decimal'));
                            }
                        }
                        else if (oCSObj.Date__c) {
                            try {
                                oCase.put(oCSObj.FieldAPI__c, Date.valueOf(urlParameter));
                            } catch (exception e) {
                                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, oCSObj.FieldAPI__c + ' Field found Invalid Date format : ' + urlParameter));
                            }
                        } 
                        else
                            oCase.put(oCSObj.FieldAPI__c, urlParameter);
                    }
                }
                for (user obj : [select Id,eMail,Name,Business_Group__c,Region__c,Country, TimeZoneSidKey from user where (Email = : UrleMail or Id = :Userinfo.getUserId()) and IsActive = true and UserType = 'Standard']){
                    if (obj.eMail == UrleMail){
                        oCase.OwnerId = obj.Id;
                        oCase.Case_Origin_is_Interface__c = true;
                    }
                    if(obj.id == Userinfo.getUserId()){
                        oCase.Case_Requestor__c = obj.Name;
                        oCase.Case_Requestor_Email__c = obj.eMail;
                        oCase.BG__c = obj.Business_Group__c;
                        oCase.Region__c = obj.Region__c;
                        oCase.Country__c = obj.Country;
                        oCase.Requestor_s_TimeZone__c = CPQConvertTimeZone.ConvertTimeZoneValue(string.valueof(obj.TimeZoneSidKey));
                    }
                }
                if(!oCase.Case_Origin_is_Interface__c){
                    oCase.Description = oCase.Description +'\n\r CA Name : ' + UrlName +'\n\r CA eMail : ' + UrleMail;
                }
                oCase.Description = oCase.Description +'\n\r Quote Number  : ' + QuoteNumber;
                if(ApexPages.hasMessages(ApexPages.Severity.ERROR))
                    return null;
                else
                    showCaseEditPage = true;
            }
        }
        catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        return null;
    }
    
    public PageReference insertCase() {
        try{
            if(oCase!=null){
                system.debug('*******mapDescriptionLabelWithValue*******'+mapDescriptionLabelWithValue);
                for(String fieldLabel : mapDescriptionLabelWithValue.keyset()){
                    oCase.Description += '\r\n' + fieldLabel + ' : ' + mapDescriptionLabelWithValue.get(fieldLabel);
                }
                insert oCase;
                //newPageUrl = '/' + oCase.id;
                PageReference FinalPage=new PageReference('/apex/CPQSAPLandingPage?CaseId='+oCase.id);
                FinalPage.setRedirect(true);
                return FinalPage;
            }        
        }
        catch (exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }

        return null;
    }
    
    public PageReference insertAndCloseCase() {
        try{
            if(oCase!=null){
                for(String fieldLabel : mapDescriptionLabelWithValue.keyset()){
                    oCase.Description += '\r\n' + fieldLabel + ' : ' + mapDescriptionLabelWithValue.get(fieldLabel);
                }
                insert oCase;
                //newPageUrl = '/' + oCase.id+'/s?retURL=/'+oCase.id+'&co=1';
                PageReference FinalPage=new PageReference('/apex/CPQSAPLandingPage?CaseId='+oCase.id+'/s?retURL=/'+oCase.id+'&co=1');
                FinalPage.setRedirect(true);
                return FinalPage;
            }        
        }
        catch (Exception e) {
            system.debug('*****e*****'+e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }

        return null;
    }
}