objects/Batch_Size__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <label>Batch Size</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Size</label>
</CustomObject>

objects/Channel_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>Location__r.Location_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>&quot;Lookup to a Location object&apos;s record.
This field is a lookup to an existing Location child record when a parent Business Relationship record is selected in the existing &quot;&quot;Partner&quot;&quot; field.This is in support to attaching an Opportunity to a Partner Site.&quot;</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Alliance and Channel Partners</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Alliance and Channel Partners</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Partner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance and Channel Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Address country.</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDCP_Organization_ID__c</fullName>
        <formula>Account__r.MDCP_Organization_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MDCP Organization ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Portal_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Portal Eligible</label>
        <type>Checkbox</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Access__c</fullName>
        <label>Case Access</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsConfidential__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate sales territory is confidential or not.</description>
        <label>IsConfidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean indicating whether Territory is exposed to Partner Accounts only</description>
        <label>IsPartner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MyComp_Sales_Territory_Name__c</fullName>
        <description>Created in R6</description>
        <label>Sales Territory Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isExternal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isExternal</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Location_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Location__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>Location__r.Location_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Locator Id</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Location Assignment</label>
    <nameField>
        <label>STLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Location Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TMEngineAccountRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>AccountRecordType__c</fullName>
        <label>AccountRecordType</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>TMEngineAccountRecordType</label>
</CustomObject>

classes/TMAllianceChannedPartnerTerrBatchTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */

// TM: Nasir:Test method for "TMAllianceChannedPartnerTerritoryBatch": Start

@isTest(SeeAllData=true)
private class TMAllianceChannedPartnerTerrBatchTest {

   static testMethod void TMAllianceChannedPartnerTerritoryBatch() {
        test.startTest();
        TMEngineAccountRecordType__c lastRun = TMEngineAccountRecordType__c.getValues('Allianc/ChanPartTimeStamp');
        lastRun.AccountRecordType__c='2013-01-21 12:14:05';
        update lastRun ;
        
        String RecordTypeId = RecordTypeIdHelper.getRecordTypeId('Account','Partner');
        Account acc1 = new Account(Name='PrevLocTestAcc1',RecordTypeId=RecordTypeId,Partner_Portal_Eligible__c=true,MDCP_Business_Relationship__c='Reseller',MDCP_Business_Relationship_ID__c='111',MDCP_Organization_ID__c='111',Channel_Partner_Flag__c=true);
        insert acc1;
        Account acc2 = new Account(Name='PrevLocTestAcc2',RecordTypeId=RecordTypeId,Partner_Portal_Eligible__c=true,MDCP_Business_Relationship__c='Reseller',MDCP_Business_Relationship_ID__c='112',MDCP_Organization_ID__c='112',Channel_Partner_Flag__c=true);
        insert acc2;
        Location__c loc1 = new Location__c(Name='1500',Location_Name__c='Blr',Account__c = acc1.id);
        insert loc1;
        Location__c loc2 = new Location__c(Name='1600',Location_Name__c='Mys',Account__c = acc2.id,Country__c='India');
        insert loc2;
        Sales_Territory__c salesTerr1 = new Sales_Territory__c (Name='TestPreview1',Account_Access__c='Edit',Case_Access__c='Edit',Opportunity_Access__c='Edit',IsConfidential__c=False,IsPartner__c=true,MyComp_Sales_Territory_Name__c = 'ST-TestTerrACP');
        insert salesTerr1;
        Sales_Territory_Location_Assignment__c stla= new Sales_Territory_Location_Assignment__c(Location__c=loc1.id,Sales_Territory__c=salesTerr1.id);
        insert stla;
        Sales_Territory_Location_Assignment__c stla1= new Sales_Territory_Location_Assignment__c(Location__c=loc2.id,Sales_Territory__c=salesTerr1.id);
        insert stla1; 
        
        Account accCust = TestingSetupDataUtil.createAccount('custAcc', 'custAcc@custTest.com', 'Customer');
        Insert accCust;
        
        opportunity opptyTest = TestingSetupDataUtil.createOpportunity(string.valueOf(accCust.id),'opptyTest', system.today()+ 30);
        insert opptyTest;  

        
        Channel_Partner__c chhPart = new Channel_Partner__c();
        chhPart.Channel_Partner__c = acc1.Id;
        chhPart.Opportunity__c = opptyTest.Id;
        chhPart.Location__c=loc1.Id;
        insert chhPart;     
        
        List<Sales_Territory_Location_Assignment__c> lstla= new List<Sales_Territory_Location_Assignment__c>();
        lstla.add(stla1);
        lstla.add(stla);
        
        delete stla;
        
        system.debug('in first method>>>> stla.isdeleted'+ stla.IsDeleted);
        
         if(stla1!=null && lastRun.AccountRecordType__c!=null){
            Datetime newTimeStamp = datetime.now();
            lastRun.AccountRecordType__c = String.valueOf(newTimeStamp);
            update lastRun;
        }
        
/*        set<id> deletedId= new set<id>();
        if(stla.IsDeleted==true){       
            deletedId.add(stla.Location__c);
        }    
*/         
        /*Database.BatchableContext ctx;
        TMAllianceChannedPartnerTerritoryBatch tm= new TMAllianceChannedPartnerTerritoryBatch();
        
        tm.start(ctx);
        tm.execute(ctx,lstla);
       
        Integer batchSize = Integer.valueOf(Batch_Size__c.getValues('Alliance and Channel Partner').Batch_Size__c);
        
        Id batchId = Database.executeBatch(new TMAllianceChannedPartnerTerritoryBatch(), batchSize);*/
        
        TMAllianceChanlPrtnrTerrSchedular tm= new TMAllianceChanlPrtnrTerrSchedular();
        datetime currentDateTime = datetime.now();
        String min = String.valueOf(math.mod((currentDateTime.minute()),60));
        
        String schExp = '0 '+min+' * * * ? ';
        system.schedule('TM Allaince Partner'+datetime.now(), schExp, tm);
        
        test.stopTest();
    }
    static testMethod void TMAllianceChannedPartnerTerritoryBatch1() {
        test.startTest();
        TMEngineAccountRecordType__c lastRun = TMEngineAccountRecordType__c.getValues('Allianc/ChanPartTimeStamp');
        lastRun.AccountRecordType__c='';
        update lastRun ;
        
        String RecordTypeId = RecordTypeIdHelper.getRecordTypeId('Account','Partner');
        Account acc1 = new Account(Name='PrevLocTestAcc1',RecordTypeId=RecordTypeId,Partner_Portal_Eligible__c=true,MDCP_Business_Relationship__c='Reseller',MDCP_Business_Relationship_ID__c='111',MDCP_Organization_ID__c='111',Channel_Partner_Flag__c=true);
        insert acc1;
        Account acc2 = new Account(Name='PrevLocTestAcc2',RecordTypeId=RecordTypeId,Partner_Portal_Eligible__c=true,MDCP_Business_Relationship__c='Reseller',MDCP_Business_Relationship_ID__c='112',MDCP_Organization_ID__c='112',Channel_Partner_Flag__c=true);
        insert acc2;
        Location__c loc1 = new Location__c(Name='1500',Location_Name__c='Blr',Account__c = acc1.id);
        insert loc1;
        Location__c loc2 = new Location__c(Name='1600',Location_Name__c='Mys',Account__c = acc2.id,Country__c='India');
        insert loc2;
        Sales_Territory__c salesTerr1 = new Sales_Territory__c (Name='TestPreview1',Account_Access__c='Edit',Case_Access__c='Edit',Opportunity_Access__c='Edit',IsConfidential__c=False,IsPartner__c=true,IsExternal__c = False,MyComp_Sales_Territory_Name__c = 'ST-TestTerrACP1');
        insert salesTerr1;
        Sales_Territory_Location_Assignment__c stla= new Sales_Territory_Location_Assignment__c(Location__c=loc1.id,Sales_Territory__c=salesTerr1.id);
        insert stla;
        Sales_Territory_Location_Assignment__c stla1= new Sales_Territory_Location_Assignment__c(Location__c=loc2.id,Sales_Territory__c=salesTerr1.id);
        insert stla1; 
        
        Account accCust = TestingSetupDataUtil.createAccount('custAcc', 'custAcc@custTest.com', 'Customer');
        Insert accCust;
        
        opportunity opptyTest = TestingSetupDataUtil.createOpportunity(string.valueOf(accCust.id),'opptyTest', system.today()+ 30);
        insert opptyTest;  

        
        Channel_Partner__c chhPart = new Channel_Partner__c();
        chhPart.Channel_Partner__c = acc1.Id;
        chhPart.Opportunity__c = opptyTest.Id;
        chhPart.Location__c=loc1.Id;
        insert chhPart;
        
        
        List<Sales_Territory_Location_Assignment__c > lstla= new List<Sales_Territory_Location_Assignment__c >();
        lstla.add(stla1);
        lstla.add(stla);
        delete stla; 
        
        
        system.debug('stla.isdeleted>>>'+stla.isdeleted);
        
        if( lastRun.AccountRecordType__c==null){
            Datetime newTimeStamp = datetime.now();
            lastRun.AccountRecordType__c = String.valueOf(newTimeStamp);
            update lastRun;
        }
/*        set<id> deletedId= new set<id>();
        if(stla.IsDeleted==true){
            deletedId.add(stla.Location__c);
        } 
*/             
        Database.BatchableContext ctx;
        TMAllianceChannedPartnerTerritoryBatch tm= new TMAllianceChannedPartnerTerritoryBatch();
        
        Integer batchSize = Integer.valueOf(Batch_Size__c.getValues('Alliance and Channel Partner').Batch_Size__c);
        
        
        Id batchId = Database.executeBatch(new TMAllianceChannedPartnerTerritoryBatch(), batchSize);
        test.stopTest();
    }
    
    static testMethod void UpdateOpportunitySharingTriggerUtilTest(){
        user testUser1 = new User(Profileid=userInfo.getProfileId(),Username='OpptyOwner12345@gmail.com',
                                 LastName='OpOw1',email='OpptyOwner124test1234@hp.com' ,Alias='OptyO1', 
                                 CommunityNickname='testO1',emailencodingkey='UTF-8', 
                                 languagelocalekey='en_US', localesidkey='en_US',timezonesidkey='America/Los_Angeles',
                                 Partner_Collaboration_Participating_User__c=true, Email_Address__c='Opptygemail1234@gmail.com',EmployeeNumber='',
                                 Legacy_Employee_Ref__c='09876510',Adoption_Role_Type__c = 'Account Executive');
     insert testUser1;
    
     user testUser2 = new User(Profileid=userInfo.getProfileId(),Username='OpptyOwner123457@gmail.com',
                                 LastName='OpOw2',email='OpptyOwner124test12345@hp.com' ,Alias='OptyO2', 
                                 CommunityNickname='testO2',emailencodingkey='UTF-8', 
                                 languagelocalekey='en_US', localesidkey='en_US',timezonesidkey='America/Los_Angeles',
                                 Partner_Collaboration_Participating_User__c=true, Email_Address__c='Opptygemail1235@gmail.com',EmployeeNumber='',
                                 Legacy_Employee_Ref__c='09876511',Adoption_Role_Type__c = 'Account Executive');
    insert testUser2;
    
    Account acc = TestingSetupDataUtil.createAccount('testAccount11','accountEmail11@test.com','Customer');
    insert acc;
    
    opportunity newOpp1 = new opportunity();
            newOpp1.name= 'test Oppty12';
            newOpp1.Accountid= acc.id;
            date closeDate = system.today();
            newOpp1.closeDate = closeDate.addDays(30);
            newOpp1.stagename='01 - Understand Customer';
            newOpp1.ownerId=testUser1.id;
            newOpp1.Managed_By__c='HP';
            insert newOpp1;
            Map<Id,Opportunity> oldOptyMap = new Map<Id,Opportunity>();
            oldOptyMap.put(newOpp1.Id,newOpp1);
            newOpp1.ownerId=testUser2.id;
            update newOpp1;
            Map<Id,Opportunity> newOptyMap = new Map<Id,Opportunity>();
            newOptyMap.put(newOpp1.Id,newOpp1);
    UpdateOpportunitySharingTriggerUtil.UpdateOpportunitySharing(newOptyMap,oldOptyMap);
    }
    
}