objects/Batch_Job_Invoker__c.object
<CustomObject>
    <description>Custom Object To Invoke batch based on Type.</description>
    <fields>
        <fullName>Account_Record_Type__c</fullName>
        <label>Account Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Consider_New_or_Changed_Territories_Only__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Consider New or Changed Territories Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>REgion__c</fullName>
        <label>Region</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Asia Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>InProgress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Territory Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialty Oppty Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialty Realignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialty On OLI Delete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Realignment Scheduler</label>
    <nameField>
        <label>Batch Job Invoker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realignment Scheduler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TMEngineScheduledFlag__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>TMEngineScheduled to be flagged TRUE until all batches complete, next schedule will only begin if flag is FALSE i.e all batches from first instance executed.</description>
    <fields>
        <fullName>SchedularFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SchedularFlag</label>
        <type>Checkbox</type>
    </fields>
    <label>TMEngineScheduledFlag__c</label>
</CustomObject>

classes/ProcessOpportunitySpecialtyBatchTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex class ProcessOpportunitySpecialtyBatch
 * @author: rahul.kunal (Accenture)
 */
@isTest (SeeAllData = true)
private class ProcessOpportunitySpecialtyBatchTest {

    /* 
     * @Desiption: Specialty Batch Process Test for Specialty Realignment.
     *
     */
     
     static testMethod void specialtyBatchTest(){
        
        test.startTest();
        Account acc = TestingSetupDataUtil.createAccount('testAccount_952PM', 'testAccount_9@mail.com','Customer');
        insert acc;
        //create a test opportunity
        Opportunity opty = TestingSetupDataUtil.createOpportunity(acc.Id,'Opty99ZZ_952PM',System.Today()+30);   
        opty.Type = 'New Business';
        opty.Route_To_Market__c = 'Direct';
        insert opty;
        TMEngineScheduledFlag__c SpecialityFlag = TMEngineScheduledFlag__c.getInstance('SpecialtyBatchFlag');
        SpecialityFlag.SchedularFlag__c = false;
        update SpecialityFlag;
        TMEngineScheduledFlag__c SpecialityFlag1 = TMEngineScheduledFlag__c.getInstance('SchedularFlagVal');
        SpecialityFlag1.SchedularFlag__c = false;
        update SpecialityFlag1;
        TMEngineScheduledFlag__c SpecialityFlag2 = TMEngineScheduledFlag__c.getInstance('TMEngineWeekend_flag');
        SpecialityFlag2.SchedularFlag__c = false;
        update SpecialityFlag2;

        Batch_Job_Invoker__c triggerObj = new Batch_Job_Invoker__c(Name='TestSpecialtyBatch',Region__c = 'APJ',STATUS__C='Submitted',Type__c = 'Specialty Realignment', Consider_New_or_Changed_Territories_Only__c = true,Account_Record_Type__c ='');
        insert triggerObj;
                
        test.stopTest();
        
     }
}