objects/Business_Impact__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Potential_Risk_ID__c</fullName>
        <label>Potential Risk ID</label>
        <referenceTo>Potential_Risk__c</referenceTo>
        <relationshipLabel>Business Impact</relationshipLabel>
        <relationshipName>Business_Impact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Business Impact</label>
    <nameField>
        <displayFormat>BI-{0000000000}</displayFormat>
        <label>Business Impact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Impact</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Business_Impact_Cause__c.object
<CustomObject>
    <fields>
        <fullName>Business_Impact_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Impact ID</label>
        <referenceTo>Business_Impact__c</referenceTo>
        <relationshipLabel>Business Impact Cause</relationshipLabel>
        <relationshipName>Business_Impact_Cause</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Root_Cause_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Root Cause ID</label>
        <referenceTo>Root_Cause__c</referenceTo>
        <relationshipLabel>Business Impact Cause</relationshipLabel>
        <relationshipName>Business_Impact_Cause</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Business Impact Cause</label>
    <nameField>
        <displayFormat>BIC-{0000000000}</displayFormat>
        <label>Business Impact Cause ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Impact Cause</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Offering_Release__c.object
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>OPP-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Potential_Risk__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <label>Project ID</label>
        <referenceTo>Offering_Release__c</referenceTo>
        <relationshipLabel>Potential Risks</relationshipLabel>
        <relationshipName>Potential_Risks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Potential Risk</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Potential Risk ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Process_Control__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Potential_Risk_ID__c</fullName>
        <label>Potential Risk ID</label>
        <referenceTo>Potential_Risk__c</referenceTo>
        <relationshipLabel>Process Control</relationshipLabel>
        <relationshipName>Process_Control</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Process Control</label>
    <nameField>
        <displayFormat>PC-{0000000000}</displayFormat>
        <label>Process Control ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Control</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Root_Cause__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Occurance__c</fullName>
        <label>Occurance</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Potential_Risk_ID__c</fullName>
        <label>Potential Risk ID</label>
        <referenceTo>Potential_Risk__c</referenceTo>
        <relationshipLabel>Root Cause</relationshipLabel>
        <relationshipName>Root_Cause</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Root Cause</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Root Cause ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cause</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Root_Cause_Control__c.object
<CustomObject>
    <fields>
        <fullName>Process_Control_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process Control ID</label>
        <referenceTo>Process_Control__c</referenceTo>
        <relationshipLabel>Root Cause Controls</relationshipLabel>
        <relationshipName>Root_Cause_Controls</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Root_Cause_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Root Cause ID</label>
        <referenceTo>Root_Cause__c</referenceTo>
        <relationshipLabel>Root Cause Controls</relationshipLabel>
        <relationshipName>Root_Cause_Controls</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Root Cause Control</label>
    <nameField>
        <displayFormat>RCC-{0000000000}</displayFormat>
        <label>Root Cause Control ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Root Cause Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Pavithra_WrapperController.cls
public class Pavithra_WrapperController {

    
    Public Offering_Release__c offeringReleaseObj{get;set;}
    public Potential_Risk__c potentialRiskObj{get;set;}
    


    public Business_Impact__c objBusinessImpact{get;set;}
    public Root_Cause__c objRootCause{get;set;}
    public Process_Control__c objProcessControl{get;set;}
    public Root_Cause_Control__c objRootCauseControl{get;set;}
    public Business_Impact_Cause__c objBusinessImpactCause{get;set;}
    Public List<Business_Impact__c> businessImpactList{get;set;}
    List<Business_Impact__c> business =new List<Business_Impact__c>();
    Public List<Root_Cause__c> rootCauseList{get;set;}
    
    public string description{get;set;}
    public String severity{get;set;}
    
    public Pavithra_WrapperController()
    {
    
        offeringReleaseObj = new Offering_Release__c();
        potentialRiskObj = new Potential_Risk__c();
        objProcessControl = new Process_Control__c();
        objRootCauseControl = new Root_Cause_Control__c();
        objBusinessImpactCause = new Business_Impact_Cause__c();
        //potentialRiskObj = [select Id,Description__c,Project_ID__c from Potential_Risk__c where Project_ID__c =:offeringReleaseObj.Id];
        system.Debug('########'+potentialRiskObj.Id);
        System.Debug('Test$$$$$'+offeringReleaseObj.Id);
    
    
    
        potentialRiskObj = new Potential_Risk__c();
        potentialRiskObj.Project_ID__c = 'a6yZ0000000DFz2';
        objBusinessImpact = new Business_Impact__c();
        objRootCause = new Root_Cause__c();
        businessImpactList = new List<Business_Impact__c>();
        rootCauseList = new List<Root_Cause__c>();
        businessImpactList.add(new Business_Impact__c());
        rootCauseList.add(new Root_Cause__c());
    }
    
    public Potential_Risk__c getPotentialRisk(){
        return potentialRiskObj;
    }
    
    public void addBusinessImpact(){
        businessImpactList.add(new Business_Impact__c());
        system.debug('#############'+businessImpactList);
    }
    
    public void addRootCause() {
        rootCauseList.add(new Root_Cause__c());
    }
    
    public void saveRecord()
    {   
        potentialRiskObj.Description__c = 'Testing1';
        insert potentialRiskObj;
        
        objBusinessImpact.Potential_Risk_ID__c = potentialRiskObj.Id;
        objBusinessImpact.Description__c = 'Test BI';
        severity = objBusinessImpact.Severity__c;
        insert objBusinessImpact;
        
        objRootCause.Description__c = 'Test Root Cause1';
        objRootCause.Occurance__c = '3';
        objRootCause.Potential_Risk_ID__c = potentialRiskObj.Id;
        insert objRootCause;
        
        objProcessControl.Potential_Risk_ID__c = potentialRiskObj.Id;
        objProcessControl.Description__c = 'Test Process Control1';
        insert objProcessControl;
        
        objRootCauseControl.Root_Cause_ID__c = objRootCause.Id;
        System.Debug('$$$$$$$$'+objRootCause.Id);
        objRootCauseControl.Process_Control_ID__c = objProcessControl.Id;
        System.Debug('$$$$$$$$'+objProcessControl.Id);
        insert objRootCauseControl;
        
        objBusinessImpactCause.Business_Impact_ID__c = objBusinessImpact.Id;
        objBusinessImpactCause.Root_Cause_ID__c = objRootCause.Id;
        insert objBusinessImpactCause;
        
    }
}