objects/Business_Impact__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Potential_Risk_ID__c</fullName>
        <label>Potential Risk ID</label>
        <referenceTo>Potential_Risk__c</referenceTo>
        <relationshipLabel>Business Impact</relationshipLabel>
        <relationshipName>Business_Impact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Business Impact</label>
    <nameField>
        <displayFormat>BI-{0000000000}</displayFormat>
        <label>Business Impact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Impact</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Potential_Risk__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <label>Project ID</label>
        <referenceTo>Offering_Release__c</referenceTo>
        <relationshipLabel>Potential Risks</relationshipLabel>
        <relationshipName>Potential_Risks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Potential Risk</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Potential Risk ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/pavithraPotentialRiskExtension.cls
public with sharing class pavithraPotentialRiskExtension {
    public Potential_Risk__c objPotentialRisk{get;set;}
    public string description{get;set;}
    public string severity{get;set;}
    public Business_Impact__c objBusinessImpact{get;set;}
    //Public List<Potential_Risk__c> potentialRiskList{get;set;}
    //Public List<Business_Impact__c> businessImpactList{get;set;}

    public pavithraPotentialRiskExtension() {
        objPotentialRisk = new Potential_Risk__c();
        objBusinessImpact = new Business_Impact__c();
        //potentialRiskList = new List<Potential_Risk__c>();
        //businessImpactList = new List<Business_Impact__c>();
       // potentialRiskList = [select Id,Description__c,Owner_Team_Member_ID__c,Project_ID__c from Potential_Risk__c where Id=:objPotentialRisk.Id];
       // businessImpactList = [select Id,Potential_Risk_ID__c,Description__c,Severity__c from Business_Impact__c where Potential_Risk_ID__c=:objPotentialRisk.Id];
        

    }
    public void saveRecord() {
        insert objPotentialRisk;
        objBusinessImpact.Potential_Risk_ID__c = objPotentialRisk.Id;
        description = objBusinessImpact.Description__c;
        severity = objBusinessImpact.Severity__c;
        insert objBusinessImpact;
        /*for(Business_Impact__c c: businessImpactList){
                c.Potential_Risk_ID__c = objPotentialRisk.Id;
                c.Description__c = objBusinessImpact.Description__c;
                //description = objBusinessImpact.Description__c;
                insert businessImpactList;
        }*/
        
    }

    

}