objects/Call_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Plan__c</fullName>
        <label>Opportunity Plan</label>
        <referenceTo>Opportunity_Plan__c</referenceTo>
        <relationshipLabel>Call Plans</relationshipLabel>
        <relationshipName>Call_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Call Plan</label>
    <nameField>
        <label>Call Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Plans</relationshipLabel>
        <relationshipName>Opportunity_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Plan</label>
    <nameField>
        <displayFormat>OP-{00000000}</displayFormat>
        <label>Opportunity Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/customRelatedCallPlansTest.cls
/************************************************************************
Purpose     : Test Class for customRelatedCallPlans
Parameters  : None
Returns     : None
***********************************************************************/
@isTest(SeeAllData=true) 
public class customRelatedCallPlansTest
    {  
        static testmethod void testcustomRelatedCallPlans(){ 
        Account acc=new Account(Name='test',Source_System_Account_ID__c='0987',ShippingCountry='India'); 
        insert acc;
        Opportunity opp = new Opportunity(AccountId = acc.id, StageName = '01 - Understand Customer', Name = 'abc', CloseDate = system.today(),CurrencyIsoCode='USD');
        insert opp;
        Opportunity_Plan__c opplan=new Opportunity_Plan__c(Opportunity__c=opp.id);
        insert opplan;
        
        system.currentPageReference().getParameters().put('retURL','/apex/');
        system.currentPageReference().getParameters().put('id',opplan.Id);
        ApexPages.StandardController controller= new ApexPages.StandardController(new Call_Plan__c());
        customRelatedCallPlans callplan=new customRelatedCallPlans(controller);        
        callplan.getrelatedCallPlans();
        callplan.cancel();
        
        }
     }