objects/Case.object
<CustomObject>
    <fields>
        <fullName>BG__c</fullName>
        <label>BG</label>
        <picklist>
            <picklistValues>
                <fullName>Cross-BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESSN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Åland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country_of_Submitter__c</fullName>
        <label>Country of Submitter</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Åland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Account_Name__c</fullName>
        <inlineHelpText>This field is required if you want to create a new account</inlineHelpText>
        <label>New Account Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <description>Type of Case being submitted</description>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Business Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GI Consolidated Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN Upfront</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Business Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS Contact Center</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account_Request</fullName>
        <active>true</active>
        <businessProcess>Account Creation</businessProcess>
        <description>For new customer creation or customer data update (Account name, address, attributes, etc…)</description>
        <label>Account Request</label>
    </recordTypes>
</CustomObject>

objects/World_Region__c.object
<CustomObject>
    <description>For testing World Region</description>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IF( NOT( ISBLANK( Country_Name__c ) ), BLANKVALUE( ParentId__r.ParentId__r.ParentId__r.ParentName__c , BLANKVALUE( ParentId__r.ParentId__r.ParentName__c , BLANKVALUE(  ParentId__r.ParentName__c , BLANKVALUE(  ParentName__c , &apos;&apos; )))), Country_Name__c )</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>World Region</label>
    <nameField>
        <label>World Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>World Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MDCPUnverifiedAccountController.cls
/**********************************************************
* Class Name: MDCPUnverifiedAccountController
* Author: Vijay Ranjan
* Date: 28-July-2013 
* Description: Controller class to Create Unverified Accounts in SFDC
*
***********************************************************/
public class MDCPUnverifiedAccountController{
public String Name{get;set;}
public String PhysicalStreet{get;set;}
public String PhysicalState {get;set;}
public String PhysicalCity{get;set;}
public String PostalCode{get;set;}
public List<SelectOption> PhysicalCountrylist {get;set;}
public String selectedCountry {get;set;}
public Boolean IsNewAccountCreated{get;set;}
public Boolean getIsNewAccountCreated(){
return IsNewAccountCreated;
}
public String newUnverifiedAccountID{get;set;}
public String getnewUnverifiedAccountID(){
return newUnverifiedAccountID;
}
public String newCaseID{get;set;}
public String getnewCaseID(){
return newCaseID;
}
public Boolean isCaseCreated{get;set;}
public Boolean getisCaseCreated(){
return isCaseCreated;
}
public Boolean isCaseCreationFailed {get;set;}
public Boolean getisCaseCreationFailed(){
return isCaseCreationFailed ;
}
/**************Constructor for MDCPUnverifiedAccountController***********************/
public MDCPUnverifiedAccountController(){
loadCountrylist();
isCaseCreated=false;
}
public void save(){
    IsNewAccountCreated=false; 
    newUnverifiedAccountID=null;
    try{
        Account var=new Account();
        ID CustomerRecordTypeId=[SELECT Id FROM RecordType where name='Customer' limit 1].id;
        var.recordTypeID=CustomerRecordTypeId;
        var.OwnerId =[Select Id,Country,Region__c,Business_Group__c,Name from User where Alias=:Label.MDCPUnverifiedAccountOwner limit 1].id;
        var.Name=Name; 
        var.ShippingStreet=PhysicalStreet; 
        var.ShippingPostalCode=PostalCode; 
        var.ShippingCity=PhysicalCity; 
        var.ShippingState=PhysicalState ; 
        var.ShippingCountry=selectedCountry ; 
        var.MDCP_Subscribed_Flag__c='false'; 
        insert var;     
               if(var.id != null){
                    IsNewAccountCreated=true;
                    newUnverifiedAccountID=var.id;
                }
        system.debug('Inserted accout ID============'+var.id);            
    }catch(Exception e){system.debug('Exception occured in Account Creation:::::: '+e.getmessage());}
  if(IsNewAccountCreated){
    createNewCase();
  }  
}
public pagereference back(){
    PageReference pageRef = new PageReference('/apex/MDCPDynamicSearchPage?entity=Customer');
    pageRef.setRedirect(true);
return pageRef;
}
public void loadCountrylist(){

    List<World_Region__c>Countrylist=[SELECT Country_Name__c from World_Region__c where Country_Name__c !=null OR Country_Name__c!= ''];
    Countrylist.sort();
    PhysicalCountrylist = new List<SelectOption>();   
     PhysicalCountrylist.add(new SelectOption('--None-- ','--None-- ')); 
    for(World_Region__c val:Countrylist){
     PhysicalCountrylist.add(new SelectOption(val.Country_Name__c,val.Country_Name__c));
    }
}
       
/********@Method to Create New Case if Account does not exist in SFDC******/
public void createNewCase() { 
isCaseCreated =false; 
Map<String,Schema.RecordTypeInfo> rtMapByName;
Id caseRecordordTypeId;
String caseId;
  case  caseRecord=new case();
    User usr = [Select Id,Country,Region__c,Business_Group__c,Name from User where Id =: UserInfo.getUserId()];
    rtMapByName = Case.SObjectType.getDescribe().getRecordTypeInfosByName();
    caseRecordordTypeId = rtMapByName.get(Label.Account_Request).getRecordTypeId();
    caseRecord.RecordTypeId = caseRecordordTypeId;
    caseRecord.AccountId= newUnverifiedAccountID;    
    caseRecord.Origin = 'SFDC';
    caseRecord.IsSelfServiceClosed = False ;
    caseRecord.IsEscalated = False;
    caseRecord.Priority = 'Medium';
    caseRecord.Region__c =usr.Region__c ;    
    caseRecord.Status = 'New';
    caseRecord.BG__c=usr.Business_Group__c;
    caseRecord.Request_Type__c = 'Single Record';
    caseRecord.New_Account_Name__c = Name;
    caseRecord.Country_of_Submitter__c = usr.Country;
    caseRecord.City__c = PhysicalCity;
    caseRecord.Country__c =selectedCountry  ;
    caseRecord.Street__c = PhysicalStreet;
    caseRecord.State_Province__c = PhysicalState ;
    caseRecord.Zip_Postal_Code__c = PostalCode;
    caseRecord.IsVisibleInSelfService = False;
    caseRecord.Country_of_Submitter__c =usr.Country ;
    //checking to create for competitor or customer
    caseRecord.OwnerId = Label.Master_Data_Back_Office_SFDC;
    caseRecord.Reason = 'Customer - Create a new account';
    caseRecord.Subject = 'account.Created By '+usr.name+ ' New Unverified account submission request';
    caseRecord.Description = 'This Record has been created in SFDC manually via Unverified Account Creation Process by  '+usr.name ;
    caseRecord.Scenario__c = 'UVA created & MDCP Org ID not found';

     try{
        insert caseRecord;
        isCaseCreated = True;
        newCaseID= [Select Id,CaseNumber from Case where id =:caseRecord.Id].CaseNumber;        
        }catch (Exception e) { isCaseCreationFailed = True;
        }
   
}
/**********************@method to hide case created link*********************************/
public void hidecaselink() {
    isCaseCreated =false;
}
/**********************@method to hide Account created link*********************************/
public void hideAccountlink() {
    IsNewAccountCreated=false;
}   
}