objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assign_to_Team__c</fullName>
        <inlineHelpText>This field will drive dynamic assignment in combination with other criteria.</inlineHelpText>
        <label>Assign to Team</label>
        <picklist>
            <picklistValues>
                <fullName>CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai NBQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO Bucharest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO Bucharest Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO Bucharest PWB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBS CEM Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICOEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multinational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multinational Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Stop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PWB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Review E2E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Review E2E Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Review Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW Back Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW ESP BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW ESP CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW PWB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW PWB BUCHAREST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW Simple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS Contact Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS Contact Center BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS Contact Center FO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS PWB Orders AMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US NBQ Channel</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BG__c</fullName>
        <label>BG</label>
        <picklist>
            <picklistValues>
                <fullName>Cross-BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESSN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Requestor_Email__c</fullName>
        <description>Email address of case submitter</description>
        <label>Case Requestor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Case_Requestor__c</fullName>
        <description>Name of person requesting case</description>
        <label>Case Requestor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Åland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <picklist>
            <picklistValues>
                <fullName>CAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multinational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Stop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PWB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW PWB</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <description>Type of Case being submitted</description>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Business Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GI Consolidated Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN Upfront</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Business Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS Contact Center</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <formula>CreatedBy.FirstName&amp;&quot; &quot;&amp;CreatedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Submitter</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/CaseExternalSystemMapper__c.object
<CustomObject>
    <description>Case External System Mapper</description>
    <fields>
        <fullName>Assign_To_Team__c</fullName>
        <label>Assign To Team</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BG__c</fullName>
        <label>BG</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <description>Classification</description>
        <inlineHelpText>Classification</inlineHelpText>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Sub-Case Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Type - Subcase Type mapper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program_Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLA / Case Weight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Reason - Scenario Mapper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OAE_Exceptions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO EmailToCase</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExternalValue__c</fullName>
        <description>ExternalValue</description>
        <inlineHelpText>ExternalValue</inlineHelpText>
        <label>Source System Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Case Origin</description>
        <inlineHelpText>Case Origin</inlineHelpText>
        <label>Case Origin</label>
        <picklist>
            <picklistValues>
                <fullName>CSIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PWB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request_Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SystemValue__c</fullName>
        <description>SFDC Value</description>
        <inlineHelpText>SFDC Value</inlineHelpText>
        <label>SFDC Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CaseExternalSystemMapper</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>RecordID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CaseExternalSystemMappers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EmailServiceToCreateCase.cls
global class EmailServiceToCreateCase implements Messaging.InboundEmailHandler {
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email,
        Messaging.InboundEnvelope envelope){
            Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
            
            // mapping case fields with incoming email 
            Case cocase = new Case();
            cocase.subject = email.subject;
            cocase.description = email.plainTextBody;
            cocase.Status  = 'New';
            //cocase.Submitter__c = email.fromname.substring(0,email.fromname.indexOf(' ')) + email.fromname.substring(email.fromname.indexOf(' ')) ;
            cocase.Case_Requestor__c = email.fromname.substring(0,email.fromname.indexOf(' ')) + email.fromname.substring(email.fromname.indexOf(' ')) ;
            cocase.Case_Requestor_Email__c = envelope.fromAddress;
            CaseExternalSystemMapper__c cm = [Select Id,Assign_to_Team__c, Classification__c, ExternalValue__c, Origin__c, Request_Type__c, SystemValue__c, BG__c, Country__c, Program_Type__c, Route_to_Market__c, Region__c, Time_zone__c, Work_Location__c FROM CaseExternalSystemMapper__c where ExternalValue__c = :envelope.toAddress]; 
            
            Map<String, Schema.SObjectType> m = Schema.getGlobalDescribe() ;
            Schema.SObjectType s = m.get('Case') ;
            Schema.DescribeSObjectResult cfrSchema = s.getDescribe() ;
            Map<String,Schema.RecordTypeInfo> RecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
            id rcdType= RecordTypeInfo.get(cm.SystemValue__c).getRecordTypeId();
            if(cm != Null){
                //setting case fields with case external system mapper field values 
                cocase.Origin = cm.Origin__c;
                cocase.Assign_to_Team__c = cm.Assign_To_Team__c;
                cocase.bg__c = cm.bg__c;
                cocase.Work_Location__c = cm.Work_Location__c;
                cocase.Route_to_Market__c = 'Direct';
                cocase.Requestor_s_TimeZone__c = cm.Time_zone__c;
                cocase.Country__c = cm.Country__c;
                cocase.Region__c = cm.Region__c;
                cocase.Work_Location__c = cm.Work_Location__c;
                cocase.RecordTypeId = rcdType;
                cocase.Request_Type__c = cm.Request_Type__c; 
                cocase.Business_Type__c = 'Standard';
                insert cocase;
            }
            
            //Attaching email to email related list on case object
            EmailMessage msg = new EmailMessage();
            msg.incoming = True;    
            msg.ParentId = cocase.Id;
            msg.Subject = email.subject;
            msg.TextBody = email.plainTextBody;
            msg.HtmlBody = email.htmlBody;
            msg.MessageDate = System.now();
            msg.FromAddress = email.fromAddress;
            msg.FromName = email.fromName;
        //if there are multiple To email address then separate by ;
            String str = '';
            if (email.toAddresses != null && email.toAddresses.size() > 0){
                for (integer i = 0 ; i < email.toAddresses.size() ; i++) {
                    if (i != 0) str = str + ';';  
                    str = str + email.toAddresses[i];
                }
                msg.ToAddress = str;
            }
        if (email.ccAddresses != null && email.ccAddresses.size() > 0){
            str = '';
            for (integer i = 0 ; i < email.ccAddresses.size() ; i++) {
                if (i != 0) str = str + ';';  
                str = str + email.ccAddresses[i];
            }
            msg.CcAddress = str;
        }
        insert msg;
        
        // Attaching email attachments to case object      
        if (email.binaryAttachments != null && email.binaryAttachments.size() > 0) {
            for (integer i = 0 ; i < email.binaryAttachments.size() ; i++) {
                Attachment attachment = new Attachment();
        //      attach to the newly created case record
                attachment.ParentId = cocase.Id;
                    if(email.binaryAttachments[i].mimeTypeSubType == 'message/rfc822'){
                    //if(email.binaryAttachments[i].filename.endsWith('.msg'))
                        String newfilename = 'OUTLOOK MESSAGE FILE :' + email.binaryAttachments[i].filename + '.eml';
                        attachment.Name = newfilename;
                    }
                    else
                        attachment.Name = email.binaryAttachments[i].filename;
                        attachment.Body = email.binaryAttachments[i].body;
               insert attachment;
            }
        }
        if (email.textAttachments != null && email.textAttachments.size() > 0) {
            for (integer i = 0 ; i < email.textAttachments.size() ; i++) {  
            Attachment attachment1 = new Attachment();
        //  attach to the newly created contact record
            attachment1.ParentId = cocase.Id;
            attachment1.Name = email.textAttachments[i].filename;      
            attachment1.Body = blob.valueOf(email.textAttachments[i].body);
       //   attachment1.mimeTypeSubType = 'application/vnd.ms-outlook';
            insert attachment1;
            }
        }
        return result;
    }
}