objects/Channel_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>Location__r.Location_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>&quot;Lookup to a Location object&apos;s record.
This field is a lookup to an existing Location child record when a parent Business Relationship record is selected in the existing &quot;&quot;Partner&quot;&quot; field.This is in support to attaching an Opportunity to a Partner Site.&quot;</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Alliance and Channel Partners</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Partner_Account_Role__c</fullName>
        <label>Partner Account Role</label>
        <picklist>
            <picklistValues>
                <fullName>Implementer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outsourcer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <picklist>
            <picklistValues>
                <fullName>Alliance Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Alliance and Channel Partners</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Partner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance and Channel Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDCP_Organization_ID__c</fullName>
        <formula>Account__r.MDCP_Organization_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MDCP Organization ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Portal_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Portal Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Userkey__c</fullName>
        <description>Location record unique key.</description>
        <externalId>true</externalId>
        <label>Userkey</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Location_Partner_Users__c.object
<CustomObject>
    <description>This object supports the logical assignment of a partner user to one or more Location entries in the Location object.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Reference to a Contact object&apos;s record. This custom objects implements an intersection between Contacts and Location records.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Location Partner Users</relationshipLabel>
        <relationshipName>Partner_User_Location_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Reference to a Location object&apos;s record. This custom objects implements an intersection between Contacts and Location records.</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Location Partner Users</relationshipLabel>
        <relationshipName>Partner_User_Location_Mappings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Userkey__c</fullName>
        <description>Partner User Location Assignment unique key.</description>
        <externalId>true</externalId>
        <label>Userkey</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Location Partner Users</label>
    <nameField>
        <displayFormat>PULA-{0}</displayFormat>
        <label>Location Partner Users</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Partner Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Access__c</fullName>
        <label>Case Access</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GroupID__c</fullName>
        <externalId>true</externalId>
        <label>GroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define a Territory as Active/ Inactive</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean indicating whether Territory is exposed to Partner Accounts only</description>
        <label>IsPartner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MyComp_Sales_Territory_Name__c</fullName>
        <description>Created in R6</description>
        <label>Sales Territory Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isExternal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isExternal</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Location_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>Location__r.Location_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Locator Id</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Location Assignment</label>
    <nameField>
        <label>STLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Location Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_User_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Record with ISActive checked signifies User&apos;s present in Group.</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Territory Short Name</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory User Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_User_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Territory_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory User Assignment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Sales Territory User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory User Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PCLM_OppOwnerChngTerrUpdateControlTest.cls
@isTest(seeAllData=true)
private class PCLM_OppOwnerChngTerrUpdateControlTest{
    static testMethod void OppOwnerChngTerritoryUpdate_controllerTest(){ 
    
    user testUser = new User(Profileid=userInfo.getProfileId(),Username='OpptyOwner123@gmail.com',
                                 LastName='OpOw',email='OpptyOwner124test12@hp.com' ,Alias='OptyO', 
                                 CommunityNickname='testO',emailencodingkey='UTF-8', 
                                 languagelocalekey='en_US', localesidkey='en_US',timezonesidkey='America/Los_Angeles',
                                 Partner_Collaboration_Participating_User__c=true, Email_Address__c='Opptygemail123@gmail.com',EmployeeNumber='',
                                 Legacy_Employee_Ref__c='09876599',Adoption_Role_Type__c='Account Executive');
    insert testUser;
    
    Id RecordTypeId= Schema.SObjectType.account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
    Account newAccount = new Account(Name='PrevLocTestAcc1',RecordTypeId=RecordTypeId,Partner_Portal_Eligible__c=true,MDCP_Business_Relationship__c='Reseller',MDCP_Business_Relationship_ID__c='111',MDCP_Organization_ID__c='111',Channel_Partner_Flag__c=true);
    insert newAccount;
    
    Contact contact1  = new Contact(FirstName = 'Test',Lastname = 'McTesty',AccountId = newAccount.Id,Email = System.now().millisecond() + 'test@test.com');
    insert contact1;
    
    Location__c loc1 = new Location__c(Name='1500',Location_Name__c='Blr',Account__c = newAccount.id);
    insert loc1;
    
    Location_Partner_Users__c lpu1 = new Location_Partner_Users__c(Contact__c = contact1.id,Location__c = loc1.id,Userkey__c =  'a2bc3');
    insert lpu1;
    
    UserLicense usr =[Select id from UserLicense where name='Gold Partner'];
    Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE '%Partner Sales Rep%' and UserLicenseId=:usr.Id ];
        
    User portalUser = new User(ProfileId = portalProfile.id,ContactId=contact1.Id,
                                    LastName = 'Test1', FirstName = 'Test1', Username = 'testing452567@test.com',
                                    Alias='test1',CommunityNickname='test12 Approve1', Email='testingoppty12323@hp.com',TimeZoneSidKey='America/Chicago',
                                    EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', LocaleSidKey='en_US',IsActive=True,Email_Address__c='test234y1@hp.com',
                                    Partner_Collaboration_Participating_User__c=true,EmployeeNumber='6534548661',
                                    Legacy_Employee_Ref__c='142587547',Adoption_Role_Type__c='Partner User');
    Insert portalUser;
    Sales_Territory__c salesTerritory = new Sales_Territory__c();
    Sales_Territory_User_Assignment__c salesTerrUser = new Sales_Territory_User_Assignment__c ();
    Sales_Territory_Location_Assignment__c salesTerrLoc = new  Sales_Territory_Location_Assignment__c();
    system.runAs(testUser){
             test.startTest();
                 portalUser.isPortalEnabled = true;
                 update portalUser;
             test.stopTest();
         }
    
        //Create a sales territory
        sales_territory__c st = new sales_territory__c();
        st.name = 'Test Sales territory';
        st.isPartner__c = true;
        st.isExternal__c = true;
        st.isActive__c = true;
        st.MyComp_Sales_Territory_Name__c ='St-Test';
        insert st;
        
        //Create a sales Territory User Assignment.
        Sales_Territory_User_Assignment__c salesUserAssign = new Sales_Territory_User_Assignment__c();
        salesUserAssign.User__c = testUser.id;
        salesUserAssign.sales_territory__c = st.id;
        insert salesUserAssign;
        
        //Create a sales territory Location assignment.
        Sales_Territory_Location_Assignment__c salesLocationAssign = new Sales_Territory_Location_Assignment__c();
        salesLocationAssign.Sales_Territory__c = st.id;
        salesLocationAssign.Location__c = loc1.id;
        insert salesLocationAssign;
        
        //Create a sales territory
        sales_territory__c st1 = new sales_territory__c();
        st1.name = 'Test Sales territory';
        st1.isPartner__c = true;
        st1.isExternal__c = true;
        st1.isActive__c = true;
        st1.MyComp_Sales_Territory_Name__c = 'St-Test1';
        insert st1;
        
        //Create a sales Territory User Assignment.
        Sales_Territory_User_Assignment__c salesUserAssign1 = new Sales_Territory_User_Assignment__c();
        salesUserAssign1.User__c = testUser.id;
        salesUserAssign1.sales_territory__c = st1.id;
        insert salesUserAssign1;
        
        //Create a sales territory Account assignment.
        Sales_Territory_Location_Assignment__c salesLocationAssign1 = new Sales_Territory_Location_Assignment__c();
        salesLocationAssign1.Sales_Territory__c = st1.id;
        salesLocationAssign1.Location__c = loc1.id;
        insert salesLocationAssign1;
        
        //Create a test account
        Account acc = TestingSetupDataUtil.createAccount('testAccount','accountEmail@test.com','Customer');
        insert acc;
        
        //Create Account share for the portal user
        AccountShare accShare = new accountShare();
        accShare.accountId = acc.Id;
        accShare.userOrGroupId = portalUser.id;
        //acc.rowCause = 'Manual Sharing';
        accShare.accountAccessLevel = 'Read';
        accShare.OpportunityAccessLevel = 'Edit';
        insert accShare;
        
        //Insert Opportunity.
             opportunity newOpp = new Opportunity();
        system.runAs(portalUser){
            
            newOpp.Name = 'OpportunityName';
            newOpp.CloseDate = system.today()+30;      
            newOpp.AccountId = acc.Id;
            newOpp.StageName = '01 - Understand Customer';
            newOpp.CurrencyIsoCode= 'USD';
            //newOpp.ownerId=portalUser.id;
            newOpp.Managed_By__c='Partner';
            insert newOpp;
        }
        
        system.runAs(testUser){
            newOpp.ownerId = testUser.id;
            update newOpp;
            opportunity newOpp1 = new opportunity();
            newOpp1.name= 'test Oppty1';
            newOpp1.Accountid= acc.id;
            date closeDate = system.today();
            newOpp1.closeDate = closeDate.addDays(30);
           // TestingSetupDataUtil.createOpportunity(newAcc.Id,'testOppty1', system.today()+ 30);
            newOpp1.stagename='01 - Understand Customer';
            newOpp1.ownerId=userInfo.getUserId();
            newOpp1.Managed_By__c='HP';
            insert newOpp1;
            
            Opportunity newOppty2=new Opportunity(Name='Test',Managed_By__c='Hp',closedate=Date.today()+30,AccountId=acc.Id,stagename='02 - Validate Opportunity',CurrencyIsoCode= 'USD',ownerId=portalUser.Id);
            Insert newOppty2;
            
            
            
             // Test Group
        Group grp = new Group(Name = ('' + 'sterr-10')); 
        insert grp ;

        // Creating GroupMember     
        //GroupMember grpMem=new GroupMember(GroupId=grp.id,UserOrGroupId=portalUser.Id);     
        //insert grpMem;

        // Test salesTerritory insertion    
        salesTerritory.Name='TestSalesTerritory';
        salesTerritory.Account_Access__c='Edit';
        salesTerritory.Opportunity_Access__c='Read';
        salesTerritory.Case_Access__c='Read';
        salesTerritory.isExternal__c=true;
        salesTerritory.isActive__c= true;
        salesTerritory.IsPartner__c= true;
        salesTerritory.GroupID__c=grp.Id; 
        salesTerritory.MyComp_Sales_Territory_Name__c = 'ST-Sterr';
        insert salesTerritory;

        //Test oppty share insert
        OpportunityShare newShareRec = new OpportunityShare(OpportunityAccessLevel = 'Read');
        newShareRec.OpportunityId = newOppty2.Id;
        newShareRec.UserOrGroupId = grp.Id;
        insert newShareRec;    

        //Sales Territory Location Assignment    
        salesTerrLoc.Location__c=loc1.Id;
        salesTerrLoc.CurrencyIsoCode='USD';
        salesTerrLoc.Sales_Territory__c=salesTerritory.Id;
        insert salesTerrLoc;

        //Sales Territory User Assignment
        salesTerrUser.Sales_Territory__c=salesTerritory.Id;
        salesTerrUser.User__c=portalUser.Id;
        insert salesTerrUser;
        
        map<id, opportunity> passOppty = new map<id, opportunity>();
        //passOppty.put(newOpp1.id, newOpp1);
        passOppty.put(newOppty2.id,newOppty2);
        list<user> passUser = new list<user>();
        passUser.add(portalUser);
            
        PCLM_OppOwnerChngTerrUpdateController.removeOpptyShareToPartnersForLocation(passOppty,passUser);
            
            
            
            channel_partner__c ACP = new Channel_partner__c();
            ACP.Opportunity__c= newOpp1.id;
            ACP.Channel_Partner__c = newAccount.id;
            ACP.Partner_Account_Role__c='Distributor';
            ACP.Partner_Type__c = 'Channel Partner';
            insert ACP;
            
            newOpp1.ownerId = portalUser.id;
            update newOpp1;
            
            newOpp1.ownerId = testuser.Id;
            update newOpp1;
          }
        
        
    }
}