objects/Channel_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>Location__r.Location_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>&quot;Lookup to a Location object&apos;s record.
This field is a lookup to an existing Location child record when a parent Business Relationship record is selected in the existing &quot;&quot;Partner&quot;&quot; field.This is in support to attaching an Opportunity to a Partner Site.&quot;</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Alliance and Channel Partners</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Partner_Account_Role__c</fullName>
        <label>Partner Account Role</label>
        <picklist>
            <picklistValues>
                <fullName>Implementer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outsourcer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <picklist>
            <picklistValues>
                <fullName>Alliance Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Alliance and Channel Partners</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Partner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance and Channel Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDCP_Organization_ID__c</fullName>
        <formula>Account__r.MDCP_Organization_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MDCP Organization ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Portal_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Portal Eligible</label>
        <type>Checkbox</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Access__c</fullName>
        <label>Case Access</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GroupID__c</fullName>
        <externalId>true</externalId>
        <label>GroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define a Territory as Active/ Inactive</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean indicating whether Territory is exposed to Partner Accounts only</description>
        <label>IsPartner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MyComp_Sales_Territory_Name__c</fullName>
        <description>Created in R6</description>
        <label>Sales Territory Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isExternal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isExternal</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Location_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>Location__r.Location_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Locator Id</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Location Assignment</label>
    <nameField>
        <label>STLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Location Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_User_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Record with ISActive checked signifies User&apos;s present in Group.</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Territory Short Name</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory User Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_User_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Territory_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory User Assignment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Sales Territory User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory User Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PCLM_OpptySalesTeamUtilTest.cls
/**********************************************************
* Class Name: PCLM_OpptySalesTeamUtilTest
* Author: HP
* Date: 10-Jan-2013
* Description: This class does the test coverage for PCLM_OpptySalesTeamUtil class.
***********************************************************/
@isTest(SeeAllData=true)
Private Class PCLM_OpptySalesTeamUtilTest{  
    static testMethod void testOpptySalesTeamUtil(){
        OpportunityTeamMember oppTeamMember=new OpportunityTeamMember();
        List<OpportunityTeamMember> oppTeamMember1=new List<OpportunityTeamMember>();
        Sales_Territory__c salesTerritory = new Sales_Territory__c();
        Sales_Territory_User_Assignment__c salesTerrUser = new Sales_Territory_User_Assignment__c ();
        Sales_Territory_Location_Assignment__c salesTerrLoc = new  Sales_Territory_Location_Assignment__c();
        
        Id RecordTypeId= Schema.SObjectType.account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
        Account newAccount = new Account(Name='PrevLocTestAcc1',RecordTypeId=RecordTypeId,Partner_Portal_Eligible__c=true,MDCP_Business_Relationship__c='Reseller',MDCP_Business_Relationship_ID__c='111',MDCP_Organization_ID__c='111',Channel_Partner_Flag__c=true);
        insert newAccount;
    
        Contact contact1  = new Contact(FirstName = 'Test',Lastname = 'McTesty',AccountId = newAccount.Id,Email = System.now().millisecond() + 'test@test.com');
        insert contact1;
    
        Location__c loc1 = new Location__c(Name='1500',Location_Name__c='Blr',Account__c = newAccount.id);
        insert loc1;
    

        //Partner User Insertion
        UserLicense usr =[Select id from UserLicense where name='Gold Partner'];
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE '%Partner Sales Rep%' and UserLicenseId=:usr.Id ];
    User portalUser = new User(ProfileId = portalProfile.id,ContactId=contact1.Id,LastName = 'Test1', FirstName = 'Test1', Username = 'testing45672@hp.com', Alias='test1', CommunityNickname='test Approve123', Email='test123@hp.com',TimeZoneSidKey='America/Chicago',EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', LocaleSidKey='en_US',IsActive=True,Email_Address__c='test123@hp.com',EmployeeNumber='65348771',Legacy_Employee_Ref__c='1487888',Location_Record_Id__c = loc1.id,Adoption_Role_Type__c='Partner User');
        Insert portalUser ;
        
        Map<String, Schema.SObjectType> m  = Schema.getGlobalDescribe() ;
        Schema.SObjectType s = m.get('Account') ;
        Schema.DescribeSObjectResult cfrSchema = s.getDescribe() ;
        Map<String,Schema.RecordTypeInfo> RecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
        Id recrdId= RecordTypeInfo.get('Customer').getRecordTypeId();
        Account newAcc=new Account(Name='Test Account11',RecordTypeId= recrdId,ShippingCountry='India');
        Insert newAcc;

        //Test Opportunity Insertion
        Opportunity newOppty=new Opportunity(Name='Test',Managed_By__c='Hp',closedate=Date.today(),AccountId=newAcc.Id,stagename='02 - Validate Opportunity',CurrencyIsoCode= 'USD');
        Insert newOppty;

        //Channel Partner insertion
        Channel_Partner__c newalliance=new Channel_Partner__c(Channel_Partner__c=newAccount.Id,Partner_Type__c='Alliance Partner',Partner_Account_Role__c='Implementer',Opportunity__c=newOppty.Id,Location__c = loc1.id);
        Insert newalliance;

        //Test Opportunity Team Member insertion 
        oppTeamMember.OpportunityId=newOppty.Id;
        oppTeamMember.TeamMemberRole='Inside Sales';
        oppTeamMember.UserId=portalUser.Id;
        insert oppTeamMember;
        oppTeamMember1.add(oppTeamMember);

 
        // Test Group
        Group grp = new Group(Name = ('' + 'sterr-10')); 
        insert grp ;

        // Creating GroupMember     
        //GroupMember grpMem=new GroupMember(GroupId=grp.id,UserOrGroupId=portalUser.Id);     
        //insert grpMem;

        // Test salesTerritory insertion    
        salesTerritory.Name='TestSalesTerritory';
        salesTerritory.Account_Access__c='Edit';
        salesTerritory.Opportunity_Access__c='Read';
        salesTerritory.Case_Access__c='Read';
        salesTerritory.isExternal__c=true;
        salesTerritory.isActive__c= true;
        salesTerritory.IsPartner__c= true;
        salesTerritory.GroupID__c=grp.Id; 
        salesTerritory.MyComp_Sales_Territory_Name__c = 'ST-TestSterr';
        insert salesTerritory;

        //Test oppty share insert
        OpportunityShare newShareRec = new OpportunityShare(OpportunityAccessLevel = 'Read');
        newShareRec.OpportunityId = newOppty.Id;
        newShareRec.UserOrGroupId = grp.Id;
        insert newShareRec;    

        //Sales Territory Account Assignment    
        salesTerrLoc.Location__c=loc1.Id;
        salesTerrLoc.CurrencyIsoCode='USD';
        salesTerrLoc.Sales_Territory__c=salesTerritory.Id;
        insert salesTerrLoc;

        //Sales Territory User Assignment
        salesTerrUser.Sales_Territory__c=salesTerritory.Id;
        salesTerrUser.User__c=portalUser.Id;
        insert salesTerrUser;

        //delete optty member
        //delete oppTeamMember;
        
        test.starttest();
        
        PCLM_OpptySalesTeamUtil.optySharesForSTMembersViaLocation(oppTeamMember1);
        PCLM_OpptySalesTeamUtil.shareOpptyWithSalesTerritoryUsersForLocation(oppTeamMember1);
        PCLM_OpptySalesTeamUtil.removeOpptyShareFromSalesTerritoryUsersForLocation(oppTeamMember1);
        test.stoptest();
    }  
}