objects/Channel_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>&quot;Lookup to a Location object&apos;s record.
This field is a lookup to an existing Location child record when a parent Business Relationship record is selected in the existing &quot;&quot;Partner&quot;&quot; field.This is in support to attaching an Opportunity to a Partner Site.&quot;</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Alliance and Channel Partners</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Alliance and Channel Partners</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Partner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance and Channel Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Location_Partner_Users__c.object
<CustomObject>
    <description>This object supports the logical assignment of a partner user to one or more Location entries in the Location object.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Reference to a Contact object&apos;s record. This custom objects implements an intersection between Contacts and Location records.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Location Partner Users</relationshipLabel>
        <relationshipName>Partner_User_Location_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Reference to a Location object&apos;s record. This custom objects implements an intersection between Contacts and Location records.</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Location Partner Users</relationshipLabel>
        <relationshipName>Partner_User_Location_Mappings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Location Partner Users</label>
    <nameField>
        <displayFormat>PULA-{0}</displayFormat>
        <label>Location Partner Users</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Partner Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupID__c</fullName>
        <externalId>true</externalId>
        <label>GroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define a Territory as Active/ Inactive</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean indicating whether Territory is exposed to Partner Accounts only</description>
        <label>IsPartner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isExternal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isExternal</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Account_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Territory Account Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Account_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory Short Name</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Account Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Account_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Account Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Sales Territory Account Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Account Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Location_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Locator Id</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Location Assignment</label>
    <nameField>
        <label>STLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Location Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PCLM_OppOwnerChngTerrUpdateController.cls
/**
* Class Name: PCLM_OppOwnerChngTerrUpdateController
* Author: HP
* Date: 08-JAN-2013 
* Requirement # Request Id: 4043 
* Description: Contains support action methods for trigger on Opportunity object for sharing opportunity to sales
               territory.
*/

public class PCLM_OppOwnerChngTerrUpdateController{
    
    /**
    * @description: Static list of Public group Ids 
    */
    public static List<Id> groupIdList = new List<Id>();
    
    
    /**
    * @description: Adds records in OpportunityShare for every opportunity and associated list of public groups.
    * @params: trigger.newMap;
    * @returns: void
    */
    /*public static void addOpptyShareToPartners(Map<Id,Opportunity> newOpptyMap, list<user> userOpptyOwner){
    
        Map<Id,List<String>> opptyWithTerritoryGroupMap = new Map<Id,List<String>>();
        List<OpportunityShare> opptySharingList = new List<OpportunityShare>();
        
        opptyWithTerritoryGroupMap = OpptyShareForPartners(newOpptyMap, userOpptyOwner);
        
        if(opptyWithTerritoryGroupMap == null){
            return;
        }
        
        for(Id opptyId : opptyWithTerritoryGroupMap.keySet()){
            for(Id groupId : opptyWithTerritoryGroupMap.get(opptyId)){
                OpportunityShare newShareRec = new OpportunityShare(OpportunityAccessLevel = 'Read');
                newShareRec.OpportunityId = opptyId;
                newShareRec.UserOrGroupId = groupId;
                opptySharingList.add(newShareRec);
            }
        }       
        
        if(opptySharingList != null && opptySharingList.size() > 0 ){
            Database.SaveResult[] newShareResults;
            try{
                newShareResults = database.insert(opptySharingList,false);  
            }catch (Exception e){
                CreateApexErrorLog.insertHandledExceptions(e, newShareResults, 'Opportunity__c', 'PCLM_OppOwnerChngTerrUpdateController', 'Class');
            }
        }
    }*/
    
    //TM:Vinay R5:Req:6201:Start
     /**
    * @description: Adds records in OpportunityShare for every opportunity and associated list of public groups.
    * @params: trigger.newMap,list of portal users;
    * @returns: void
    */
    public static void addOpptyShareToPartnersForLocation(Map<Id,Opportunity>  processOptyMap,
                                                                List<User> optyPortalOwnerList){
        Map<Id,List<String>> opptyWithTerritoryGroupMap = new Map<Id,List<String>>();
        List<OpportunityShare> opptyShareList = new List<OpportunityShare>();
        
        opptyWithTerritoryGroupMap = OpptyShareForPartnersViaLocation(processOptyMap,optyPortalOwnerList);
        
        if(opptyWithTerritoryGroupMap == null || opptyWithTerritoryGroupMap.isEmpty()){
            return;
        }
        
        //TM:Vinay R6:Req 7525:Start
        Set<Channel_Partner__c> pvtOpptySet = new Set<Channel_Partner__c>();
        for(Channel_Partner__c pvtOppty:[Select Opportunity__c From Channel_Partner__c Where
         Opportunity__c In:opptyWithTerritoryGroupMap.keySet() And (Opportunity__r.Account.Confidential_Account__c = true
          Or Opportunity__r.Confidential__c = true)]){
            pvtOpptySet.add(pvtOppty);
        }
        
        if(pvtOpptySet != null && pvtOpptySet.size() > 0){
            for(Channel_Partner__c pvtOppty:pvtOpptySet){
                if(opptyWithTerritoryGroupMap.containsKey(pvtOppty.Opportunity__c)){
                    opptyWithTerritoryGroupMap.remove(pvtOppty.Opportunity__c);
                }
            }
        }
        if(opptyWithTerritoryGroupMap == null || opptyWithTerritoryGroupMap.isEmpty()){ 
            return;
        }
        //TM:Vinay R6:Req 7525:End
        
        for(Id optyId: opptyWithTerritoryGroupMap.keySet()){
            for(String grpId: opptyWithTerritoryGroupMap.get(optyId)){
                OpportunityShare newOptyShareRec = new OpportunityShare(OpportunityAccessLevel = 'Read');
                newOptyShareRec.OpportunityId = optyId;
                newOptyShareRec.UserOrGroupId = grpId;
                opptyShareList.add(newOptyShareRec);
            }
        }
        if(opptyShareList != null && opptyShareList.size() > 0){
            Database.SaveResult[] newShareResults;
            try{
                newShareResults = database.insert(opptyShareList,false);
            }catch(Exception e){
                CreateApexErrorLog.insertHandledExceptions(e, newShareResults, 'Opportunity__c', 'OpptyACPUtil', 'Class');
            }
        }
    }
    //TM:Vinay R5:Req:6201:End
    
    /**
    * @description: Deletes records from OpportnityShare when Owner is changed from Partner User to Non-partner User.
    * @params: trigger.newMap,trigger.oldMap;
    * @returns: void
    */
    /*public static void removeOpptyShareToPartners(Map<Id,Opportunity> oldMap, list<user> userOpptyownerlist){
        Map<Id,List<String>> opptyWithTerritoryGroupMap = new Map<Id,List<String>>(); 
        List<OpportunityShare> currentOpptySharingList = new List<OpportunityShare>(); 
        List<OpportunityShare> deleteOpptySharingList = new List<OpportunityShare>(); 
        Set<Id> opptyIdSet = new Set<Id>();
        
        opptyWithTerritoryGroupMap = OpptyShareForPartners(oldMap, userOpptyownerlist);
        
        if(opptyWithTerritoryGroupMap == null){
            return;
        }
        
        opptyIdSet = opptyWithTerritoryGroupMap.keySet();
        
        currentOpptySharingList = [SELECT OpportunityId,UserOrGroupId FROM OpportunityShare WHERE opportunityId IN: opptyIdSet AND UserOrGroupId IN: groupIdList];
        
        for(OpportunityShare opptySharing : currentOpptySharingList){
            if(opptyWithTerritoryGroupMap.containsKey(opptySharing.OpportunityId)){
                for(Id groupId : opptyWithTerritoryGroupMap.get(opptySharing.OpportunityId)){
                    if(groupId == opptySharing.UserOrGroupId){
                        deleteOpptySharingList.add(opptySharing);
                        system.debug('the userGroupId is '+ opptySharing.userOrGroupId);
                    }
                }
            }
        }
        
         try{        
            if(deleteOpptySharingList != null && deleteOpptySharingList.size() > 0 ){
                Database.DeleteResult[] newShareResults = database.delete(deleteOpptySharingList,false);  
            }
        }catch(Exception e){
            CreateApexErrorLog.insertHandledExceptions(e, null, 'Opportunity__c', 'OpptyACPUtil', 'Class');
        }
        
    }*/
    /**
    * @description: Deletes records from OpportnityShare when Owner is changed from Partner User to Non-partner User.
    * @params: list<Users>,trigger.oldMap;
    * @returns: void
    */
    public static void removeOpptyShareToPartnersForLocation(Map<Id,Opportunity> oldMap,List<User> optyOwnerList){
        Map<Id,List<String>> opptyWithTerritoryGroupMap;
        List<OpportunityShare> currentOptySharingList;
        List<OpportunityShare> deleteOptySharingList = new List<OpportunityShare>();
        Set<Id> opptyIdSet = new Set<Id>();
        
        opptyWithTerritoryGroupMap = OpptyShareForPartnersViaLocation(oldMap, optyOwnerList);
        
        if(opptyWithTerritoryGroupMap == null){
            return;
        }
        
        opptyIdSet = opptyWithTerritoryGroupMap.keySet();
        currentOptySharingList = new List<OpportunityShare>([Select OpportunityId,UserOrGroupId FROM OpportunityShare WHERE opportunityId IN:opptyIdSet]);
        
        for(OpportunityShare optyShare: currentOptySharingList){
            if(opptyWithTerritoryGroupMap.containsKey(optyShare.OpportunityId)){
                for(Id groupId: opptyWithTerritoryGroupMap.get(optyShare.OpportunityId)){
                    if(groupId == optyShare.UserOrGroupId){
                        deleteOptySharingList.add(optyShare);
                    }
                }
            }
        }
         try{        
            if(deleteOptySharingList != null && deleteOptySharingList.size() > 0 ){
                Database.DeleteResult[] newShareResults = database.delete(deleteOptySharingList,false);  
            }
        }catch(Exception e){
            CreateApexErrorLog.insertHandledExceptions(e, null, 'Opportunity__c', 'PCLM_OppOwnerChngTerrUpdateController', 'Class');
        }
        
    }

    /**
    * @description: Fetches related list of public groups for opportunities.
    * @params: Map<Id,Opportunity>;
    * @returns: map of opportunity with the corresponding list of public groups to which it should be shared.
    */    
    /*private static Map<Id,List<String>> OpptyShareForPartners(Map<Id,Opportunity> newOpptyMap, list<user> userOwnerOpptylist){

        Map<Id,Id>partnerAccWithOpptyMap = new Map<Id,Id>(); 
        Map<Id,Sales_Territory_Account_Assignment__c> accWithTerritoryMap; 
        Set<Id> territoryIdOfPartnerSet = new Set<Id>(); 
        Map<Id,Sales_Territory__c> partnerTerritoryMap; 
        Map<Id,List<Id>> opptyWithTerritoryMap = new Map<Id,List<Id>>(); 
        Map<Id,List<String>> opptyWithTerritoryGroupMap = new Map<id,List<String>>(); 
        Set<id> oppOwnerIdSet = new Set<id>();
        Map<id, id> ownerPartnerAccIdMap = new Map<id,id>();
        
        for(Opportunity oppt:newOpptyMap.values()){
            oppOwnerIdSet.add(oppt.ownerId);
        }
        
        for(user u : userOwnerOpptylist){
            ownerPartnerAccIdMap.put(u.id, u.partner_account_Id__c);
        }
        
        for(Opportunity oppty:newOpptyMap.values()){
            system.debug('check portal enabled' + 'id is '+ oppty.ownerId + '   ' + oppty.Owner.IsPortalEnabled);
            
                partnerAccWithOpptyMap.put(oppty.Id,ownerPartnerAccIdMap.get(oppty.ownerId));
                system.debug('inside this loop' + oppty.Owner.Partner_Account_Id__c + 'oppty ID'+oppty.ID);
            
        }
        
        List<Id> partnerAccIdMap = partnerAccWithOpptyMap.values();
        
        accWithTerritoryMap = new Map<Id,Sales_Territory_Account_Assignment__c>([SELECT Id,Account__c,Sales_Territory__c FROM Sales_Territory_Account_Assignment__c WHERE Account__c IN: partnerAccIdMap AND Sales_Territory__r.isPartner__c= true AND Sales_Territory__r.isExternal__c=true]);
        
        if(accWithTerritoryMap == null || accWithTerritoryMap.isEmpty()){
            return null;
        }
        
        for(Opportunity oppty : newOpptyMap.Values()){
            for(Sales_Territory_Account_Assignment__c accWithTerrRec : accWithTerritoryMap.values()){
                if((ownerPartnerAccIdMap.get(oppty.ownerId) == accWithTerrRec.Account__c) && (accWithTerrRec.Account__c != null) && String.ValueOf(accWithTerrRec.Account__c) != ''){
                    territoryIdOfPartnerSet.add(accWithTerrRec.Sales_Territory__c);
                }
                if(opptyWithTerritoryMap.containsKey(oppty.Id)){
                    List<Id> relatedTerrIds = opptyWithTerritoryMap.get(oppty.id);
                    relatedTerrIds.add(accWithTerrRec.Sales_Territory__c);
                    opptyWithTerritoryMap.put(oppty.Id, relatedTerrIds);
                }else{
                    opptyWithTerritoryMap.put(oppty.Id,new List<Id>{accWithTerrRec.Sales_Territory__c});
                }
            }
        }
        
        partnerTerritoryMap = new Map<Id,Sales_Territory__c>([SELECT Id,GroupId__c FROM Sales_Territory__c WHERE Id IN: territoryIdOfPartnerSet]);
        
        if(partnerTerritoryMap == null || partnerTerritoryMap.isEmpty()){
            return null;
        }
        
        for(Id opptyId: opptyWithTerritoryMap.KeySet()){
            List<String> relatedGrpIds = new List<String>();
            for(Id terrId: opptyWithTerritoryMap.get(opptyId)){
                if(partnerTerritoryMap.get(terrId).GroupID__c !=null && String.ValueOf(partnerTerritoryMap.get(terrId).GroupID__c) !=''){
                    relatedGrpIds.add(partnerTerritoryMap.get(terrId).GroupID__c);
                    groupIdList.add(partnerTerritoryMap.get(terrId).GroupID__c);
                }
            }
            opptyWithTerritoryGroupMap.put(opptyId,relatedGrpIds);
        }
        
        if(opptyWithTerritoryGroupMap == null && opptyWithTerritoryGroupMap.isEmpty()){
            return null;
        }else{
            return opptyWithTerritoryGroupMap;
        }
    }*/
    
    //TM:Vinay R5:Req:6201:Start
    /**
    * @description: Fetches related list of public groups for opportunities based on locations.
    * @params: Map<Id,Opportunity>,List<User>;
    * @returns: map of opportunity with the corresponding list of public groups to which it should be shared.
    */   
    public static Map<Id,List<String>> OpptyShareForPartnersViaLocation(Map<Id,Opportunity>  processOptyMap,
                                                                List<User> optyPortalOwnerList){
        Set<Id> optyOwnerContactIdSet = new Set<Id>();
        Map<Id,Id> userIdLocationMap = new Map<Id,Id>();
        Map<Id,Id> contactLocMap = new Map<Id,Id>();
        Map<Id,Id> optyLocIdMap = new Map<Id,Id>();
        List<Id> locationIdList = new List<Id>();
        Set<Id> territoryIdSet = new Set<Id>();
        Map<Id,List<Id>> opportunityTerritoryMap = new Map<Id,List<Id>>();
        Map<Id,List<String>> opportunityTerritoryPubGrpMap = new Map<Id,List<String>>();
        Map<Id,Sales_Territory__c> locationTerritoryMap;
        
        for(User u:optyPortalOwnerList){
            optyOwnerContactIdSet.add(u.contactId);
        }
        for(Location_Partner_Users__c lpUser: [Select location__c,contact__c from Location_Partner_Users__c where contact__c IN: optyOwnerContactIdSet]){
            contactLocMap.put(lpUser.contact__c,lpUser.Location__c);
        }
        for(User u: optyPortalOwnerList){
            userIdLocationMap.put(u.id,contactLocMap.get(u.contactId));
        }
        for(Opportunity opty: processOptyMap.values()){
            optyLocIdMap.put(opty.id,userIdLocationMap.get(opty.ownerId));
        }
        
        locationIdList = optyLocIdMap.values();
        
        Map<Id,Sales_Territory_Location_Assignment__c> locWithTerritoryMap = new Map<Id,Sales_Territory_Location_Assignment__c>([Select Id,Location__c,Sales_Territory__c From Sales_Territory_Location_Assignment__c Where Location__c IN: locationIdList AND Sales_Territory__r.isPartner__c = true AND Sales_Territory__r.isExternal__c = true AND Sales_Territory__r.isActive__c = true]);
        
        if(locWithTerritoryMap == null || locWithTerritoryMap.isEmpty()){
            return null;
        }
        
        for(Opportunity opty: processOptyMap.values()){
            for(Sales_Territory_Location_Assignment__c stla: locWithTerritoryMap.values()){
                if(userIdLocationMap.get(opty.ownerId) == stla.Location__c && stla.Location__c != null && String.valueOf(stla.Location__c) != ''){
                    territoryIdSet.add(stla.Sales_Territory__c);
                }
                if(opportunityTerritoryMap.containsKey(opty.id)){
                    List<Id> relatedTerrIdList = opportunityTerritoryMap.get(opty.id);
                    relatedTerrIdList.add(stla.Sales_Territory__c);
                    opportunityTerritoryMap.put(opty.id,relatedTerrIdList);
                }else{
                    opportunityTerritoryMap.put(opty.id,new List<Id>{stla.Sales_Territory__c});
                }
            }
        }
        
        locationTerritoryMap =new Map<Id,Sales_Territory__c>([Select Id,GroupId__c From Sales_Territory__c where id IN: territoryIdSet]);
        
        if(locationTerritoryMap == null || locationTerritoryMap.isEmpty()){
            return null;
        }
        
        for(Id optyId: opportunityTerritoryMap.keySet()){
            List<String> relatedGrpIdList = new List<String>();
            for(Id terrId: opportunityTerritoryMap.get(optyId)){
                if(locationTerritoryMap.get(terrId).GroupId__c != null && String.valueOf(locationTerritoryMap.get(terrId).GroupId__c)!=''){
                    relatedGrpIdList.add(locationTerritoryMap.get(terrId).GroupId__c);
                    groupIdList.add(locationTerritoryMap.get(terrId).GroupID__c);
                }
            }
            opportunityTerritoryPubGrpMap.put(optyId,relatedGrpIdList);
        }
        
        if(opportunityTerritoryPubGrpMap == null || opportunityTerritoryPubGrpMap.isEmpty()){
            return null;
        }else{
            return opportunityTerritoryPubGrpMap;
        }
        
    }
    //TM:Vinay R5:Req:6201:End
}