objects/Channel_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>&quot;Lookup to a Location object&apos;s record.
This field is a lookup to an existing Location child record when a parent Business Relationship record is selected in the existing &quot;&quot;Partner&quot;&quot; field.This is in support to attaching an Opportunity to a Partner Site.&quot;</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Alliance and Channel Partners</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Alliance and Channel Partners</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Partner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance and Channel Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupID__c</fullName>
        <externalId>true</externalId>
        <label>GroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define a Territory as Active/ Inactive</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean indicating whether Territory is exposed to Partner Accounts only</description>
        <label>IsPartner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isExternal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isExternal</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Location_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Locator Id</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Location Assignment</label>
    <nameField>
        <label>STLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Location Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TMLocationOpptyShare.cls
/*********************************************************************************
* Class Name: TMLocationOpptyShare 
* Author: HP
* Date: 29-JUL-2013 
* Requirement # Request Id: 10319
* Description: This is a class that performs sharing of Opptys to Locations.
***********************************************************************************/
public class TMLocationOpptyShare{

    public static void createOpptyShare(List<Channel_Partner__c>acpList){
        
        Map<Id,List<Id>> locOpptyMap = new Map<Id,List<Id>>();
        Map<Id,List<String>> locGrpMap = new Map<Id,List<String>>();
        List<OpportunityShare> opptyShareList = new List<OpportunityShare>();
        
        //Find related opportunities for every location
        for(Channel_Partner__c acp:acpList){
            if(!locOpptyMap.containsKey(acp.Location__c)){
                List<Id> relOpptyIdList = new List<Id>();
                relOpptyIdList.add(acp.Opportunity__c);
                locOpptyMap.put(acp.Location__c,relOpptyIdList);
            }else{
                locOpptyMap.get(acp.Location__c).add(acp.Opportunity__c);
            }
        }
        //Find corresponding Territory groups for every location
        for(Sales_Territory_Location_Assignment__c stla:[Select location__c,Sales_Territory__r.GroupID__c From Sales_Territory_Location_Assignment__c Where location__c In :locOpptyMap.keySet() AND Sales_Territory__r.IsPartner__c = true AND Sales_Territory__r.IsExternal__c = false AND Sales_Territory__r.IsActive__c = true]){
            if(!locGrpMap.containsKey(stla.location__c)){
                List<Id> relGrpIdList = new List<Id>();
                relGrpIdList.add(stla.Sales_Territory__r.GroupID__c);
                locGrpMap.put(stla.location__c,relGrpIdList);
            }else{
                locGrpMap.get(stla.location__c).add(stla.Sales_Territory__r.GroupID__c);
            }
        }
        
        for(Id locId:locGrpMap.keySet()){
            List<String> grpIdList = locGrpMap.get(locId);
            if(grpIdList != null){
                for(String grpId:grpIdList){
                    if(grpId != ''){
                        if(locOpptyMap.containsKey(locId)){
                            List<Id> opptyIdList = locOpptyMap.get(locId);
                            if(opptyIdList != null){
                                for(Id opptyId:opptyIdList){
                                    OpportunityShare opptyShareRecord = new OpportunityShare(OpportunityId = opptyId,UserOrGroupId = grpId,OpportunityAccessLevel = 'Read');
                                    opptyShareList.add(opptyShareRecord);
                                }
                            }
                        }
                    }
                }
            }
        }
        
        Database.SaveResult[] opptyShareResultArray;
        try{
            opptyShareResultArray = Database.insert(opptyShareList,false);
        }catch(DmlException e){
            CreateApexErrorLog.insertHandledExceptions(e, opptyShareResultArray, 'Opportunity__c', 'TMLocationOpptyShare', 'Class');
        }
    }
}