objects/Channel_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>&quot;Lookup to a Location object&apos;s record.
This field is a lookup to an existing Location child record when a parent Business Relationship record is selected in the existing &quot;&quot;Partner&quot;&quot; field.This is in support to attaching an Opportunity to a Partner Site.&quot;</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Associated Opportunities</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Alliance and Channel Partners</relationshipLabel>
        <relationshipName>Channel_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Alliance and Channel Partners</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Partner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance and Channel Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupID__c</fullName>
        <externalId>true</externalId>
        <label>GroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Location_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Locator Id</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrackAssociationToDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TrackAssociationToDelete</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Territory Location Assignment</label>
    <nameField>
        <label>STLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Location Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TMProcessLocationCleanUpBatch.cls
/**************************************************************************************************************
* Class Name: TMProcessLocationCleanUpBatch 
* Author: HP
* Description: This batch deletes associations between Location and Sales Territories no longer Valid
***************************************************************************************************************/

global class TMProcessLocationCleanUpBatch implements Database.batchable<sObject>, Database.Stateful{

    global String stLocToProcess = 'Select Id,Location__c,Sales_Territory__c,TrackAssociationToDelete__c,Sales_Territory__r.GroupId__c From Sales_Territory_Location_Assignment__c where TrackAssociationToDelete__c = true';
    
    /**
    * @description: Queries accounts in Sales_Territory_Location_Assignment__c to process
    * @param: Database.BatchableContext ctx
    * @return: Database queryLocator
    **/
    global Database.QueryLocator start(Database.BatchableContext bc){
        if ( Test.isRunningTest() ) stLocToProcess += ' limit 30';
        return Database.getQueryLocator(stLocToProcess);
    }
    
    /**
    * @description: Execute method for finding location assignment records that needs to be deleted
    * @param: Database.BatchableContext ctx, List<Account> stlaProcessList - location assignment list to process
    **/
    global void execute(Database.BatchableContext bc,List<Sales_Territory_Location_Assignment__c> stlaProcessList){
        try{
            List<Sales_Territory_Location_Assignment__c> stlaDeletionList = new List<Sales_Territory_Location_Assignment__c>();
            List<OpportunityShare> oppShare = new List<OpportunityShare>();
            Set<Id> locOppToDelete = new Set<Id>();
            Set<Id> grpToDelete = new Set<Id>();
            for(Sales_Territory_Location_Assignment__c stla: stlaProcessList){
                stlaDeletionList.add(stla);
                locOppToDelete.add(stla.location__c);
                grpToDelete.add(stla.Sales_Territory__r.GroupId__c);
            }
            if(!stlaDeletionList.isEmpty()){
                delete stlaDeletionList;
            }
            if(locOppToDelete !=null)
            {
                Set<Id> opptyId = new Set<Id>();
                List<Channel_Partner__c> oppToDel = [select id, Opportunity__c,location__c from Channel_Partner__c where location__c in :locOppToDelete ];
                for(integer i =0; i< oppToDel.size();i++)
                {
                    opptyId.add(oppToDel[i].Opportunity__c);
                }               
                for(OpportunityShare oppSh : [Select Id, opportunityId , UserOrGroupId from OpportunityShare where opportunityID IN : opptyId AND UserOrGroupId IN : grpToDelete AND RowCause = 'Manual'])
                {
                    oppShare.add(oppSh);
                }
                if(oppShare !=null)
                {
                    delete oppShare;
                }
            }        
        }catch(Exception e){
            system.debug('******Exception in TMProcessLocationCleanUpBatch*****'+e.getMessage());
        }
    }
    
    /**
    * @description: finish method for sending completion mail of location clean up process
    * @param: Database.BatchableContext ctx
    **/  
    global void finish(Database.BatchableContext bc){
        AsyncApexJob a = [Select id, ApexClassId, JobItemsProcessed, NumberOfErrors, TotalJobItems, CreatedBy.Email From AsyncApexJob
                                                                                                            Where id =: bc.getJobId()];
        String emailMessage = 'Your batch job ' 
                              + 'APEX Batch Job for '
                              + 'TM Process Location Clean up' + ' has finished. It executed '  
                              + a.totalJobItems   
                              + ' batches.';  
        Messaging.Singleemailmessage mail = new Messaging.Singleemailmessage();
        String[] toAddress = new String[]{a.CreatedBy.Email};
        mail.setToAddresses(toAddress);
        mail.setReplyTo('noreply@salesforce.com');
        mail.setSenderDisplayName('Batch Job Summary');
        mail.setSubject('Batch Job Completed - TM Process Location Clean up Batch');
        mail.setPlainTextBody(emailMessage);
        Messaging.sendEmail(new Messaging.Singleemailmessage[]{mail});
        
        TMAddPtrShareNonPvtAccScheduler addPtrShare = new TMAddPtrShareNonPvtAccScheduler();
        
        Datetime currentDateTime = Datetime.now();
        String min = String.valueOf(math.mod((currentDateTime.minute() + 2), 60));
        String schExp = '0 '+min+' * * * ?' ;
        system.schedule('TM - Add Partner Share for Non Private Customer Accounts', schExp, addPtrShare);
    }
}