objects/CMSFolder__c.object
<CustomObject>
    <description>CMSForce Folders. Used to categorize Pages, PageTemplates and Web Forms</description>
    <fields>
        <fullName>Parent_CMSFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this folder is a subfolder, please select it&apos;s parent here.</inlineHelpText>
        <label>Parent CMSFolder</label>
        <referenceTo>CMSFolder__c</referenceTo>
        <relationshipLabel>Subfolders</relationshipLabel>
        <relationshipName>CMSFolder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Id__c</fullName>
        <description>The Site that this folder belongs to.</description>
        <label>Site Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PageTemplate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebForm</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Folder</label>
    <nameField>
        <label>CMSFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContentBlockItem__c.object
<CustomObject>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field will determine if the item is regular HTML or a Web Form include.</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Web Form</label>
        <referenceTo>Web_Form__c</referenceTo>
        <relationshipLabel>ContentBlockItems</relationshipLabel>
        <relationshipName>ContentBlockItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ContentBlockItem</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContentBlockItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>CMSFolder__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PageTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageTemplate</label>
        <referenceTo>PageTemplate__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Id__c</fullName>
        <label>Site Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PageTemplate__c.object
<CustomObject>
    <fields>
        <fullName>ContentBlockNames__c</fullName>
        <description>This field contains the names of the content block tags defined in the template.</description>
        <label>ContentBlockNames</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>CMSFolder__c</referenceTo>
        <relationshipLabel>PageTemplates</relationshipLabel>
        <relationshipName>PageTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VisualForce_Page_Name__c</fullName>
        <label>VisualForce Page Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PageTemplate</label>
    <nameField>
        <label>PageTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageTemplates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PageToItem__c.object
<CustomObject>
    <description>This is a junction object that links contentblockitems to a page. Working with a junction object makes content items re-usable across different pages.</description>
    <fields>
        <fullName>ContentBlockItem__c</fullName>
        <label>ContentBlockItem</label>
        <referenceTo>ContentBlockItem__c</referenceTo>
        <relationshipLabel>PageItem</relationshipLabel>
        <relationshipName>PageItem</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>PageItem</relationshipLabel>
        <relationshipName>PageItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PageItem</label>
    <nameField>
        <displayFormat>ITEM-{00000}</displayFormat>
        <label>PageToItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PageItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Web_Form__c.object
<CustomObject>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Choose a folder this web form belongs to.</inlineHelpText>
        <label>Folder</label>
        <referenceTo>CMSFolder__c</referenceTo>
        <relationshipLabel>Web Forms</relationshipLabel>
        <relationshipName>Web_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>The API name of the object which fields will be filled by this form.</description>
        <inlineHelpText>The API name of the object which fields will be filled by this form.</inlineHelpText>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_URL__c</fullName>
        <description>URL the user will go to after saving the form.</description>
        <inlineHelpText>URL the user will be redirected to after saving the form.</inlineHelpText>
        <label>Return URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>SavedByWebformeditor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is internal to the app and is used to track if people didn&apos;t forget to override the edit and new buttons on the webform object. Only the webform editor will set this flag.</description>
        <label>SavedByWebformeditor</label>
        <type>Checkbox</type>
    </fields>
    <label>Web Form</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCMSForceTriggers.cls
@isTest
private class TestCMSForceTriggers {
//  Copyright (c) 2010, David Van Puyvelde, Sales Engineering, Salesforce.com Inc.
//  All rights reserved.
//
//  Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
//  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
//  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
//  Neither the name of the salesforce.com nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. 
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
//  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
//  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
//  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
//  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



	//test methods
	static testMethod void t1() {
		//set up a test web form
		Web_Form__c form = new Web_Form__c();
		form.Name = 'test webform';
		form.Object_Name__c = 'wrongAPIName';
		form.Return_URL__c = 'www.x.com';
		form.SavedByWebformeditor__c = true;
		
		try {
			insert form;
		}
		catch(DMLException dex) {
			System.assert(dex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
		}
		
		form.SavedByWebformeditor__c = false;
		try {
			insert form;
		}
		catch(DMLException dex) {			
			System.assert(dex.getMessage().contains('WebFormEditor'));
		}
	}


	//test cleanup unused contentblock items (those that don't have a pagetoitem pointing at them)
	private static testMethod void t2() {
		Site site = [select Id from Site limit 1];
		String siteid = site.Id;		
		//set up page and template folders
		CMSFolder__c pagefolder = new CMSFolder__c(Site_Id__c = siteid.substring(0,15),Type__c = 'Page', Name='test');
		insert pagefolder;
		CMSFolder__c templatefolder = new CMSFolder__c(Type__c = 'PageTemplate', Name='test');
		insert templatefolder;
        //set up a test template
        PageTemplate__c template = new PageTemplate__c(Name='test', VisualForce_Page_Name__c='TestTemplate', ContentBlockNames__c ='main,header', Folder__c = templatefolder.Id);
        insert template;
        //set up a test page
        Page__c pg = new Page__c(Name='testpage', PageTemplate__c = template.Id, Folder__c = pagefolder.Id);
        insert pg;
        //set up a test ContentBlockItem
        ContentBlockItem__c cb = new ContentBlockItem__c(Name='test content', Content__c='some content');
        insert cb;
        //use this content block in the page
        PageToItem__c pti = new PageToItem__c();
        pti.ContentBlockItem__c = cb.Id;
        pti.Page__c = pg.Id;
        insert pti;
        
        //delete the link, orphaning the contentblock
        delete pti;
        
        //the formula field updates async so I can't test for the deletion of the contentblock
        Exception ex;
        try{pti = [select Id from PageToItem__c where Id =:pti.Id];}catch(Exception ex1){ex=ex1;}
        System.assert(ex != null);	
	}
	
	//preventactive webform delete
	private static testMethod void t3() {
		Site site = [select Id from Site limit 1];
		String siteid = site.Id;		
		//set up page and template folders
		CMSFolder__c pagefolder = new CMSFolder__c(Site_Id__c = siteid.substring(0,15),Type__c = 'Page', Name='test');
		insert pagefolder;
		CMSFolder__c templatefolder = new CMSFolder__c(Type__c = 'PageTemplate', Name='test');
		insert templatefolder;
		//set up a webform folder
		CMSFolder__c webformfolder = new CMSFolder__c(Type__c = 'WebForm', Name='test');
		insert webformfolder;
        //set up a test template
        PageTemplate__c template = new PageTemplate__c(Name='test', VisualForce_Page_Name__c='TestTemplate', ContentBlockNames__c ='main,header', Folder__c = templatefolder.Id);
        insert template;
        //set up a test page
        Page__c pg = new Page__c(Name='testpage', PageTemplate__c = template.Id, Folder__c = pagefolder.Id);
        insert pg;
        //set up a test web form
		Web_Form__c form = new Web_Form__c();
		form.Name = 'test webform';
		form.Object_Name__c = 'Account';
		form.Return_URL__c = 'www.x.com';
		form.SavedByWebformeditor__c = true;
		form.Folder__c = webformfolder.Id;
		insert form;
		//set up a test ContentBlockItem
        ContentBlockItem__c cb = new ContentBlockItem__c(Name='test content', Content__c='some content', Web_Form__c = form.Id);
        insert cb;
        PageToItem__c pti = new PageToItem__c();
        pti.Page__c = pg.Id;
        pti.ContentBlockItem__c = cb.Id;
        
        insert pti;
        //this should lock the webform from delete
        Exception ex;
        try{delete form;}catch(Exception ex1){ex = ex1;}
        System.assert(ex != null);
        
	}
	
	
	//prevent folder orphans
	private static testMethod void t4() {
		Site site = [select Id from Site limit 1];
		String siteid = site.Id;		
		//set up page and template folders
		CMSFolder__c pagefolder = new CMSFolder__c(Site_Id__c = siteid.substring(0,15),Type__c = 'Page', Name='test');
		insert pagefolder;
		CMSFolder__c pagefolder2 = new CMSFolder__c(Type__c = 'Page', Name='test', Parent_CMSFolder__c = pagefolder.Id);
		insert pagefolder2;
		Exception ex;
		try{delete pagefolder;}catch(Exception ex1){ex=ex1;}
		System.assert(ex != null);
	}
	
	//prevent delete of templates used on pages
	private static testMEthod void t5() {
		Site site = [select Id from Site limit 1];
		String siteid = site.Id;		
		//set up page and template folders
		CMSFolder__c pagefolder = new CMSFolder__c(Site_Id__c = siteid.substring(0,15),Type__c = 'Page', Name='test');
		insert pagefolder;
		CMSFolder__c templatefolder = new CMSFolder__c(Type__c = 'PageTemplate', Name='test');
		insert templatefolder;
		//set up a test template
		PageTemplate__c template = new PageTemplate__c(Name='test', VisualForce_Page_Name__c='TestTemplate', Folder__c = templatefolder.Id);
		insert template;
		//set up a test page that uses the template
		Page__c pg = new Page__c(Name='testpage', PageTemplate__c = template.Id, Folder__c = pagefolder.Id);
		insert pg;
		//try to delete the template, it should fail
		Exception ex;
		try{delete template;}catch(Exception ex1){ex=ex1;}
		System.assert(ex != null);
	}

}