objects/CMSFolder__c.object
<CustomObject>
    <description>CMSForce Folders. Used to categorize Pages, PageTemplates and Web Forms</description>
    <fields>
        <fullName>Site_Id__c</fullName>
        <description>The Site that this folder belongs to.</description>
        <label>Site Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PageTemplate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebForm</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Folder</label>
    <nameField>
        <label>CMSFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMSForceDomain__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This setting will hold the url of your instance. Should be something like https://na1.salesforce.com or https://emea.salesforce.com</description>
    <label>CMSForce Domain</label>
</CustomObject>

objects/CMSForceSites__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Additional Sites information needed for CMSForce.</description>
    <fields>
        <fullName>Site_Id__c</fullName>
        <inlineHelpText>Go to the detail page of your Site definition in Setup and copy the Id which shows in the Url of your browser.</inlineHelpText>
        <label>Site Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Url__c</fullName>
        <inlineHelpText>Enter the full Site url as it appears in the Site definition page in setup (Default web address).</inlineHelpText>
        <label>Site Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CMSForce Sites</label>
</CustomObject>

objects/ContentBlockItem__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field will determine if the item is regular HTML or a Web Form include.</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ContentBlockItem</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContentBlockItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Cache_expires__c</fullName>
        <defaultValue>600</defaultValue>
        <description>This field will keep the number of seconds this page stays in the cache on the Content Delivery Network.</description>
        <inlineHelpText>This field will keep the number of seconds this page stays in the cache on the Content Delivery Network.</inlineHelpText>
        <label>Cache expires</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>CMSFolder__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FriendlyUrl__c</fullName>
        <inlineHelpText>Type a friendly url here. Do not start with a &apos;/&apos;</inlineHelpText>
        <label>FriendlyUrl</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box to set the page as the home page for the site this page is in.</description>
        <inlineHelpText>Check this box to set the page as the home page for the site this page is in.</inlineHelpText>
        <label>Home Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PageTemplateVFPage__c</fullName>
        <formula>PageTemplate__r.VisualForce_Page_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PageTemplateVFPage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PageTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageTemplate</label>
        <referenceTo>PageTemplate__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Id__c</fullName>
        <label>Site Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PageTemplate__c.object
<CustomObject>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>CMSFolder__c</referenceTo>
        <relationshipLabel>PageTemplates</relationshipLabel>
        <relationshipName>PageTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VisualForce_Page_Name__c</fullName>
        <label>VisualForce Page Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PageTemplate</label>
    <nameField>
        <label>PageTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageTemplates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PageToItem__c.object
<CustomObject>
    <description>This is a junction object that links contentblockitems to a page. Working with a junction object makes content items re-usable across different pages.</description>
    <fields>
        <fullName>ContentBlockItem__c</fullName>
        <label>ContentBlockItem</label>
        <referenceTo>ContentBlockItem__c</referenceTo>
        <relationshipLabel>PageItem</relationshipLabel>
        <relationshipName>PageItem</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>PageItem</relationshipLabel>
        <relationshipName>PageItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PageItem</label>
    <nameField>
        <displayFormat>ITEM-{00000}</displayFormat>
        <label>PageToItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PageItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CMSForceConsoleController.cls
public with sharing class CMSForceConsoleController {

	//public Boolean pageproperties {get;set;}
	public String selectednode {get;set;}
	public String selectednodetype {get;set;}
	
	public Page__c page {get;set;}
	public String previewlink {get;set;}
	public Map<ID,Site> sites;
	public List<SelectOption> siteSelectOptions {get;set;}
	public String siteurl {get;set;}
	
	public CMSForceConsoleController() {		
		sites = new Map<ID,Site>([Select s.UrlPathPrefix, s.TopLevelDomain, s.Subdomain, s.Status, s.Name, s.MasterLabel, s.Id, s.Description From Site s where Status = 'Active' limit 25]);
		siteSelectOptions = new List<Selectoption>();
		for(Site s:sites.values()) {
			Selectoption so = new Selectoption(s.Id,s.Name);
			siteSelectOptions.add(so);
		}
		//pageproperties = false;
		selectednode = 'nothing yet';
	}
	
	//pull in the properties of the page and show them
	public PageReference editPageProperties() {
		try {
			page = [Select p.PageTemplate__c, p.FriendlyUrl__c, p.Site_Id__c, p.PageTemplateVFPage__c, p.Name, p.Home_Page__c, p.Folder__c, p.Cache_expires__c From Page__c p where Id = :selectednode];
			//find the site via the rootfolder
			CMSFolder__c rootfolder = CMSForceUtils.findRootFolder(page.Folder__c);
			if(CMSForceSites__c.getAll().get(rootfolder.Site_Id__c) != null) siteurl = CMSForceSites__c.getAll().get(rootfolder.Site_Id__c).Site_Url__c;
		}
		catch(Exception ex) {
			//do nothing
		}
		return null;
	}
	
	//create a new page item
	/**
	public PageReference newPageItem() {
		PageToItem__c pti = new PageToItem__c();
		pti.Page__c = page.Id;		
		ContentBlockItem__c cbi = new ContentBlockItem__c();
		cbi.Name = '';
		insert cbi;
		pti.ContentBlockItem__c = cbi.id;
		insert pti;
		ApexPages.StandardController sc = new ApexPages.StandardController(pti);
		return sc.edit();
	}
	**/
	public PageReference savePage() {
		try {
			update page;
		}
		catch(Exception ex) {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
		}
		
		return null;
	}

	
	//get the site id for the current page
	public String getSiteId() {		
		String siteid = CMSForceUtils.findRootFolder(page.Folder__c).Site_Id__c;
		return siteid;
	}
	
	//check if the needed custom settings are initialed
	//if not redirect to the setup page
	public PageReference checkSetup() {		
		if(CMSForceDomain__c.getAll().get('cmsforcedomain') == null || CMSForceSites__c.getAll().isEmpty()) {
			return new PageReference('/apex/CMSForceSetup?showheader=true');
		}
		return null; 
	}
	
	
	/** TESTS **/
	private static testMethod void t1() {
		Site site = [select Id from Site limit 1];
		String siteid = site.Id;		
		//set up page and template folders
		CMSFolder__c pagefolder = new CMSFolder__c(Site_Id__c = siteid.substring(0,15),Type__c = 'Page', Name='test');
		insert pagefolder;
		CMSFolder__c templatefolder = new CMSFolder__c(Type__c = 'PageTemplate', Name='test');
		insert templatefolder;
		//set up a test template
		PageTemplate__c template = new PageTemplate__c(Name='test', VisualForce_Page_Name__c='TestTemplate', Folder__c = templatefolder.Id);
		insert template;
		//set up a test page
		Page__c pg = new Page__c(Name='testpage', PageTemplate__c = template.Id, Folder__c = pagefolder.Id);
		insert pg;
		
		Test.setCurrentPage(Page.CMSForceConsole);
		CMSForceConsoleController ccc = new CMSForceConsoleController();
		
		ccc.selectednode = pg.Id;
		ccc.editPageProperties();
		System.assertEquals(pg.Id, ccc.page.Id);
		ccc.savePage();
		System.assertEquals(siteid.substring(0,15), ccc.getSiteId());
		ccc.checkSetup();
		
	}
	

}