objects/CMSFolder__c.object
<CustomObject>
    <description>CMSForce Folders. Used to categorize Pages, PageTemplates and Web Forms</description>
    <fields>
        <fullName>Site_Id__c</fullName>
        <description>The Site that this folder belongs to.</description>
        <label>Site Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PageTemplate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebForm</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Folder</label>
    <nameField>
        <label>CMSFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>CMSFolder__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PageTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PageTemplate</label>
        <referenceTo>PageTemplate__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Id__c</fullName>
        <label>Site Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PageTemplate__c.object
<CustomObject>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>CMSFolder__c</referenceTo>
        <relationshipLabel>PageTemplates</relationshipLabel>
        <relationshipName>PageTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VisualForce_Page_Name__c</fullName>
        <label>VisualForce Page Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PageTemplate</label>
    <nameField>
        <label>PageTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageTemplates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/hpdcpageControllerTracker.cls
@isTest
private class hpdcpageControllerTracker {

    static testMethod void validatePageController() 
    {
         Site site = [select Id from Site limit 1];
        String siteid = site.Id;        
        //set up page and template folders
        CMSFolder__c pagefolder = new CMSFolder__c(Site_Id__c = siteid.substring(0,15),Type__c = 'Page', Name='test');
        insert pagefolder;
        CMSFolder__c templatefolder = new CMSFolder__c(Type__c = 'PageTemplate', Name='test');
        insert templatefolder;
        //set up a test template
        PageTemplate__c template = new PageTemplate__c(Name='test', VisualForce_Page_Name__c='TestTemplate', Folder__c = templatefolder.Id);
        insert template;
        //set up a test page
        Page__c pg = new Page__c(Name='testpage', PageTemplate__c = template.Id, Folder__c = pagefolder.Id);
        insert pg;
        
        PageReference pr = Page.page;
        pr.getParameters().put('pageid', pg.Id);
        Test.setCurrentPageReference(pr);
        
        pageController pc = new pageController();
        
        pc.RedirectURL();
        
        ApexPages.currentPage().getParameters().put('pagename',pg.name);
        
        ApexPages.currentPage().getParameters().put('tab','true');
        
        System.assertEquals(pc.pagetemplatename, 'TestTemplate');       
        
        //create a controller with no pageid parameter
        pr.getParameters().remove('pageid');
        
        pageController pc2 = new pageController();
        System.assertEquals(pc2.pagetemplatename, 'Id error :');
        
       
        
        
    }
}