objects/Collateral__c.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Collateral</label>
    <nameField>
        <displayFormat>CN-{00000000}</displayFormat>
        <label>Collateral Name ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>collaterals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Learning__c.object
<CustomObject>
    <description>Created: Venkatesh S\Veeresh Alur 
Date: 15/11/2013 
Capablity: ES Offering 
Release: 1 
Description: Learning Board</description>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Learning</label>
    <nameField>
        <displayFormat>LE-{0000000000}</displayFormat>
        <label>Learning ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learnings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/inputfilecontroller.cls
public class inputfilecontroller {

public blob UploadValue {get;set;}
public string Url{get;set;}
public string CollateralId{get;set;}

    public void UpdateDocUrl()
    {
    string url=Url;
    string topicId=null;
    string collateralid=CollateralId;
    system.debug('URL:'+url+',CollateralId:'+collateralid);
    system.debug('Sree - In Upload Doc URL');
           If( topicId != null){
                 Learning__c lb = new Learning__c();
                 lb.URL__c = url;
                 lb.Id = topicId;
                 update lb;
             }
            If( collateralid != null){ 
                 Collateral__c c = new Collateral__c();
                 c.URL__c = url;
                 c.Id = collateralid;
                 update c;
             }
             
            
           }
}