objects/Competitive_Sales_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Competitors__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Competitors</label>
        <referenceTo>Competitors__c</referenceTo>
        <relationshipLabel>Competitive Sales Plans</relationshipLabel>
        <relationshipName>Competitive_Sales_Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Plan__c</fullName>
        <label>Opportunity Plan</label>
        <referenceTo>Opportunity_Plan__c</referenceTo>
        <relationshipLabel>Competitive Sales Plans</relationshipLabel>
        <relationshipName>Competitive_Sales_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Opportunity_Plan__r.Opportunity__r.Name</formula>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <label>Competitive Sales Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Competive Sales Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Sales Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Competitors__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Competitor</label>
        <type>Checkbox</type>
    </fields>
    <label>Competitors</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Competitors Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/csp_defensive_strategy__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Created_On__c</fullName>
        <label>Activity Created On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csp__c</fullName>
        <label>csp</label>
        <referenceTo>Competitive_Sales_Plan__c</referenceTo>
        <relationshipLabel>CSP Defensive Strategies</relationshipLabel>
        <relationshipName>CSP_Defensive_Strategies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CSP Defensive Strategy</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>CSP Defensive Strategy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSP Defensive Strategies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/csp_offensive_strategy__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Created_On__c</fullName>
        <label>Activity Created On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csp__c</fullName>
        <label>csp</label>
        <referenceTo>Competitive_Sales_Plan__c</referenceTo>
        <relationshipLabel>CSP Offensive Strategies</relationshipLabel>
        <relationshipName>CSP_Offensive_Strategies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CSP Offensive Strategy</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>CSP Offensive Strategy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSP Offensive Strategies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Decision__c.object
<CustomObject>
    <description>Custom object for Oppotunity Planning Tool (Decision Grid)</description>
    <fields>
        <fullName>Decision__c</fullName>
        <label>Decision</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Plan__c</fullName>
        <label>Opportunity Plan</label>
        <referenceTo>Opportunity_Plan__c</referenceTo>
        <relationshipLabel>Decisions</relationshipLabel>
        <relationshipName>Decisions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <label>Who</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Decision</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Decision ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Decisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Plans</relationshipLabel>
        <relationshipName>Opportunity_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Plan</label>
    <nameField>
        <displayFormat>OP-{00000000}</displayFormat>
        <label>Opportunity Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Relationship_Suite__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Plan__c</fullName>
        <label>Opportunity Plan</label>
        <referenceTo>Opportunity_Plan__c</referenceTo>
        <relationshipLabel>Relationship Suite</relationshipLabel>
        <relationshipName>Relationship_Suite</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Relationship Suite</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Suite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/cspExtensionControllerTest.cls
/************************************************************************
Purpose     : Test Class for cspExtensionController                  
Parameters  : None
Returns     : None
***********************************************************************/
@isTest(SeeAllData=true) 
public class cspExtensionControllerTest
    {  
        static testmethod void testcspExtensionController(){  
        
        Account acc=TestingSetupDataUtil.createAccount('Test','test@abc.com','Competitor');
        insert acc;
        Account acc1=TestingSetupDataUtil.createAccount('Test','test@abc.com','Customer');
        insert acc1;
        Opportunity opp = new Opportunity(AccountId = acc1.id, StageName = '01 - Understand Customer', Name = 'abc', CloseDate = system.today(),CurrencyIsoCode='USD');
        insert opp;
        Opportunity_Plan__c opplan=new Opportunity_Plan__c(Opportunity__c=opp.id);
        insert opplan;
        Competitors__c competator=new Competitors__c(Opportunity__c=opp.id,Primary__c=true);
        insert competator;
        
        Competitive_Sales_Plan__c cspsalesplan=new Competitive_Sales_Plan__c(Opportunity_Plan__c=opplan.id,Competitors__c=competator.id);
        insert cspsalesplan;
        csp_defensive_strategy__c cspdefensive=new csp_defensive_strategy__c(csp__c=cspsalesplan.Id,Activity_Created_On__c=system.today());
        insert cspdefensive;
        csp_offensive_strategy__c cspoffensive=new csp_offensive_strategy__c(csp__c=cspsalesplan.Id);
        insert cspoffensive;
        
        Relationship_Suite__c relatiosuite=new Relationship_Suite__c(Opportunity_Plan__c=opplan.Id);
        insert relatiosuite;
        Decision__c decision=new Decision__c(Opportunity_Plan__c=opplan.Id,Who__c='test');
        insert decision;
        
        ApexPages.StandardController controller= new ApexPages.StandardController(new Competitive_Sales_Plan__c());
        system.currentPageReference().getParameters().put('id',competator.id);
        system.currentPageReference().getParameters().put('cspName',competator.id);
        system.currentPageReference().getParameters().put('oppPlanId',opplan.Id);
        
        cspExtensionController cspextention=new cspExtensionController(controller);
        cspextention.oppPlanId=opplan.Id;
        cspextention.chosenOffId=cspoffensive.Id;
        cspextention.chosenDefId=cspdefensive.Id;
        cspextention.idcount='test';
        cspextention.getRelatedOffensiveStrategies();
        cspextention.getRelatedDefensiveStrategies();       
        cspextention.addOffRow();
        cspextention.addDefRow();
        cspextention.customSave();
        cspextention.customCancel();
        cspextention.getBuyingCriteria();
        cspextention.getDecisionMakers();
        cspextention.getDecisionCount();
        cspextention.goBack();
        cspextention.getRelatedOffensiveStrategiesT();
        cspextention.getRelatedDefensiveStrategiesT();
        cspextention.CreateOffActivities();
        cspextention.CreateDefActivities();
        cspextention.removeOffRow();
        cspextention.removeDefRow();
        
        
       
        
        }
   }