objects/Competitive_Sales_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Plan__c</fullName>
        <label>Opportunity Plan</label>
        <referenceTo>Opportunity_Plan__c</referenceTo>
        <relationshipLabel>Competitive Sales Plans</relationshipLabel>
        <relationshipName>Competitive_Sales_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Opportunity_Plan__r.Opportunity__r.Name</formula>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <label>Competitive Sales Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Competive Sales Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Sales Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Plans</relationshipLabel>
        <relationshipName>Opportunity_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Plan</label>
    <nameField>
        <displayFormat>OP-{00000000}</displayFormat>
        <label>Opportunity Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CSPCompetitorAddExtensionTest.cls
/************************************************************************
Purpose     : Test Class for CSPCompetitorAddExtension
Parameters  : None
Returns     : None
***********************************************************************/
@isTest(SeeAllData=true) 
public class CSPCompetitorAddExtensionTest
    {  
        static testmethod void testCSPCompetitorAddExtension(){
        
        Account acc=TestingSetupDataUtil.createAccount('Test','test@abc.com','Customer');
        insert acc;
        Opportunity opp = new Opportunity(AccountId = acc.id, StageName = '01 - Understand Customer', Name = 'abc', CloseDate = system.today(),CurrencyIsoCode='USD');
        insert opp;
        Opportunity_Plan__c opplan=new Opportunity_Plan__c(Opportunity__c=opp.id);
        insert opplan;

        
        ApexPages.StandardController controller= new ApexPages.StandardController(new Competitive_Sales_Plan__c());
        system.currentPageReference().getParameters().put('OppPlanId',opplan.id);
        system.currentPageReference().getParameters().put('retURL','/apex/');
        
        CSPCompetitorAddExtension cspextention=new CSPCompetitorAddExtension(controller);
        cspextention.getCSP();
        cspextention.initialize();
        cspextention.Save();
        cspextention.cancel();
        
        }
     }