objects/Competitive_Sales_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Competitor__c</fullName>
        <formula>Competitors__r.Competitor_Account__r.Name</formula>
        <label>Competitor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Plan__c</fullName>
        <label>Opportunity Plan</label>
        <referenceTo>Opportunity_Plan__c</referenceTo>
        <relationshipLabel>Competitive Sales Plans</relationshipLabel>
        <relationshipName>Competitive_Sales_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Opportunity_Plan__r.Opportunity__r.Name</formula>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <label>Competitive Sales Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Competive Sales Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Sales Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/csp_defensive_strategy__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Created_On__c</fullName>
        <label>Activity Created On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csp__c</fullName>
        <label>csp</label>
        <referenceTo>Competitive_Sales_Plan__c</referenceTo>
        <relationshipLabel>CSP Defensive Strategies</relationshipLabel>
        <relationshipName>CSP_Defensive_Strategies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ct_countertactic__c</fullName>
        <label>ct_countertactic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ct_owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ct_owner</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>CSP Defensive Strategies</relationshipLabel>
        <relationshipName>CSP_Defensive_Strategies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ct_timing__c</fullName>
        <label>ct_timing</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>our_weakness_countered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>our_weakness_countered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>our_weakness_customer_validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>our_weakness_customer_validated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>our_weakness_text__c</fullName>
        <label>our_weakness_text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>their_strength_countered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>their_strength_countered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>their_strength_customer_validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>their_strength_customer_validated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>their_strength_text__c</fullName>
        <label>their_strength_text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSP Defensive Strategy</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>CSP Defensive Strategy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSP Defensive Strategies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/csp_offensive_strategy__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Created_On__c</fullName>
        <label>Activity Created On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csp__c</fullName>
        <label>csp</label>
        <referenceTo>Competitive_Sales_Plan__c</referenceTo>
        <relationshipLabel>CSP Offensive Strategies</relationshipLabel>
        <relationshipName>CSP_Offensive_Strategies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>strength_customer_validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>strength_customer_validated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>strength_leveraged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>strength_leveraged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>strength_text__c</fullName>
        <label>strength_text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tactic_owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>tactic_owner</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>CSP Offensive Strategies</relationshipLabel>
        <relationshipName>CSP_Offensive_Strategies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tactic_text__c</fullName>
        <label>tactic_text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tactic_timing__c</fullName>
        <label>tactic_timing</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>their_weakness_customer_validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>their_weakness_customer_validated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>their_weakness_exploited__c</fullName>
        <defaultValue>false</defaultValue>
        <label>their_weakness_exploited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>their_weakness_text__c</fullName>
        <label>their_weakness_text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSP Offensive Strategy</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>CSP Offensive Strategy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSP Offensive Strategies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Decision__c.object
<CustomObject>
    <description>Custom object for Oppotunity Planning Tool (Decision Grid)</description>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Decision__c</fullName>
        <label>Decision</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Plan__c</fullName>
        <label>Opportunity Plan</label>
        <referenceTo>Opportunity_Plan__c</referenceTo>
        <relationshipLabel>Decisions</relationshipLabel>
        <relationshipName>Decisions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Who__c</fullName>
        <label>Who</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Decision</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Decision ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Decisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Plans</relationshipLabel>
        <relationshipName>Opportunity_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Plan</label>
    <nameField>
        <displayFormat>OP-{00000000}</displayFormat>
        <label>Opportunity Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Relationship_Suite__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationship Suite</relationshipLabel>
        <relationshipName>Relationship_Suite</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Plan__c</fullName>
        <label>Opportunity Plan</label>
        <referenceTo>Opportunity_Plan__c</referenceTo>
        <relationshipLabel>Relationship Suite</relationshipLabel>
        <relationshipName>Relationship_Suite</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship_map__c</fullName>
        <label>Relationship map</label>
        <picklist>
            <picklistValues>
                <fullName>Authorizer - Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorizer - Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer - Political Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer - Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Justifier-Financial Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Justifier-SME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operationalizer-End User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operationalizer-Internal Enabler</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Relationship Suite</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Suite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/cspExtensionController.cls
public with sharing class cspExtensionController {
    
    public String cspName;
    public String oppPlanId {get;set;}
    public String id;
    public List<csp_offensive_strategy__c> relatedOffensiveStrategies;
    public List<csp_defensive_strategy__c> relatedDefensiveStrategies;
    public ApexPages.StandardController std; 
    public Id chosenOffId {get; set;}
    public Id chosenDefId {get; set;}
    public Integer off_count {get;set;}
    public Integer def_count {get;set;}
    public Integer rows {get;set;}
    public String idcount {get;set;}
    public String printView {get;set;}
    public Competitive_Sales_Plan__c compsaleplan;
    public cspExtensionController(ApexPages.StandardController controller) {
    std=controller;
    
    this.compsaleplan=(Competitive_Sales_Plan__c)std.getRecord();
        
        
        this.cspName = ApexPages.currentPage().getParameters().get('cspName');
        this.id = ApexPages.currentPage().getParameters().get('id');
        this.oppPlanId = ApexPages.currentPage().getParameters().get('oppPlanId');
        this.printView = ApexPages.currentPage().getParameters().get('printView');
        
    }
    
    public List<csp_offensive_strategy__c> getRelatedOffensiveStrategies()
    {
        relatedOffensiveStrategies = [SELECT csp__c,Id,Name,strength_customer_validated__c,strength_leveraged__c,strength_text__c,their_weakness_customer_validated__c,their_weakness_exploited__c,their_weakness_text__c, tactic_timing__c, tactic_text__c, tactic_owner__c  FROM csp_offensive_strategy__c where csp__c = :cspName ORDER BY CreatedDate asc];
        off_count = [SELECT count() FROM csp_offensive_strategy__c where csp__c =:cspName];
        return relatedOffensiveStrategies;
    }
    
    public List<csp_defensive_strategy__c> getRelatedDefensiveStrategies()
    {
        relatedDefensiveStrategies = [SELECT csp__c,Id,Name,our_weakness_countered__c,our_weakness_customer_validated__c,our_weakness_text__c,their_strength_countered__c,their_strength_customer_validated__c,their_strength_text__c, ct_countertactic__c, ct_owner__c, ct_timing__c FROM csp_defensive_strategy__c where csp__c = :cspName ORDER BY CreatedDate asc];
        def_count = [SELECT count() FROM csp_defensive_strategy__c where csp__c =:cspName];
        return relatedDefensiveStrategies;
    }
    
    public void addOffRow(){
    try{
        update relatedOffensiveStrategies;
        update relatedDefensiveStrategies;
        //std.save();
        upsert compsaleplan;
        for (Integer i=0; i<rows;i++){
            csp_offensive_strategy__c new_strategy = new csp_offensive_strategy__c();
            new_strategy.csp__c = cspName;
            insert new_strategy;
        }
    
        }catch(Exception e){
            ApexPages.addMessages(e);
           
        }
        
    }
    
    public void addDefRow(){
      try{
        update relatedOffensiveStrategies;
        update relatedDefensiveStrategies;
        //std.save();
        upsert compsaleplan;
        for (Integer i=0; i<rows;i++){
            csp_defensive_strategy__c new_strategy = new csp_defensive_strategy__c();
            new_strategy.csp__c = cspName;
            insert new_strategy;
        }
       }catch(Exception e){
        ApexPages.addMessages(e);
       }
        
    }
    
    public void removeOffRow(){
        
       try{
        update relatedOffensiveStrategies;
        update relatedDefensiveStrategies;
        //std.save();
        upsert compsaleplan;
        csp_offensive_strategy__c delrow = new csp_offensive_strategy__c(Id=chosenOffId);
        delete delrow;
       }catch(Exception e){
       
       }
    }
    
    public void removeDefRow(){
    try{
        update relatedOffensiveStrategies;
        update relatedDefensiveStrategies;
        //std.save();
        upsert compsaleplan;
        csp_defensive_strategy__c delrow = new csp_defensive_strategy__c(Id=chosenDefId);
        delete delrow;
      }catch(Exception e){
      
      }
    }

    public PageReference customSave(){
        
      try{
        update relatedOffensiveStrategies;
        update relatedDefensiveStrategies;
        //std.save();
        upsert compsaleplan;
        PageReference pr = new PageReference('/apex/CSP_List?id='+oppPlanId);
        pr.setRedirect(true);
        return pr;
       }catch(Exception e){
           
           ApexPages.addMessages(e);
           return null;
       
       }
    }
    
    public PageReference customCancel(){
        
        std.cancel();
        PageReference pr = new PageReference('/apex/CSP_List?id='+oppPlanId);
        pr.setRedirect(true);
        return pr;
    
    }
    
    public List<Decision__c> getBuyingCriteria(){
        List<Decision__c> qlist = new List<Decision__c>([SELECT Criteria__c FROM Decision__c WHERE Opportunity_Plan__c = :oppPlanId]);
        List<Decision__c> result = new List<Decision__c>();
        for (Decision__c d : qlist) {
            if (d.Criteria__c != null) {
                result.add(d);
            }
        }
        return result;
    }
    
    public List<Relationship_Suite__c> getDecisionMakers(){
        
        List<Relationship_Suite__c> rs = new List<Relationship_Suite__c>([SELECT Contact__r.Name,Contact__r.Title, Relationship_map__c FROM Relationship_Suite__c WHERE Opportunity_Plan__c = :oppPlanId ]);
        List<Relationship_Suite__c> result = new List<Relationship_Suite__c>();
        String compareme; 
        for (Relationship_Suite__c r : rs){
            compareme = String.valueOf(r.Relationship_map__c);
            if (compareme == null){
                compareme = '_';
            }
            if (compareme.indexOf('Decision Maker',0) > -1){
                result.add(r);
            }
        }
        return result;
    }
    
    public Integer getDecisionCount(){
        List<Decision__c> decisions = new List<Decision__c>([SELECT Who__c FROM Decision__c WHERE Opportunity_Plan__c = :oppPlanId]);
        Integer decision_count = 0;
        String compareme;
        for (Decision__c d : decisions){
            compareme = String.valueOf(d.Who__c);
            if (compareme == null){
                compareme = '_';
            }
            if (compareme.indexOf(idcount,0)>-1){
                decision_count = decision_count + 1;
            }
        }
        
        return decision_count;
        
    }
    
    public PageReference goBack(){
        PageReference pr = new PageReference('/apex/CSP_List?id='+oppPlanId);
        pr.setRedirect(true);
        return pr;
    
    }
    
    
    
    public List<csp_offensive_strategy__c> getRelatedOffensiveStrategiesT()
    {
        relatedOffensiveStrategies = [SELECT csp__c,Id,Name,Activity_Created_On__c, tactic_timing__c, tactic_text__c, tactic_owner__c  FROM csp_offensive_strategy__c where csp__c = :cspName and tactic_text__c <>null ORDER BY CreatedDate asc];
        off_count = [SELECT count() FROM csp_offensive_strategy__c where csp__c =:cspName ];
        return relatedOffensiveStrategies;
    }
     public List<csp_defensive_strategy__c> getRelatedDefensiveStrategiesT()
    {
        relatedDefensiveStrategies = [SELECT csp__c,Id,Name, Activity_Created_On__c, ct_countertactic__c, ct_owner__c, ct_timing__c FROM csp_defensive_strategy__c where csp__c = :cspName and ct_countertactic__c <>null ORDER BY CreatedDate asc];
        def_count = [SELECT count() FROM csp_defensive_strategy__c where csp__c =:cspName];
        return relatedDefensiveStrategies;
    }  
  
    public void CreateOffActivities(){
//        csp_offensive_strategy__c currow = new csp_offensive_strategy__c(Id='a0ZJ0000000EzgnMAC');
         csp_offensive_strategy__c currow = [SELECT csp__c,Id,Activity_Created_On__c,Name,csp__r.Opportunity_Plan__r.Opportunity__r.Id,csp__r.name, tactic_timing__c, tactic_text__c, tactic_owner__c  FROM csp_offensive_strategy__c where Id=:chosenOffId];
        
        // Instanciate Object
        Task tskNew = new Task();
        
        // Pre-populate Fields
//        tskNew.WhoId = currow.tactic_owner__c; 
        tskNew.WhatId = currow.csp__r.Opportunity_Plan__r.Opportunity__r.Id; 
        tskNew.Subject = currow.tactic_text__c; // Pull CS Subject
        tskNew.ActivityDate = currow.tactic_timing__c; 
        tskNew.Description = currow.csp__r.name; 
        tskNew.OwnerId = currow.tactic_owner__c;                
            System.debug('INSERTING OFF' + currow.tactic_text__c + ':' + chosenOffId ) ;
        try {
            insert tskNew;
            } 
            catch(DMLException e) {
            tskNew.addError(e.getMessage());
            System.debug('ERRORING OFF') ;
            System.debug(e.getMessage()) ;
            }
        currow.Activity_Created_On__c =date.today();
        update currow;
            
    }
    
    public void CreateDefActivities(){
//        csp_defensive_strategy__c currow = new csp_defensive_strategy__c(Id=chosenDefId);
         csp_defensive_strategy__c currow = [SELECT csp__c,Id,csp__r.competitor__c,Name,Activity_Created_On__c,csp__r.Opportunity_Plan__r.Opportunity__r.Id,csp__r.name, ct_timing__c, ct_countertactic__c, ct_owner__c  FROM csp_defensive_strategy__c where Id=:chosenDefId];

        // Instanciate Object
        Task tskNew = new Task();
        
        // Pre-populate Fields
//        tskNew.WhoId = currow.ct_owner__c; 
        tskNew.WhatId = currow.csp__r.Opportunity_Plan__r.Opportunity__r.Id; 
        tskNew.Subject = currow.ct_countertactic__c; // Pull CS Subject
        tskNew.ActivityDate = currow.ct_timing__c; 
        tskNew.Description = currow.csp__r.competitor__c; 
        tskNew.OwnerId = currow.ct_owner__c;                
            System.debug('INSERTING DEF') ;
        try {
            insert tskNew;
            } 
            catch(DMLException e) {
            tskNew.addError(e.getMessage());
            System.debug('ERRORING DEF') ;
            System.debug(e.getMessage());  
            }
            
        currow.Activity_Created_On__c =date.today();
        update currow;
              
    }
    
    
}