objects/Contributor__c.object
<CustomObject>
    <fields>
        <fullName>Include__c</fullName>
        <formula>If( Stage_Work_Element__r.Include__c = TRUE , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <formula>Role__r.Role_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Work_Element__c</fullName>
        <label>Work Element Id</label>
        <referenceTo>Stage_Work_Element__c</referenceTo>
        <relationshipLabel>Contributors</relationshipLabel>
        <relationshipName>Contributors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Contributor</label>
    <nameField>
        <displayFormat>Contributor-{0000000000}</displayFormat>
        <label>Contributor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contributors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Core_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Contributor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contributor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <formula>Release_Role__r.Role_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Core_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>CTM-{0000000000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Link__c.object
<CustomObject>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Stage_Work_Element_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Element ID</label>
        <referenceTo>Stage_Work_Element__c</referenceTo>
        <relationshipLabel>Links</relationshipLabel>
        <relationshipName>Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Link</label>
    <nameField>
        <displayFormat>Link-{0000000000}</displayFormat>
        <label>Link ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Release_Deliverable__c.object
<CustomObject>
    <fields>
        <fullName>Include__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include</label>
        <type>Checkbox</type>
    </fields>
    <label>Deliverable</label>
    <nameField>
        <displayFormat>D-{0000000000}</displayFormat>
        <label>Deliverable ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliverables</pluralLabel>
    <recordTypes>
        <fullName>Attachment</fullName>
        <active>false</active>
        <label>Attachment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Link</fullName>
        <active>true</active>
        <label>Link</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Release_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Include__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Include checkbox indicates the Release Stage
should be included (checked) or excluded (unchecked) for the
Offering Release.</description>
        <inlineHelpText>The Include indicates the Release Stage
should be included (checked) or excluded (unchecked) for the
Offering Release.</inlineHelpText>
        <label>Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage_Name__c</fullName>
        <formula>Stage_ID__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Stage Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stage</label>
    <nameField>
        <displayFormat>S-{0000000000}</displayFormat>
        <label>Stage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Review__c.object
<CustomObject>
    <fields>
        <fullName>Include__c</fullName>
        <formula>If( Stage_Work_Element__r.Include__c = TRUE , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <formula>Role__r.Role_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Work_Element__c</fullName>
        <label>Work Element Id</label>
        <referenceTo>Stage_Work_Element__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member Id</label>
        <referenceTo>Core_Team_Member__c</referenceTo>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review</label>
    <nameField>
        <displayFormat>Review-{0000000000}</displayFormat>
        <label>Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Stage_Work_Element__c.object
<CustomObject>
    <fields>
        <fullName>Accountable_Process_Role_Name__c</fullName>
        <formula>Accountable_Role__r.Role_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accountable Process Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Accountable_Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accountable Team Member</label>
        <referenceTo>Core_Team_Member__c</referenceTo>
        <relationshipName>Stage_Work_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accountable_User__c</fullName>
        <formula>Accountable_Team_Member__r.User__r.Last_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accountable User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Include__c</fullName>
        <formula>IF(Release_Stage_ID__r.Include__c  = TRUE &amp;&amp;  Release_Deliverable_ID__r.Include__c = TRUE ,TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optional__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Optional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Release_Stage_ID__c</fullName>
        <label>Stage ID</label>
        <referenceTo>Release_Stage__c</referenceTo>
        <relationshipName>Stage_Work_Elements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Review_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Review Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage_Name__c</fullName>
        <formula>Release_Stage_ID__r.Stage_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Work_Element_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process Work Element ID</label>
        <referenceTo>Work_Element__c</referenceTo>
        <relationshipLabel>Work Elements</relationshipLabel>
        <relationshipName>Stage_Work_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Instructions__c</fullName>
        <label>Work Instructions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Work Element</label>
    <nameField>
        <displayFormat>WE-{0000000000}</displayFormat>
        <label>Work Element ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Stage_Work_Element_Predecessor__c.object
<CustomObject>
    <fields>
        <fullName>Include__c</fullName>
        <formula>IF (  Stage_Work_Element__r.Include__c = TRUE &amp;&amp;  Predecessor_Stage_Work_Element_ID__r.Include__c = TRUE,TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage_Work_Element__c</fullName>
        <label>Work Element Id</label>
        <referenceTo>Stage_Work_Element__c</referenceTo>
        <relationshipLabel>Work Element Predecessors (Stage Work Element Id)</relationshipLabel>
        <relationshipName>Stage_Work_Element_Predecessors1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Element__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Predecessor Process Work Element Id</label>
        <referenceTo>Work_Element__c</referenceTo>
        <relationshipLabel>Work Element Predecessors</relationshipLabel>
        <relationshipName>Stage_Work_Element_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Element Predecessor</label>
    <nameField>
        <displayFormat>WEP-{0000000000}</displayFormat>
        <label>Work Element Predecessor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Element Predecessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Work_Element__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Optional__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Optional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Review_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Review Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage_Name__c</fullName>
        <formula>Stage_ID__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Stage Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Instructions__c</fullName>
        <label>Work Instructions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Process Work Element</label>
    <nameField>
        <displayFormat>PWE-{0000000000}</displayFormat>
        <label>Process Work Element ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Work Element</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ODP_Extension_WorkElementDetail.cls
public class ODP_Extension_WorkElementDetail {

    public boolean IsBizEngaPartners{get;set;}
    public Stage_Work_Element__c swe{get;set;}
    public string host{get;set;}
    public string CurSweID{get;set;}
    public List<Contributor__c> ContribList{get;set;}
    public List<Review__c> ReviewList{get;set;}
    public List<Stage_Work_Element_Predecessor__c> PredecessorList{get;set;}
        
    public class  AttachmentAndLink{
        public string docId{get;set;}
        public string name{get;set;}
        public string fileType{get;set;}
        public string addBY{get;set;}
        public Date  modifyDate{get;set;}
        public string lik{get;set;}         
    }
    public Attachment attachDoc{get;set;}
    public List<AttachmentAndLink> attachmentAndLinkList{get;set;}
    public LIST<Attachment> documents {get;set;}
    public LIST<Attachment> tempattach {get;set;}
    public LIST<Link__c> links {get;set;}
    public Link__c link {get;set;}
    
    public ODP_Extension_WorkElementDetail(ApexPages.StandardController controller) {
        IsBizEngaPartners = ODP_Class_CommonTools.IsBizEngaPartner();
        host = ApexPages.currentPage().getHeaders().get('Host');
        CurSweID = ApexPages.currentPage().getParameters().get('id');
        link = new Link__c();
        attachDoc = new Attachment();
        
        if(CurSweID != null){
            //get swe Inout
            documents = [SELECT id,CreatedById, name,lastmodifiedDate,ownerid FROM Attachment WHERE parentid = :CurSweID ORDER By Name];
            links = [select id, Link__c, CreatedById, Name__c , lastmodifiedDate from Link__c where Stage_Work_Element_ID__c=:CurSweID];
            User tempUser = new User(); 
            attachmentAndLinkList = new List<AttachmentAndLink>();           
            for(Attachment attTemp : documents ){
                AttachmentAndLink tempObj = new AttachmentAndLink();
                tempObj.docId= string.valueOf(attTemp.id); 
                tempObj.name = attTemp.name;
                tempObj.fileType = 'Document';
                tempUser = [select email, Name from User where id =: attTemp.CreatedById ];               
                tempObj.addBY = tempUser.Name;
                tempObj.modifyDate = attTemp.lastmodifiedDate.date();
                tempObj.lik = null;               
                attachmentAndLinkList.add(tempObj);                               
            }
            for(Link__c attTemp : links ){
                AttachmentAndLink tempObj = new AttachmentAndLink();
                tempObj.docId = attTemp.id; 
                tempObj.name = attTemp.Name__c;
                tempObj.fileType = 'Link';
                tempUser = [select email, Name from User where id =: attTemp.CreatedById ];               
                tempObj.addBY = tempUser.Name;
                tempObj.modifyDate = attTemp.lastmodifiedDate.date();
                tempObj.lik = attTemp.Link__c;               
                attachmentAndLinkList.add(tempObj);                                
            }
        }
        
        swe = (Stage_Work_Element__c)controller.getRecord();
        swe = [select  id,
                       Name,
                       Name__c,
                       Accountable_Team_Member__r.User__r.email,
                       Accountable_Team_Member__r.User__r.SmallPhotourl,
                       Accountable_User__c,
                           Accountable_Process_Role_Name__c,
                       Optional__c,
                       Status__c,
                       Include__c,
                       Review_Required__c,
                       Work_Instructions__c,
                       Text__c,
                       Stage_Name__c,
                           Release_Stage_ID__r.Offering_Release_ID__c,
                       Release_Stage_ID__c,
                       Review_Due_Date__c,
                       Work_Element_Name__c,
                       Work_Element_ID__c,
                       Release_Name__c,
                       Help_Description__c,
                       Description_Text_Area__c,
                       Deliverable_Name__c,
                       Release_Deliverable_ID__c,
                           Release_Deliverable_ID__r.Release_Deliverable_Name__c,
                       Days_To_Review__c,
                       Contribute_Due_Date__c
               from    Stage_Work_Element__c
               where   id =: CurSweID];
        
        ContribList = [select id, Name, Completed__c, include__c,Team_member_name__c,Role_Name__c,Team_Members__r.User__r.Id,Team_Members__r.User__r.email, Team_Members__r.User__r.smallphotourl from Contributor__c where Stage_Work_Element__c =: CurSweID];
                ReviewList = [select id, Name, Complete__c, include__c, Rating__c, Team_Member_Name__c,Role_Name__c,Comment__c, Team_Member__r.User__r.email, Team_Member__r.User__r.smallphotourl from Review__c where Stage_Work_Element__c =: CurSweID];           
        PredecessorList = [select id, Name, Include__c, Work_Element__c, Predecessor_Stage_Work_Element_ID__c, Predecessor_Stage_Work_Element_Name__c, Stage_Work_Element_Name__c,  
                           Predecessor_Stage_Work_Element_ID__r.Accountable_Team_Member__r.User__r.email,
                           Predecessor_Stage_Work_Element_ID__r.Accountable_Team_Member__r.User__r.smallphotourl,
                           Predecessor_Stage_Work_Element_ID__r.Accountable_Team_Member__r.User__c
                           from Stage_Work_Element_Predecessor__c where Stage_Work_Element__c =:CurSweID];          
    }
    
    
    public PageReference FileUploadSave(){
        try{
            //contributor.completed__c = True;
            attachDoc.ParentId = CurSweID; 
            insert attachDoc;
            PageReference pageRef = new PageReference('/'+CurSweID);
            pageRef.setRedirect(true); 
            return pageRef;
        }
        catch(exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Operation Failed: file upload exception, Please contact IT Administrator if any assistance needed'));
            return null;
        }       
    }
    

  
  public string addtaLinkId{get;set;} 
  public string addtaLinkType{get;set;}       
  public PageReference deleteAttaLink(){
        try{
            //system.debug('documentId' + addtaLinkId);        
      
            if(addtaLinkType == 'Link'){
                system.debug(addtaLinkId);            
                Link__c linkDel = [select id, Link__c, CreatedById, Name__c , lastmodifiedDate from Link__c where id =: addtaLinkId];
                delete linkDel;                 
            }
            else if(addtaLinkType == 'Document'){
                Attachment  attachmentDel = [SELECT id,CreatedById, name,lastmodifiedDate,ownerid FROM Attachment WHERE id = :addtaLinkId];
                delete attachmentDel;                 
            } 
            PageReference pageRef = new PageReference('/' + CurSweID);
            pageRef.setRedirect(true); 
                        
            return pageRef;                     
        }
        catch(exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Operation Failed: deletion exception, Please contact IT Administrator if any assistance needed'));
            return null;            
        }
  }
    
    
    public PageReference saveLink(){
         try{
            if(string.IsEmpty(link.Name__c) || string.IsEmpty(link.Link__c))
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'must provide the link name link url.'));
                return null;
            }
            //add by june.
            List<Link__c> links = [SELECT Link__c,Name,Name__c FROM Link__c WHERE Name__c =:link.Name__c];
            if(links.size()>0){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Link name was already existed in current work element or in another,please use a unique name.'));
                return null;
            }
            //---end---
            link.Stage_Work_Element_ID__c = CurSweID;
            insert link;
            PageReference pageRef = new PageReference('/' + CurSweID);
            pageRef.setRedirect(true); 
            return pageRef;
        }
        catch(exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Operation Failed: save link exception, Please contact IT Administrator if any assistance needed'));
            return null;
        }
    }
   
    public Document document {
    get {
      if (document == null) document = new Document();
      return document;
    }
    set;
  }
    

}