objects/Contract_Reference__c.object
<CustomObject>
    <description>Contract related to the corresponding renewal opportunity is displayed</description>
    <fields>
        <fullName>AMP_ID__c</fullName>
        <label>AMP ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_End_date__c</fullName>
        <label>Contract End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <label>Functional Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Contract_Nbr__c</fullName>
        <label>Group Contract Nbr</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contract References</relationshipLabel>
        <relationshipName>Contract_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAID__c</fullName>
        <label>SAID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Doc_Nbr__c</fullName>
        <externalId>true</externalId>
        <label>Sales Doc Nbr</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Contract_Value__c</fullName>
        <label>Total Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract Reference</label>
    <nameField>
        <label>Sales Document Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HP_Quote__c.object
<CustomObject>
    <description>Custom quote object to capture quotes from Quote IDS and to support future integration with CPQ tools</description>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Functional Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>HP Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Originating_System_Quote_ID__c</fullName>
        <label>Quote ID Doc #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Request</label>
        <referenceTo>Support_Request__c</referenceTo>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HP Quote</label>
    <nameField>
        <label>HP Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SRTDataFromSFDCController.cls
public class SRTDataFromSFDCController{  
    private ApexPages.StandardController stdCtrl {get; set;} 
    public List<Support_Request__c> SR {get; set;}     
    public List<Contract_Reference__c> conts {get; set;}     
    public List<HP_Quote__c> quotesList{get;set;}
    public List<OpportunityLineItem> opportunityLineItem {get; set;}     
    public Opportunity oppty {get; set;} 
    public Account account {get; set;} 
    public SRTDataFromSFDCController(ApexPages.StandardController std)  {   stdCtrl=std;   setupContacts();  }     
        private void setupContacts(){   
            SR = [select Opportunity__c from Support_Request__c where id=:stdCtrl.getId()];
            if(SR.size()==1){
                oppty = [select id,Name,AccountId from Opportunity where id = :SR[0].Opportunity__c];
                account = [Select id, Name from Account where id = :oppty.AccountId];
                conts=[select Name,Sales_Doc_Nbr__c, Document_Type__c, AMP_ID__c,Group_Contract_Nbr__c,SAID__c,Contract_Start_Date__c,Contract_End_date__c,Total_Contract_Value__c,Functional_Location__c from Contract_Reference__c where Original_Opportunity__c = :SR[0].Opportunity__c Limit 1000]; 
                opportunityLineItem=[select Sales_Doc_Nbr__c,Description,Quantity ,UnitPrice,ListPrice,Discount,ProductId__c,Product__c,ProductName__c from OpportunityLineItem where OpportunityId = :SR[0].Opportunity__c Limit 1000];
                quotesList = new List<HP_Quote__c>();
                quotesList = [Select Id, Originating_System_Quote_ID__c From HP_Quote__c Where Opportunity_Name__c = :SR[0].Opportunity__c Limit 1000];
                
            }
        /********Commented for optimization by Deepak Saxena**********************************************/
        /* for(Support_Request__c section : SR){ 
            oppty = [select id,Name,AccountId from Opportunity where id = :section.Opportunity__c];
            account = [Select id, Name from Account where id = :oppty.AccountId];
            conts=[select Name,Sales_Doc_Nbr__c, Document_Type__c, AMP_ID__c,Group_Contract_Nbr__c,SAID__c,Contract_Start_Date__c,Contract_End_date__c,Total_Contract_Value__c,Functional_Location__c from Contract_Reference__c where Original_Opportunity__c = :section.Opportunity__c]; 
            opportunityLineItem=[select Sales_Doc_Nbr__c,Description,Quantity ,UnitPrice,ListPrice,Discount,ProductId__c,Product__c,ProductName__c from OpportunityLineItem where OpportunityId = :section.Opportunity__c];
        } */
    } 
}