objects/Contributor__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <formula>Role__r.Role_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Work_Element_Name__c</fullName>
        <formula>Stage_Work_Element__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Element Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Work_Element__c</fullName>
        <label>Work Element Id</label>
        <referenceTo>Stage_Work_Element__c</referenceTo>
        <relationshipLabel>Contributors</relationshipLabel>
        <relationshipName>Contributors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member_Name__c</fullName>
        <formula>Team_Members__r.User__r.FirstName &amp;&quot; &quot;&amp;Team_Members__r.User__r.LastName</formula>
        <label>Team Member Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Members__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Members</label>
        <referenceTo>Core_Team_Member__c</referenceTo>
        <relationshipName>Contributors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contributor</label>
    <nameField>
        <displayFormat>Contributor-{0000000000}</displayFormat>
        <label>Contributor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contributors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Core_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contributor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contributor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Release_Name__c</fullName>
        <formula>Release_Role__r.Release_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <formula>Release_Role__r.Role_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Core_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>CTM-{0000000000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Release_Stage__c.object
<CustomObject>
    <label>Stage</label>
    <nameField>
        <displayFormat>S-{0000000000}</displayFormat>
        <label>Stage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Review__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <inlineHelpText>“0” means “Not Yet Scored”.  This is the default value and cannot be set by the user
“1” means “Major re-work required”
“2” means “Minor re-work required”
“3” means “Meets stage exit criteria”</inlineHelpText>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <formula>Role__r.Role_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Work_Element_Name__c</fullName>
        <formula>Stage_Work_Element__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Element Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Work_Element__c</fullName>
        <label>Work Element Id</label>
        <referenceTo>Stage_Work_Element__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member_Name__c</fullName>
        <formula>Team_Member__r.User__r.FirstName &amp;&quot; &quot;&amp;Team_Member__r.User__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team Member Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member Id</label>
        <referenceTo>Core_Team_Member__c</referenceTo>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review</label>
    <nameField>
        <displayFormat>Review-{0000000000}</displayFormat>
        <label>Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Stage_Work_Element__c.object
<CustomObject>
    <fields>
        <fullName>Contribute_Due_Date__c</fullName>
        <description>The Contribute Due Date formula calculates the data all contributions should be completed by</description>
        <formula>IF( Review_Required__c = TRUE,  Review_Due_Date__c -  Days_To_Review__c ,  Release_Stage_ID__r.Current_Baseline_End_Date__c - 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contribute Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Release_Name__c</fullName>
        <formula>Release_Stage_ID__r.Release_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release_Stage_ID__c</fullName>
        <label>Stage ID</label>
        <referenceTo>Release_Stage__c</referenceTo>
        <relationshipName>Stage_Work_Elements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Element_Name__c</fullName>
        <formula>Work_Element_ID__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Work Element Name</label>
        <type>Text</type>
    </fields>
    <label>Work Element</label>
    <nameField>
        <displayFormat>WE-{0000000000}</displayFormat>
        <label>Work Element ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ODP_ReviewContributeController.cls
public with sharing class ODP_ReviewContributeController 
{

    public LIST<Contributor__c> contributors {get;set;}
    public LIST<Review__c> deliverableReview{get;set;}
    
    public string UserId {get;set;}
    public boolean JustMyRecords {get;set;}
    
    public ODP_ReviewContributeController (){
        JustMyRecords = true;
        UserId = UserInfo.getUserId();
        doQuery();
    }
    
    private void doQuery()
    {
        string WhereThisUser = '';
        string queryString = '';
        
        // Contributors
        if ( JustMyRecords ) 
            {WhereThisUser = ' WHERE Team_Members__r.User__r.Id = \'' + UserId + '\' '; }
            else
            {WhereThisUser = ' WHERE Team_Members__c != null ';}
          queryString = 'SELECT id,name,Team_Member_Name__c,Role_Name__c,Completed__c,Stage_Work_Element_Name__c,Team_Members__r.User__r.Id,'+
                        'Stage_Work_Element__r.Work_Element_Name__c,Stage_Work_Element__r.Release_Stage_ID__r.Release_Name__c,Stage_Work_Element__r.Contribute_Due_Date__c from Contributor__c '+
                        WhereThisUser + 
                        ' ORDER BY CreatedDate';
                     system.debug('%%%%%%%%%%%%%%%%%%%%%%%%%%'+queryString );
          contributors = Database.Query(queryString );

       
        // Reviews
        if ( JustMyRecords ) 
            {WhereThisUser = ' WHERE Team_Member__r.User__r.Id = \'' + UserId + '\' '; }
            else
            {WhereThisUser = ' WHERE Team_Member__c != null ';}   
            queryString = 'SELECT id, name, Team_Member_Name__c,Comment__c,Role_Name__c,Complete__c,Stage_Work_Element_Name__c,Rating__c,'+
                        'Stage_Work_Element__r.Work_Element_Name__c,Stage_Work_Element__r.Release_Stage_ID__r.Release_Name__c,Stage_Work_Element__r.Contribute_Due_Date__c  from Review__c' +
                        WhereThisUser + 
                        ' ORDER BY CreatedDate';                            
          deliverableReview = Database.Query(queryString );
    }
    
    public PageReference MyRecords() {
        JustMyRecords = true;
        doQuery();
        return null;
    }
    public PageReference AllRecords() {
        JustMyRecords = false;
        system.debug('Sree: in All records');
        doQuery();
        return null;
    }

}