objects/Core_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Release_Name__c</fullName>
        <formula>Release_Role__r.Release_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <formula>Release_Role__r.Role_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Core_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>CTM-{0000000000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Commitment__c.object
<CustomObject>
    <fields>
        <fullName>Commitment_Description__c</fullName>
        <label>Commitment Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Commitment_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Commitment Owner</label>
        <referenceTo>Core_Team_Member__c</referenceTo>
        <relationshipLabel>Customer Commitment</relationshipLabel>
        <relationshipName>Customer_Commitment</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <label>Project ID</label>
        <referenceTo>Offering_Release__c</referenceTo>
        <relationshipLabel>Customer Commitment</relationshipLabel>
        <relationshipName>Customer_Commitment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Commitment</label>
    <nameField>
        <displayFormat>CC-{0000000000}</displayFormat>
        <label>Customer Commitment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Commitment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Offering_Release__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Opportunity Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>OPP-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ODP_Extension_CustomerCommitment.cls
public class ODP_Extension_CustomerCommitment {
    public string myEditStates {get;set;}
    public string UserID {get;set;}
    public Customer_Commitment__c cuscomObj{get;set;}
    public List<Core_team_member__c> ctmList{get;set;}
    public string retURL {get;set;}
    public string CurObjID{get;set;}
    public string OfId{get;set;}
    public ODP_Extension_CustomerCommitment(ApexPages.StandardController controller) {
        cuscomObj = (Customer_Commitment__c )controller.getRecord();
        CurObjID = ApexPages.currentPage().getParameters().get('id');
        retURL = ApexPages.currentPage().getParameters().get('retURL');
        OfId=  ApexPages.currentPage().getParameters().get('OFId');   
        if(CurObjID  == null){
            myEditStates = 'Create';
            if(string.isNotEmpty(OfId)){
                //retURL =  ApexPages.currentPage().getParameters().get('retURL').substring(1);
                cuscomObj.Project_ID__c = OfId;
                Offering_Release__c proOBJ = [select id, Name__c from offering_release__c where id=: OfId];
                ctmList = [select id, Role_Name__c, User__c,User__r.Id,  User__r.Last_First_Name__c, Release_Name__c from Core_team_member__c where Release_Name__c =: proOBJ.Name__c];    
            }
        }
        else{
            myEditStates = 'Update';
            cuscomObj = [SELECT id, 
                            Commitment_Description__c,
                            Commitment_Owner__c,
                            Customer_Name__c,
                            Due_Date__c,
                            Project_ID__c
                         FROM Customer_Commitment__c 
                         WHERE id =: cuscomObj.id 
                        ];
            Offering_Release__c proOBJ = [select id, Name__c from offering_release__c where id=: cuscomObj.Project_ID__c];
            ctmList = [select id, Role_Name__c, User__c,User__r.Id,  User__r.Last_First_Name__c, Release_Name__c from Core_team_member__c where Release_Name__c =: proOBJ.Name__c];            
        }
    }
    

     public List<SelectOption> CTMName{
      get{
            List<SelectOption> options = new List<SelectOption>();
            if(ctmList != null){             
            for(core_team_member__c ctmobj:ctmList){
              options.add(new SelectOption(ctmobj.id,ctmobj.User__r.Last_First_Name__c + ' | ' + ctmobj.Role_Name__c));                           
            }
            }
            return options;
         }
    }
    
    private string saveData(){
        try{
            upsert cuscomObj;
            return 'success';
        }
        catch(exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Operation Failed: saving data exception. Please contact IT administrators if any assistance needed.'));
            return 'failed';   
        }
    }
    public PageReference Save(){
        string saveflag = saveData();
        if(saveflag == 'success')
        {
            PageReference CUSCOMPage = new PageReference('/'+OfId);
            CUSCOMPage.setRedirect(true);
            return CUSCOMPage;
        }
        else
        {
            return null;
        }
    }


}