objects/Deal_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Master-detail relation with Opportunity object</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal Registrations</relationshipLabel>
        <relationshipName>Deal_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Product_Registration_Approved_count__c</fullName>
        <label>Product Registration Approved count</label>
        <summaryFilterItems>
            <field>Product_Registration__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>Product_Registration__c.Deal_Registration__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal Registration</label>
    <nameField>
        <label>Deal Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Registration__c.object
<CustomObject>
    <description>Created to show the Product Lines associated to a Deal as a Realted List under Deal Registration view.</description>
    <fields>
        <fullName>Deal_Registration__c</fullName>
        <label>Deal Registration</label>
        <referenceTo>Deal_Registration__c</referenceTo>
        <relationshipLabel>Product Registrations</relationshipLabel>
        <relationshipName>Product_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product Registrations</relationshipLabel>
        <relationshipName>Product_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Changed the Label name from Status to Deal Registration Status as per the request DMCR: 3803</description>
        <label>Deal Registration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product Registration</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityProductTriggerController.cls
/**
  * @author: HP
  * HP Release 
  * This class drives the logic for DealRegOpportunityLineItemBeforeDelete trigger.
  * Date: 19/08/2013
  */
public with sharing class OpportunityProductTriggerController {
    /*
     * @Description: Method to control delete Logic for Product Registration records.
     * @Param: List<OpportunityLineItem> oliList
     */
    public Pagereference controlDeleteProdReg(List<OpportunityLineItem> oliList){
        List<Id> oppIdList = new List<Id>();
        List<String> prodLineList= new List<String>();
        List<Product_Registration__c> productRegList = new List<Product_Registration__c>();
        List<Product_Registration__c> productRegdelList = new List<Product_Registration__c>();
        Map<String, Product_Registration__c> progRegMap= new Map<String, Product_Registration__c>();
        
        for(OpportunityLineItem oli: oliList){
            oppIdList.add(oli.OpportunityId);
            prodLineList.add(oli.Product_Line__c);
        }
        productRegList =[select status__c,Product_Line__c ,opportunity__r.Name, Deal_Registration__r.Product_Registration_Approved_count__c, id from Product_Registration__c where Opportunity__c IN: oppIdList and Opportunity__r.Deal_Registration_Status__c IN( 'Open', 'approved','rejected') and Product_Line__c IN :prodLineList];
        for(Product_Registration__c progReg: productRegList ){
            progRegMap.put(progReg.Product_Line__c,progReg);
        }
        for(OpportunityLineItem oli: oliList){
            if(progRegMap.ContainsKey(oli.Product_Line__c)){
                if(progRegMap.get(oli.Product_Line__c).Deal_Registration__r.Product_Registration_Approved_count__c==1 && progRegMap.get(oli.Product_Line__c).status__c=='Approved'){
                    oli.addError('Selected Product cannot be deleted as corresponding Product Registration is the only approved record in Deal Registration.');
                }
                else{
                    productRegdelList.add(progRegMap.get(oli.Product_Line__c));
                }
            }
        }
        try{
            Delete productRegdelList;
        }
        catch(DMLException ex){
            system.debug('***Error occurred while deleting***');
        }
        return null;
    }
}