objects/EngineFields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>OAE</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EngineFields</label>
</CustomObject>

objects/RuleScenario__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RuleObjectInternal__c</fullName>
        <description>getName() schema for the getLabel() selected in ruleObject picklist</description>
        <label>RuleObjectInternal</label>
        <length>63</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RuleObject__c</fullName>
        <label>RuleObject</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Object With A Long Name</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X10__c</fullName>
        <label>10</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X1__c</fullName>
        <label>1</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X2__c</fullName>
        <label>2</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3__c</fullName>
        <label>3</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X4__c</fullName>
        <label>4</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X5__c</fullName>
        <label>5</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X6__c</fullName>
        <label>6</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X7__c</fullName>
        <label>7</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X8__c</fullName>
        <label>8</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X9__c</fullName>
        <label>9</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>RuleScenario</label>
    <nameField>
        <label>RuleScenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RuleScenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OAE_RS_ViewExt.cls
public with sharing class OAE_RS_ViewExt {
    private RuleScenario__c thisRS;
    public String[] ruleLabels; 
    private Boolean[] showMe;
    
    public OAE_RS_ViewExt(ApexPages.StandardController stdC) {
        thisRS = (RuleScenario__c)stdC.getRecord();
        thisRS = [Select id, x1__c, x2__c, x3__c, x4__c, x5__c, x6__c, x7__c, x8__c, x9__c, x10__c,
        	RuleObject__c, RuleObjectInternal__c
//        	RuleObject__c
            From RuleScenario__c where id =:thisRS.ID];

        showMe = new Boolean[10];
        for (Integer i = 0; i < 10; i++) showMe[i] = false;

        ruleLabels = new String[10];
        for (Integer i = 0; i < 10; i++) ruleLabels[i] = '';

        //get current from custom settings
        Map<String,EngineFields__c> fNames = EngineFields__c.getAll();
        for (EngineFields__c ef : fNames.values()) {
			if(ef.object__c == thisRS.RuleObjectInternal__c) {
//			if(ef.object__c == thisRS.RuleObject__c) {
	            Integer z = ef.Order__c.intValue();
	            showMe[z-1] = true;
	            ruleLabels[z-1] = ef.Label__c;
			}
        }
    }

    private String getList(Integer i) {
        return ruleLabels[i-1];
    }
    
    private Boolean getShow(Integer i) {
        return showMe[i-1];
    }
    
    public String getList1() { return getList(1); }
    public String getList2() { return getList(2); }
    public String getList3() { return getList(3); }
    public String getList4() { return getList(4); }
    public String getList5() { return getList(5); }
    public String getList6() { return getList(6); }
    public String getList7() { return getList(7); }
    public String getList8() { return getList(8); }
    public String getList9() { return getList(9); }
    public String getList10() { return getList(10); }

    public Boolean getShow1() { return getShow(1); }
    public Boolean getShow2() { return getShow(2); }
    public Boolean getShow3() { return getShow(3); }
    public Boolean getShow4() { return getShow(4); }
    public Boolean getShow5() { return getShow(5); }
    public Boolean getShow6() { return getShow(6); }
    public Boolean getShow7() { return getShow(7); }
    public Boolean getShow8() { return getShow(8); }
    public Boolean getShow9() { return getShow(9); }
    public Boolean getShow10() { return getShow(10); }
}