objects/Extended_Profile_Category__c.object
<CustomObject>
    <label>Extended Profile Category</label>
    <nameField>
        <label>Extended Profile Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Extended Profile Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Extended_Profile_Category_Item__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Effective Date of an Extended Profile Category Item. The Item has validity starting from this Date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <description>Expiry Date of an Extended Profile Category Item. The Item has validity up to this Date.</description>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extended_Profile_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Extended Profile Category reference to a parent Extended Profile Category object&apos;s record.</description>
        <label>Extended Profile Category</label>
        <referenceTo>Extended_Profile_Category__c</referenceTo>
        <relationshipLabel>Extended Profile Category Items</relationshipLabel>
        <relationshipName>Extended_Profile_Category_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Extended Profile Category Item status. Values not known and not boundable to a local picklist.</description>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Extended Profile Category Item</label>
    <nameField>
        <label>Extended Profile Category Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Extended Profile Category Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Extended_Profile_Category_Item_Asgn__c.object
<CustomObject>
    <description>This object supports the relationship between an Extended Profile Category leaf item and an Extended Profile Item.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record. As per MDCP Data Model, this custom objects implements an intersection between an Extended Profile Category Item and an Account record of type Organization or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Extended Profile Category Item Asgns</relationshipLabel>
        <relationshipName>ExtendProfileItemJunction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Effective Date of an Extended ProfileCategory  Item Assignment. The assignment has validity starting from this Date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <description>Expity Date of an Extended ProfileCategory  Item Assignment. The assignment has validity up to this Date.</description>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extended_Profile_Category_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Extended Profile Category Item. Item reference to a parent Extended Profile Category Item object&apos;s record.</description>
        <label>Extended Profile Category Item</label>
        <referenceTo>Extended_Profile_Category_Item__c</referenceTo>
        <relationshipLabel>Extended Profile Category Item Asgns</relationshipLabel>
        <relationshipName>ExtendProfileItemJunction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Business_Area_Group__c</fullName>
        <description>Item&apos;s Business Area Group retrieved from a parent Extended Profile Category Item object&apos;s record.</description>
        <formula>Extended_Profile_Category_Item__r.Business_Area_Group__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Business Area Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <description>Item&apos;s Type retrieved from a parent Extended Profile Category Item object&apos;s record.</description>
        <formula>Extended_Profile_Category_Item__r.Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a Location object&apos;s record. As per MDCP Data Model, this custom objects implements an intersection between an Extended Profile Category Item and a Location record.</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Extended Profile Category Item Asgns</relationshipLabel>
        <relationshipName>ExtendProfileItemJunction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Extended Profile Category Item Assignment status. Values not known and not boundable to a local picklist.</description>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Extended Profile Category Item Asgn</label>
    <nameField>
        <displayFormat>EPCIA-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Extended Profile Category Item Asgns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/JBP__c.object
<CustomObject>
    <fields>
        <fullName>BG__c</fullName>
        <inlineHelpText>The name of the HP business group responsible for the plan.</inlineHelpText>
        <label>Business Group</label>
        <picklist>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Profile Locator ID</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Joint Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Joint Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Joint Business Plan</label>
    <nameField>
        <label>Partner Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Joint Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JointPlanSpclController.cls
/**
 * Class Name: JointPlanSpclController 
 * Author: HP
 * Date: 27-Mar-2013 
 * Requirement # Request Id: 5357
 * Description: To check if there are Program product Association records, if exists should not allow to change the All product eligible to true
 */
public with sharing class JointPlanSpclController {

    public string mainAcctID{get;set;}
    public string PlanBG {get;set;}

    /* Constructer */
    public JointPlanSpclController(ApexPages.StandardController std)
    {  
        mainAcctID = [select Partner_Account__c from JBP__c where id = :std.getId()].Partner_Account__c;
        PlanBG  = [select BG__c from JBP__c where id = :std.getId()].BG__c;
    }
    /**
     * @description: To return the List of Extended Profile Category Item
     * @return: List of Extended profile category Item Asgn records
     * 
     */
    public list<Extended_Profile_Category_Item_Asgn__c> getspclList(){
       return  [Select Item_Type__c,Location__r.Name,Item_Business_Area_Group__c,Extended_Profile_Category_Item__r.Name,Name,Effective_Date__c,Expiry_Date__c, Status__c, Extended_Profile_Category_Item__r.Extended_Profile_Category__c 
                 From Extended_Profile_Category_Item_Asgn__c 
                 where Account__c =:mainAcctID and Effective_Date__c<=TODAY and (Expiry_Date__c>=TODAY or Expiry_Date__c = Null)
                 and Status__c LIKE:'%'+ 'Assigned' +'%' and ((Item_Type__c =: Label.Specialisation and (Item_Business_Area_Group__c LIKE :'%'+PlanBG+'%'or Item_Business_Area_Group__c=: Label.Pan_HP)) or (Extended_Profile_Category_Item__r.Extended_Profile_Category__r.Name=: Label.Partner_Membership_PartnerOne and (Item_Business_Area_Group__c LIKE:'%'+PlanBG+'%' or Item_Business_Area_Group__c=: Label.Pan_HP)))
                 Order By Item_Type__c,Item_Business_Area_Group__c];
    }   
}