objects/Flight_Plan__c.object
<CustomObject>
    <description>Object to create a template for flight plan</description>
    <fields>
        <fullName>Name__c</fullName>
        <description>The Name Text is a word or combination of words by
which a Flight Plan is called</description>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Flight Plan</label>
    <nameField>
        <displayFormat>FP-{0000000000}</displayFormat>
        <label>Flight Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Offering_Release__c.object
<CustomObject>
    <fields>
        <fullName>Flight_Plan_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flight Plan ID</label>
        <referenceTo>Flight_Plan__c</referenceTo>
        <relationshipName>Offering_Release</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Opportunity Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>OPP-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ODP_Extension_VisualAdminConsoleNing.cls
public class ODP_Extension_VisualAdminConsoleNing {
    public List<Flight_Plan__c> FPS{get;set;}
    public ODP_Extension_VisualAdminConsoleNing(ApexPages.StandardController controller) {
        AggregateResult[] aggr = [select count(id) cc,Flight_Plan_ID__c from Offering_Release__c group by Flight_Plan_ID__c order by count(id) desc limit 6];
        List<string> ids = new List<string>();
        for(AggregateResult ar:aggr){
            ids.add(String.valueOf(ar.get('Flight_Plan_ID__c')));
        }
        FPS = [select id,Name__c from Flight_Plan__c where id in :ids];
    }

}