objects/GBU_Specialization_Plans__c.object
<CustomObject>
    <description>This Object stores all metrics for Busines Groups and Global Business Units.</description>
    <fields>
        <fullName>Business_Group__c</fullName>
        <inlineHelpText>The name of the HP business group responsible for the plan.</inlineHelpText>
        <label>Business Group</label>
        <picklist>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GBU_Specialization__c</fullName>
        <inlineHelpText>HP Global Business Unit. For example, ‘Printing’ is a PPS GBU, ‘BCS’ is a EG GBU, and Vertica is a SW GBU.  This is the level at which the metrics are planned.</inlineHelpText>
        <label>Global Business Unit</label>
        <picklist>
            <controllingField>Business_Group__c</controllingField>
            <picklistValues>
                <fullName>Mobility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virtualization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workstation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LaserJet Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ink Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business PCs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Notebooks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workstations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Commercial Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thin Clients</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other PSG Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphics Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inkjet and Printing Solutions (hardware only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LaserJet &amp; Enterprise Solutions (hardware only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software and Web Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other IPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS - Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS - Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autonomy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <label>Joint Business Plan</label>
        <referenceTo>JBP__c</referenceTo>
        <relationshipName>GBU_Plans1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sub-Plan</label>
    <nameField>
        <displayFormat>SP - {0000}</displayFormat>
        <label>Sub-Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub-Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/JBP__c.object
<CustomObject>
    <fields>
        <fullName>BG__c</fullName>
        <inlineHelpText>The name of the HP business group responsible for the plan.</inlineHelpText>
        <label>Business Group</label>
        <picklist>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Joint Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_End_Date__c</fullName>
        <inlineHelpText>Date the plan ends, typically on the last day of HP&apos;s fiscal year, October 31st.</inlineHelpText>
        <label>Plan End Date</label>
        <type>Date</type>
    </fields>
    <label>Joint Business Plan</label>
    <nameField>
        <label>Partner Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Joint Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SubPlan_TriggerControllerTest.cls
@isTest
Public class SubPlan_TriggerControllerTest{

     Static Account accRec = new Account();
     Static JBP__c jbp = new JBP__c();
     Static GBU_Specialization_Plans__c suPlan1 = new GBU_Specialization_Plans__c();
     Static GBU_Specialization_Plans__c suPlan2 = new GBU_Specialization_Plans__c();
     public static testMethod void testBeforeInsert() {
        Test.startTest();
        /* Create a test Account */        
        accRec = TestingSetupDataUtil.createAccount('Testing Account','testing@test.com','Partner');
        insert accRec;
        
         /*Create a JBP */
        jbp.Name = 'Test_SubPlan_TriggerControllerTest';
        jbp.BG__c = 'PPS';
        jbp.Partner_Account__c = accRec.id;
        jbp.Plan_End_Date__c = date.valueof('2014-08-14');
        insert jbp;
        
        /* Create Sub plans */
        List<GBU_Specialization_Plans__c> suPlanList = new List<GBU_Specialization_Plans__c>();
        suPlan1.GBU_Specialization__c = 'Supplies';
        suPlan1.Business_Group__c = 'PPS';
        suPlan1.Joint_Business_Plan__c = jbp.id;
        suPlan2.GBU_Specialization__c = 'Printing';
        suPlan2.Business_Group__c = 'PPS';
        suPlan2.Joint_Business_Plan__c = jbp.id;        
        suPlanList.add(suPlan1);
        suPlanList.add(suPlan2);
        insert suPlanList;
        suPlan1.GBU_Specialization__c = 'Computing';
        update suPlan1;
        Test.stopTest();
    }
}