objects/GBU_Specialization_Plans__c.object
<CustomObject>
    <description>This Object stores all metrics for Busines Groups and Global Business Units.</description>
    <fields>
        <fullName>Business_Group__c</fullName>
        <inlineHelpText>The name of the HP business group responsible for the plan.</inlineHelpText>
        <label>Business Group</label>
        <picklist>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GBU_Specialization__c</fullName>
        <inlineHelpText>HP Global Business Unit. For example, ‘Printing’ is a PPS GBU, ‘BCS’ is a EG GBU, and Vertica is a SW GBU.  This is the level at which the metrics are planned.</inlineHelpText>
        <label>Global Business Unit</label>
        <picklist>
            <controllingField>Business_Group__c</controllingField>
            <picklistValues>
                <fullName>Mobility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virtualization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workstation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LaserJet Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ink Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business PCs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Notebooks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workstations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Commercial Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thin Clients</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other PSG Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graphics Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inkjet and Printing Solutions (hardware only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LaserJet &amp; Enterprise Solutions (hardware only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software and Web Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other IPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS - Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TS - Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autonomy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <label>Joint Business Plan</label>
        <referenceTo>JBP__c</referenceTo>
        <relationshipName>GBU_Plans1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sub-Plan</label>
    <nameField>
        <displayFormat>SP - {0000}</displayFormat>
        <label>Sub-Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub-Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/JBP__c.object
<CustomObject>
    <fields>
        <fullName>BG__c</fullName>
        <inlineHelpText>The name of the HP business group responsible for the plan.</inlineHelpText>
        <label>Business Group</label>
        <picklist>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PPT_Export_Currency__c</fullName>
        <inlineHelpText>The currency defaulted for the PowerPoint export.</inlineHelpText>
        <label>PPT Export Default Currency</label>
        <picklist>
            <picklistValues>
                <fullName>USD</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HKD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ILS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MXN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MYR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PKR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SGD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TWD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PPT_Export_Language__c</fullName>
        <description>PPT Export Default Language</description>
        <inlineHelpText>The language defaulted for the PowerPoint export.</inlineHelpText>
        <label>PPT Export Default Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese (Simplified)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese (Brazilian)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish (Latin America/Mexico)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Joint Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_End_Date__c</fullName>
        <inlineHelpText>Date the plan ends, typically on the last day of HP&apos;s fiscal year, October 31st.</inlineHelpText>
        <label>Plan End Date</label>
        <type>Date</type>
    </fields>
    <label>Joint Business Plan</label>
    <nameField>
        <label>Partner Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Joint Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Metrics__c.object
<CustomObject>
    <fields>
        <fullName>BG__c</fullName>
        <inlineHelpText>The name of the HP business group responsible for the plan.</inlineHelpText>
        <label>Business Group</label>
        <picklist>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GbuSpecializationPlan__c</fullName>
        <inlineHelpText>The associated sub-plan for the metric.</inlineHelpText>
        <label>Sub Plan</label>
        <referenceTo>GBU_Specialization_Plans__c</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Metrics</label>
    <nameField>
        <displayFormat>M - {0000}</displayFormat>
        <label>Metrics ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <recordTypes>
        <fullName>Attach</fullName>
        <active>true</active>
        <description>Complementary products/services sold with a primary product/service – measured as a ratio of complementary units to primary units.  Note: different BGs may use a different calculation</description>
        <label>Attach %</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JBP_MetricsBeforeInsertTest.cls
/**********************************************************
* Class Name: JBP_MetricsBeforeInsertTest
* Author: HP 
* Date: 06-May-20123
* Description: This class contains the test code coverage for the class "JBP_MetricsBeforeInsertController"
***********************************************************/
@isTest(seeAllData = true)
private class JBP_MetricsBeforeInsertTest{
    static testMethod void testJBP_MetricsBeforeInsert(){
    Id recordId=schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
        Account newAccount=new Account(Name='TestAccountForTestClass',RecordTypeId=recordId,ShippingCountry='India',ShippingPostalCode='234562345',ShippingState='Karnataka123',ShippingStreet='Esomecity');
        insert newAccount;
        newAccount.IsPartner=true;
        update newAccount;
        
        JBP__c testJBP = new JBP__c();
        testJBP.name = 'Test JBP123456';
        testJBP.Partner_Account__c = newAccount.ID;
        testJBP.BG__c = 'HPFS';
        testJBP.PPT_Export_Currency__c='USD';
        testJBP.PPT_Export_Language__c='English';
        testJBP.Plan_End_Date__c=system.today()+20;
        insert testJBP;
        
        GBU_Specialization_Plans__c subPlan = new GBU_Specialization_Plans__c();
        subPlan.Business_Group__c='HPFS';
        subplan.GBU_Specialization__c='HPFS';
        subplan.Joint_Business_Plan__c=testJBP.id;
        insert subPlan;
        
        Metrics__c met = new metrics__c();
        met.BG__c = 'HPFS';
        met.recordTypeId = schema.SObjectType.metrics__c.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        met.GbuSpecializationPlan__c = subPlan.id;
        insert met;
        
       // test.startTest();
       try{
            Metrics__c met1 = new metrics__c();
            met1 .BG__c = 'HPFS';
            met1 .recordTypeId = schema.SObjectType.metrics__c.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
            met1 .GbuSpecializationPlan__c = subPlan.id;
            insert met1;
            
            Metrics__c met2 = new metrics__c();
            met2 .BG__c = 'HPFS';
            met2 .recordTypeId = schema.SObjectType.metrics__c.getRecordTypeInfosByName().get('Attach %').getRecordTypeId();
            met2 .GbuSpecializationPlan__c = subPlan.id;
            //insert met2;
            Metrics__c met3 = new metrics__c();
            met3 .BG__c = 'HPFS';
            met3 .recordTypeId = schema.SObjectType.metrics__c.getRecordTypeInfosByName().get('Attach %').getRecordTypeId();
            met3 .GbuSpecializationPlan__c = subPlan.id;
            //insert met3;
            list<metrics__c> metriclist = new list<metrics__c>();
            metricList.add(met2);
            metricList.add(met3);
            insert metricList;
        }catch(exception e){
            system.debug('the exception is '+ e.getMessage());
        }
       try{
            Metrics__c met11 = new metrics__c();
            met11.BG__c = 'HPFS';
            met11.recordTypeId = schema.SObjectType.metrics__c.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
            met11.GbuSpecializationPlan__c = subPlan.id;
            //insert met11;
            
            Metrics__c met21 = new metrics__c();
            met21.BG__c = 'HPFS';
            met21.recordTypeId = schema.SObjectType.metrics__c.getRecordTypeInfosByName().get('Attach %').getRecordTypeId();
            met21.GbuSpecializationPlan__c = subPlan.id;
            //insert met21;
            Metrics__c met31 = new metrics__c();
            met31.BG__c = 'HPFS';
            met31.recordTypeId = schema.SObjectType.metrics__c.getRecordTypeInfosByName().get('Attach %').getRecordTypeId();
            met31.GbuSpecializationPlan__c = subPlan.id;
            //insert met3;
            list<metrics__c> metriclist1 = new list<metrics__c>();
            metricList1.add(met11);
            metricList1.add(met21);
            metricList1.add(met31);
            JBP_MetricsBeforeInsertController.avoidDuplicateRecord(metriclist1);
        }catch(exception e){
            system.debug('the exception is '+ e.getMessage());
        }
       // test.stopTest();
     }
}