objects/HP_Quote__c.object
<CustomObject>
    <description>Custom quote object to capture quotes from Quote IDS and to support future integration with CPQ tools</description>
    <fields>
        <fullName>BMI_ID__c</fullName>
        <externalId>true</externalId>
        <label>BMI ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>HP Quote</label>
    <nameField>
        <label>HP Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CPQOpenBMIDocumentURLController.cls
public class CPQOpenBMIDocumentURLController {
    public HP_Quote__c objHPQuote;
    public string BMIEditPage{set;get;}
    public CPQOpenBMIDocumentURLController(ApexPages.StandardController controller) {
        objHPQuote = (HP_Quote__c)controller.getRecord();
        BigMachines__Quote__c objBMIQuote = [Select id from BigMachines__Quote__c where Name=:objHPQuote.BMI_ID__c limit 1];
        BMIEditPage = '/apex/BigMachines__QuoteEdit?retURL=%2F'+objHPQuote.Id+'&scontrolCaching=1&sfdc.override=1&id='+objBMIQuote.Id;
    }
}