objects/HPMenu__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ShortDescription__c</fullName>
        <label>Short Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SubMenu__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Menu Of</label>
        <referenceTo>HPMenu__c</referenceTo>
        <relationshipLabel>HPMenu</relationshipLabel>
        <relationshipName>HPMenu</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HP Menu</label>
    <nameField>
        <label>HPMenu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HPMenu</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/hpdcAuthenticatedMenuDetailsTracker.cls
@isTest
private class hpdcAuthenticatedMenuDetailsTracker{

    static HPMenu__c objMenu;
    static testMethod void firstMethod() {
        
        loadData();
        
        ApexPages.currentPage().getParameters().put('menu','mainMenu');
        ApexPages.currentPage().getParameters().put('tab','subMenu');
        hpdcAuthenticatedMenuDetailsController ob = new hpdcAuthenticatedMenuDetailsController();
        
    }
    
    static void loadData(){
        
        insertMainMenu();
        insertSubMenu();
    }
    
    static void insertMainMenu(){
    
        objMenu = new HPMenu__c();
        objMenu.Name = 'mainMenu';
        objMenu.Active__c = true;
        objMenu.Description__c = 'test';
        objMenu.ShortDescription__c = 'test';
        insert objMenu;        
    }
    
    static void insertSubMenu(){
    
        HPMenu__c objSubMenu = new HPMenu__c();
        objSubMenu.Name = 'subMenu';
        objSubMenu.Active__c = true;
        objSubMenu.Description__c = 'test';
        objSubMenu.ShortDescription__c = 'test';
        objSubMenu.SubMenu__c = objMenu.Id;
        insert objSubMenu;        
    }
}