objects/JBP__c.object
<CustomObject>
    <fields>
        <fullName>BG__c</fullName>
        <inlineHelpText>The name of the HP business group responsible for the plan.</inlineHelpText>
        <label>Business Group</label>
        <picklist>
            <picklistValues>
                <fullName>EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PPT_Export_Currency__c</fullName>
        <inlineHelpText>The currency defaulted for the PowerPoint export.</inlineHelpText>
        <label>PPT Export Default Currency</label>
        <picklist>
            <picklistValues>
                <fullName>USD</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HKD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ILS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MXN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MYR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PKR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SGD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TWD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PPT_Export_Language__c</fullName>
        <description>PPT Export Default Language</description>
        <inlineHelpText>The language defaulted for the PowerPoint export.</inlineHelpText>
        <label>PPT Export Default Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese (Simplified)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese (Brazilian)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish (Latin America/Mexico)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Joint Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_End_Date__c</fullName>
        <inlineHelpText>Date the plan ends, typically on the last day of HP&apos;s fiscal year, October 31st.</inlineHelpText>
        <label>Plan End Date</label>
        <type>Date</type>
    </fields>
    <label>Joint Business Plan</label>
    <nameField>
        <label>Partner Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Joint Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PPT_Currency_Symbol__c.object
<CustomObject>
    <fields>
        <fullName>PPT_Currency_Code_Key__c</fullName>
        <description>PPT Currency Code is the value and the key is &apos;PPT Currency Code key&apos; is used as a key for drop down list.Example for simplified, traditional Chinese and Russian the values are different</description>
        <label>PPT Currency Code Key</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PPT_Currency_Code__c</fullName>
        <label>PPT Currency Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PPT_Display_Code__c</fullName>
        <label>PPT Display Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PPT Currency Symbol</label>
    <nameField>
        <label>PPT Currency Symbol</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPT Currency Symbols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PPT_Language__c.object
<CustomObject>
    <fields>
        <fullName>PPT_Display_Language__c</fullName>
        <label>PPT Display Language</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PPT_Language_Code__c</fullName>
        <label>PPT Language Code</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PPT Language</label>
    <nameField>
        <label>PPT Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPT Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PPT_Usage_Metric__c.object
<CustomObject>
    <description>PPT Export usage metrics</description>
    <fields>
        <fullName>UserEmailId__c</fullName>
        <description>User Email Address</description>
        <inlineHelpText>User Email Address</inlineHelpText>
        <label>UserEmailId</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PPT Usage Metric</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPT Usage Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JBPExstreamControllerTest.cls
/**********************************************************
* Class Name: JBPExstreamControllerTest 
* Author: HP
* Date: 09-May-2013 
* Description: This class does the test coverage for JBPExstreamController class. 
***********************************************************/

@isTest(SeeAllData=true)
private class JBPExstreamControllerTest {
     
private static testMethod void testJBP(){     
     date dtDate = date.today();
      String usersId =  UserInfo.getUserId();
      Account partAcc = new Account();
      partAcc = TestingSetupDataUtil.createAccount('JBPAccount', 'partnerJBP@hp.com','Partner');
      partAcc.Partner_Portal_Eligible__c = true;
      insert partAcc;
      JBP__c jbp= new JBP__c(Name='TestJbp', Partner_Account__c=partAcc.Id, BG__c='EG', PPT_Export_Currency__c='MZE', PPT_Export_Language__c='English',Plan_End_Date__c=dtDate);
      insert jbp;
      PPT_Language__c pptLanguage =new PPT_Language__c (Name='English',PPT_Display_Language__c='en',PPT_Language_Code__c='en');
      insert pptLanguage;
      
      PPT_Currency_Symbol__c pptCurrency=new PPT_Currency_Symbol__c (Name='MZE',PPT_Currency_Code__c='MZE',PPT_Currency_Code_Key__c='ABC',PPT_Display_Code__c='ABZ');
      insert pptCurrency;
     
      PPT_Usage_Metric__c pptUsageMetric=new PPT_Usage_Metric__c (Name='abc@hp.com',UserEmailId__c='abc@hp.com');
      insert pptUsageMetric;
      
      ApexPages.currentPage().getParameters().put('jbpId',jbp.id); 
      JBPExstreamController jbpExstreamControllerObject =new JBPExstreamController();
      jbpExstreamControllerObject.pptLanguage= 'English';
      jbpExstreamControllerObject.currencyCode = 'MZE';
      jbpExstreamControllerObject.success='true';
      
      Test.setMock(WebServiceMock.class, new JBPExstreamControllerImpl());
      List<SelectOption> languageList=  jbpExstreamControllerObject.getLanguage;
      List<SelectOption> currencyList=  jbpExstreamControllerObject.getCurrency;
      jbpExstreamControllerObject.insertUsageMetric(usersId);
      jbpExstreamControllerObject.invokeTibcoWsService();    
    }      
 }