objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>D &amp; B Domestic Name</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account Name)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authorized_Buyer__c</fullName>
        <description>Authorized Buyer</description>
        <label>Authorized Buyer</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <description>Yes/No Option in case there is no Budget.</description>
        <label>Budget</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Budget__c</fullName>
        <description>Value of Estimated Budget.  Multi Currency.</description>
        <inlineHelpText>Enter the amount of estimated budget if known</inlineHelpText>
        <label>Estimated Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Modified_by_Partner__c</fullName>
        <description>This field captures the time-stamp for any modification performed by the partner user.  It is used for the calculation of strike-count mechanism.</description>
        <label>Last Modified by Partner</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <description>Estimated Value of Lead</description>
        <label>Estimated Lead Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Timeframe_to_Buy_1__c</fullName>
        <description>Timeframe to Buy the product</description>
        <label>Timeframe to Buy</label>
        <picklist>
            <picklistValues>
                <fullName>&lt; 1 Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt; 1 Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - 3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - 6 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 - 12 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt; 1 Year</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Strike_Count_Track__c.object
<CustomObject>
    <description>This custom object is used to keep a track of all the leads and opportunities that are assigned to partners. It will be further leveraged to update the strike count on partner user and account.</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Strike_Count_Track</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Thirty_Day_SLA_Date__c</fullName>
        <description>This field provides the SLA date for 30-day SLA for lead, Opportunity. It handles recurring SLA date for each 30-day count by using Strike count date.</description>
        <formula>IF(  AND( NOT(  ISBLANK( Lead_Last_Modified_by_Partner__c ) ), NOT(  ISNULL( Lead_Last_Modified_by_Partner__c ) ) )  ,

IF( OR(  ISBLANK(  Strike_Increment_Date__c ), ISNULL(  Strike_Increment_Date__c ), DATEVALUE( Lead_Last_Modified_by_Partner__c) &gt;  Strike_Increment_Date__c   ),  DATEVALUE( Lead_Last_Modified_by_Partner__c) + 30 , Strike_Increment_Date__c + 30) , 

 IF( AND( NOT(  ISBLANK(  Opportunity_Last_Modified_by_Partner__c ) ), NOT(  ISNULL( Opportunity_Last_Modified_by_Partner__c ) ) ) ,

IF( OR(  ISBLANK(  Strike_Increment_Date__c ), ISNULL(  Strike_Increment_Date__c ), DATEVALUE( Opportunity_Last_Modified_by_Partner__c) &gt;   Strike_Increment_Date__c  ),  DATEVALUE( Opportunity_Last_Modified_by_Partner__c) + 30 , Strike_Increment_Date__c + 30) , 

NULL )   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>30 Day SLA Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Two_Day_SLA_Date__c</fullName>
        <label>2 Day SLA Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User_Assignment_Date__c</fullName>
        <label>User Assignment Date</label>
        <type>DateTime</type>
    </fields>
    <label>Demerit Count Track</label>
    <nameField>
        <displayFormat>SCT-{0}</displayFormat>
        <label>Demerit Count Track #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demerit Count Track</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PartnerStrikeCountBatchAndExecutorTest.cls
/***********************************************************
* Class Name: PartnerStrikeCountBatchAndExecutorTest
* Author: Accenture
* Date: 26-JULY-2012 
* Requirement # Request Id: 
* Description: This class does the test coverage for PartnerStrikeCountBatch And PartnerStrikeCountBatchExecutor classes
**********************************************************/

@isTest
private class PartnerStrikeCountBatchAndExecutorTest {
        
    //setup your test data in this method
    private static void setupData() {
        
        //Insert Lead
        Lead newLead = TestingSetupDataUtil.createLead('testClassLead', 'qqq123', 'Open', 'Accepted', '123', 't12est1@test.com');
      //  newLead.Account_Name__c = acc.Id;
        newLead.Budget__c = '121' ;
        newLead.Authorized_Buyer__c = 'No';
        newLead.Timeframe_to_Buy_1__c = '< 1 Week';
        newLead.Estimated_Budget__c = 123.0;
        newLead.Last_Modified_by_Partner__c = system.today().addDays(-30);
        insert newLead;
        
        Lead newLead1 = TestingSetupDataUtil.createLead('testClassLead', 'qqq123', 'open', 'Accepted', '123', 't12est1@test.com');
      //  newLead.Account_Name__c = acc.Id;
        newLead1.Budget__c = '121' ;
        newLead1.Authorized_Buyer__c = 'No';
        newLead1.Timeframe_to_Buy_1__c = '< 1 Week';
        newLead1.Estimated_Budget__c = 123.0;
        newLead1.Last_Modified_by_Partner__c = system.today().addDays(-35);
        insert newLead1;
        
        //creating a strike count instance
        Strike_Count_Track__c strikeCntTest = new Strike_Count_Track__c();
        strikeCntTest.User_Assignment_Date__c = system.today() -2;
        strikeCntTest.Two_Day_SLA_Date__c = system.today();
        strikeCntTest.Lead__c = newLead.id;
        insert strikeCntTest;        
       
        Strike_Count_Track__c strikeCntTest1 = new Strike_Count_Track__c();
        strikeCntTest1.User_Assignment_Date__c = system.today() -3;
        strikeCntTest1.Two_Day_SLA_Date__c = system.today();
        insert strikeCntTest1;
        
        Strike_Count_Track__c strikeCntTest2 = new Strike_Count_Track__c();
        strikeCntTest2.User_Assignment_Date__c = system.today() -4;
        strikeCntTest2.Lead__c = newLead.id;
        insert strikeCntTest2; 
        system.debug('the 30 day date is '+strikeCntTest2.Thirty_Day_SLA_Date__c ) ;    
        
        Strike_Count_Track__c strikeCntTest3 = new Strike_Count_Track__c();
        strikeCntTest3.User_Assignment_Date__c = system.today() -5;
        //strikeCntTest3.Thirty_Day_SLA_Date__c = system.today();
        insert strikeCntTest3;
        
         Strike_Count_Track__c strikeCntTest4 = new Strike_Count_Track__c();
        strikeCntTest4.User_Assignment_Date__c = system.today() -6;
        //strikeCntTest4.Thirty_Day_SLA_Date__c = system.today().addDays(5);
        insert strikeCntTest4;
        
         Strike_Count_Track__c strikeCntTest5 = new Strike_Count_Track__c();
        strikeCntTest5.User_Assignment_Date__c = system.today() -7;
        strikeCntTest5.lead__c = newLead1.id;
        insert strikeCntTest5;
        system.debug('the 30 + 5 days date is '+strikeCntTest5.Thirty_Day_SLA_Date__c);
     }
     
    //Method for Positive test
    private static testMethod void PositiveTest() {
        Test.startTest();        
        setupData();
        
        database.executeBatch(new PartnerStrikeCountBatch());
       
        //Creating an instance of the executor
        PartnerStrikeCountBatchExecutor SCTExecutorInstance = new PartnerStrikeCountBatchExecutor();
        
        datetime currentDateTime = datetime.now();
        String min = String.valueOf(math.mod((currentDateTime.minute() + 2),60));
        String schExp = '0 '+min+' * * * ? ';
        system.schedule('Strike Schedular Test:'+datetime.now(), schExp, SCTExecutorInstance);
     
                
        Test.stopTest();
    }  
   
}