objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>D &amp; B Domestic Name</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account Name)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authorized_Buyer__c</fullName>
        <description>Authorized Buyer</description>
        <label>Authorized Buyer</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <description>Yes/No Option in case there is no Budget.</description>
        <label>Budget</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Budget__c</fullName>
        <description>Value of Estimated Budget.  Multi Currency.</description>
        <inlineHelpText>Enter the amount of estimated budget if known</inlineHelpText>
        <label>Estimated Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <description>Estimated Value of Lead</description>
        <label>Estimated Lead Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Timeframe_to_Buy_1__c</fullName>
        <description>Timeframe to Buy the product</description>
        <label>Timeframe to Buy</label>
        <picklist>
            <picklistValues>
                <fullName>&lt; 1 Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt; 1 Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - 3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - 6 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 - 12 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt; 1 Year</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Portal_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Portal Eligible</label>
        <type>Checkbox</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Strike_Count_Track__c.object
<CustomObject>
    <description>This custom object is used to keep a track of all the leads and opportunities that are assigned to partners. It will be further leveraged to update the strike count on partner user and account.</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Strike_Count_Track</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Strike_Count_Track</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_Partner_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner - Partner User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Strike_Count_Track</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Strike_Count_Track</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Strike_Count_Track</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Strike Count Track</relationshipLabel>
        <relationshipName>Strike_Count_Track</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Lead_Owner_Id__c</fullName>
        <label>Previous Lead Owner Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Assignment_Date__c</fullName>
        <label>Queue Assignment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Two_Day_SLA_Date__c</fullName>
        <label>2 Day SLA Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User_Assignment_Date__c</fullName>
        <label>User Assignment Date</label>
        <type>DateTime</type>
    </fields>
    <label>Demerit Count Track</label>
    <nameField>
        <displayFormat>SCT-{0}</displayFormat>
        <label>Demerit Count Track #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demerit Count Track</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PartnerCollabUtilTest.cls
/***********************************************************
* Class Name: PartnerCollabUtilTest
* Author: Accenture
* Date: 26-JULY-2012 
* Requirement # Request Id: 
* Description: This class does the test coverage for PartnerCollabUtil class
***********************************************************/

@isTest
private class PartnerCollabUtilTest {
    private static Account partAcc = new Account();
    private static Account custAcc = new Account();
    private static Contact partContact = new Contact();
    private static Lead testlead = new Lead();
    private static Opportunity opptyTest = new Opportunity();
    private static User partUser111 = new User();
    private static Strike_Count_Track__c strikeCntTest;
    private static Strike_Count_Track__c strikeCntOpptyTest;
    private static Strike_Count_Track__c strikeCntQueueTest;
    private static list<strike_count_track__c> strikeCntTestList = new list<strike_count_track__c>(); 
    //private static List<RecordType> allrecTypes = new List<RecordType>();
    
    
    //setup your test data in this method
    private static void setupData() {
        
        // Create a account with record type - partner
        //partAcc = TestingSetupDataUtil.createAccount('Test Partner Account', 'partner@partnercollab.com','Partner');
        partAcc = TestingSetupDataUtil.createAccount('Test Partner Account', 'partner@apttus.com','Partner');
        insert partAcc;
        
        //Test Location Insertion
        Location__c partLoc=new Location__c(Name='33586574',Account__c=partAcc.Id);
        Insert partLoc;  
           
        // Create a account with record type - customer
        custAcc = TestingSetupDataUtil.createAccount('Test Account', 'custom@partnercollab.com','Customer');
        insert custAcc;
        
        //Enable the account as partner
        partAcc.IsPartner = true;
        partAcc.Partner_Portal_Eligible__c = true;
        partAcc.ShippingCountry = 'China';
        update partAcc;
        
        // Create a contact under the partner account
        partContact = TestingSetupDataUtil.createContact(partAcc.Id, 'Test Contact');
        insert partContact;
        
        // fetch the partner profiles
        List<Profile> partnerProfiles = new List<Profile>();
        partnerProfiles = [Select p.UserType, p.UserLicenseId, p.Name, p.Id From Profile p where p.UserType like '%Partner%' ];
        
        // Create a partner user
        partUser111 = TestingSetupDataUtil.createUser('par1Test','abcw1@hp.com','5_1_PMawbc1@testab.com','UTF-8','Tertlan','en_US','en_US','America/Los_Angeles','partnercoll@partnertest.com',String.valueOf(Math.random()).substring(0,15),partnerProfiles[0].Id );
        partUser111.ContactId = partContact.Id;
        insert partUser111;
        
        // create a lead
        testlead = TestingSetupDataUtil.createLead('TestLead2', 'qqq123', 'Qualified', 'Accepted', '123', 'abcw1@hp.com');
        testlead.Account_Name__c = custAcc.Id;
        testlead.Budget__c = '121' ;
        testlead.Authorized_Buyer__c = 'No';
        testlead.Timeframe_to_Buy_1__c = '< 1 Week';
        testlead.Estimated_Budget__c = 123.0;
        insert testlead;
        
        // Opportunity creation
        opptyTest = TestingSetupDataUtil.createOpportunity(string.valueOf(custAcc.id),'opptyTest', system.today()+ 30);
        opptyTest.Partner_acknowledged__c = false;
        opptyTest.Converted_by_Partner__c = false;
        opptyTest.OwnerId = partUser111.Id;
        opptyTest.Assigned_to_partner_date__c = system.today() - 1;
        insert opptyTest;
        
        strikeCntTest = new Strike_Count_Track__c();
        strikeCntTest.Two_Day_SLA_Date__c = system.today();
        strikeCntTest.User_Assignment_Date__c = system.today() - 2;
        strikeCntTest.Previous_Lead_Owner_Id__c = partUser111.Id;
        strikeCntTest.Partner_Contact__c = partContact.Id;
        strikeCntTest.Partner_Account__c = partAcc.Id;
        strikeCntTest.Partner_Location__c = partLoc.Id;
        strikeCntTest.Owner_Partner_User__c = partUser111.Id;
        strikeCntTest.Lead__c = testlead.Id;
        insert strikeCntTest;
        
        strikeCntOpptyTest = new Strike_Count_Track__c();
        strikeCntOpptyTest.User_Assignment_Date__c = system.today() - 2;
        strikeCntOpptyTest.Partner_Contact__c = partContact.Id;
        strikeCntOpptyTest.Partner_Account__c = partAcc.Id;
        strikeCntOpptyTest.Owner_Partner_User__c = partUser111.Id;
        strikeCntOpptyTest.Opportunity__c = opptyTest.Id;
        insert strikeCntOpptyTest;
        
        strikeCntQueueTest = new Strike_Count_Track__c();
        strikeCntQueueTest.Two_Day_SLA_Date__c = system.today();
        strikeCntQueueTest.Queue_Assignment_Date__c = system.today() - 2;
        strikeCntQueueTest.Previous_Lead_Owner_Id__c = UserInfo.getUserId();
        strikeCntQueueTest.Lead__c = testlead.Id;
        insert strikeCntQueueTest;
        
        strikeCntTestList.add(strikeCntTest);
        strikeCntTestList.add(strikeCntOpptyTest);
        strikeCntTestList.add(strikeCntQueueTest);      
        
        //allrecTypes = [Select SobjectType, Name, Id From RecordType limit 1]; 
                    
     }
     
    //Method for Positive test
    private static testMethod void StrikeTest() {
        Test.startTest();
        setupData();
        
       /* PartnerCollabUtil.emailTemplateNames = new List<String>{'Two_day_lead_update_failure_notification', 'Stale_Lead_notification', 'Opportunity_update_reminder'};
        //PartnerCollabUtil.getRecordTypeName(allrecTypes[0].Id);
        PartnerCollabUtil.isLoggedInPartnerUser();
        PartnerCollabUtil.participatingInPartnerHandling();
        
        PartnerCollabUtil.handleTwoDaySLAs(strikeCntTestList);
        PartnerCollabUtil.handleProactiveNotifications(strikeCntTestList);
        PartnerCollabUtil.handleThirtyDaySLAs(strikeCntTestList);
        PartnerCollabUtil.handleQueueOwnedLeadTracks(new List<Strike_Count_Track__c>{strikeCntQueueTest});
        PartnerCollabUtil.handlUserOwnedLeadTracks(strikeCntTestList);
        
        try{
        PartnerCollabUtil.sendNotifications();
        }catch(exception e){}
        PartnerCollabUtil.getStringFromDate(system.today());
        PartnerCollabUtil.incrementPartnerLocationStrike();
        PartnerCollabUtil.incrementPartnerUserStrike();
        PartnerCollabUtil.updateStrikeDate = strikeCntTestList;
        PartnerCollabUtil.updateStrikeIncrementDate();        
        PartnerCollabUtil.strCntsToDelete = strikeCntTestList;
        PartnerCollabUtil.deleteStrkRecords();*/
        
        PartnerCollabUtil.participatingInPartnerHandling();
        PartnerCollabUtil.handleTwoDaySLAs(strikeCntTestList);
        PartnerCollabUtil.handleQueueOwnedLeadTracks(new List<Strike_Count_Track__c>{strikeCntQueueTest});
        //PartnerCollabUtil.deleteStrkRecords();
        
        
        system.runAs(partUser111){
            PartnerCollabUtil.isLoggedInPartnerUser();
        }
        
        Test.stopTest();
    }
    
}