objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>D &amp; B Domestic Name</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account Name)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authorized_Buyer__c</fullName>
        <description>Authorized Buyer</description>
        <label>Authorized Buyer</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <description>Yes/No Option in case there is no Budget.</description>
        <label>Budget</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Budget__c</fullName>
        <description>Value of Estimated Budget.  Multi Currency.</description>
        <inlineHelpText>Enter the amount of estimated budget if known</inlineHelpText>
        <label>Estimated Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Partner_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDC R2.0_07/23/2012: New field is created as per the requirement #</description>
        <label>Partner Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Timeframe_to_Buy_1__c</fullName>
        <description>Timeframe to Buy the product</description>
        <label>Timeframe to Buy</label>
        <picklist>
            <picklistValues>
                <fullName>&lt; 1 Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt; 1 Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - 3 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - 6 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 - 12 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt; 1 Year</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HP_Lead_Status__c</fullName>
        <description>Picklist containing these values: Non compliant, Inactive, Active, Disqualified. Existing field carried over from Account object because of new partner data model. Tracks the reactivity of a partner at the location level in progressing through the life cycle of a Deal.</description>
        <label>HP Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Non Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Portal_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Portal Eligible</label>
        <type>Checkbox</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Interest__c.object
<CustomObject>
    <description>To store the list of product in which lead is interested</description>
    <fields>
        <fullName>Business_Group__c</fullName>
        <description>Will show the Business Group of Product</description>
        <formula>TEXT( Product__r.Business_Group__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GBU__c</fullName>
        <description>Will show the GBU of product</description>
        <formula>TEXT( Product__r.GBU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GBU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SFDC R3.0_Julalin_20/09/2012: New field is created as per the requirement #3214</description>
        <formula>Product__r.Product_Line__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Product_Line__c</fullName>
        <description>SFDC R3.0_Julalin_20/09/2012: New field is created as per the requirement #3214</description>
        <formula>Product__r.Sub_Product_Line__c</formula>
        <label>Sub Product Line</label>
        <type>Text</type>
    </fields>
    <label>Product Interest</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>Product Interest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Specialty_Definition__c.object
<CustomObject>
    <description>Specialty Definition Object- This is child object to Specialty which contains all the definition records.</description>
    <label>Specialty Definition</label>
    <nameField>
        <displayFormat>PSD-{00000}</displayFormat>
        <label>Specialty Definition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specialty Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define a Territory as Active/ Inactive</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean indicating whether Territory is exposed to Partner Accounts only</description>
        <label>IsPartner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MyComp_Sales_Territory_Name__c</fullName>
        <description>Created in R6</description>
        <label>Sales Territory Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Account_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Territory Account Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Account_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory Short Name</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Account Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Account_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Account Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Sales Territory Account Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Account Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Location_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>Location__r.Location_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Locator Id</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Location Assignment</label>
    <nameField>
        <label>STLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Location Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_User_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Record with ISActive checked signifies User&apos;s present in Group.</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Territory Short Name</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory User Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_User_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Territory_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory User Assignment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Sales Territory User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory User Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LeadCollabACPUtilTest.cls
/**********************************************************
* Class Name: LeadCollabACPUtilTest1
* Author: pravee
* Date:  
* Description:  
***********************************************************/
@isTest(seeAllData=true)

public class LeadCollabACPUtilTest {
    private static Account acc;
    private static List<Pricebook2> price;
    private static Product2 prod;
    private static PricebookEntry priceEntry;
    private static Product_Interest__c productInterest;
    private static Sales_Territory__c salesTerr;
    private static List<Sales_Territory_User_Assignment__c> salesTerrUsers;
    private static Sales_Territory_Account_Assignment__c salesTerrAcc;
    private static Product_Specialty_Definition__c prodSpcltyDef;
    private static List<User> users;
    private static Profile prof;
    private static List<Lead> newLeads;
    private static Account partAcc1 = new Account();
    private static Contact partContact1 = new Contact();
    private static User partUser1 = new User();
    private static Contact partContact2 = new Contact();
    private static User partUser2 = new User();
    private static user user;
    
    private static Location__c loc;
    private static Sales_Territory_Location_Assignment__c salesTerrLoc;
    private static Sales_Territory__c PartnersalesTerr;
    private static List<Sales_Territory_User_Assignment__c> PsalesTerrUsers;
  //  private static Map<id,Location__c> acpNewMap=new Map<id,Location__c>();
  //  private static Map<Id,List<String>> leadWithTerritoryGroups = new Map<id,List<String>>();
  //  private static List<Lead> leadslist =new List<Lead>();
  //  private static List<LeadShare> newLeadSharing = new List<LeadShare>();
    
    /*
     * Method for creating test data.
     */
     
    private static void setUpData(){
        system.debug('Enter setUpData()');
        //Create a test account
        acc = TestingSetupDataUtil.createAccount('testAccount_952PM', 'testAccount_9@hp.com','Customer');
        insert acc;
                
        RecordType rt=[select id,name from RecordType where name like '%Qualified%' limit 1];
        //Insert Lead
        newLeads = new List<Lead>();       
        Lead newLead = TestingSetupDataUtil.createLead('TestLead1', 'qqq123', 'Qualified', 'New', '123', 'test1@test.com');
        newLead.Account_Name__c = acc.Id;
        newLead.Budget__c = '121' ;
        newLead.Authorized_Buyer__c = 'No';
        newLead.Timeframe_to_Buy_1__c = '< 1 Week';
        newLead.Estimated_Budget__c = 123.0;
        newLead.recordtypeid=rt.id;
        
        insert newLead;
        
        
        newLeads.add(newLead);
        
       
        
        // create a test Product2
        prod = TestingSetupDataUtil.createProduct(true ,'abc','USD','1234');
        prod.Business_Group__c = 'ESSN';
        prod.GBU__c = 'Technology Support';
        prod.Product_Line__c = 'Technology Support PL';
        prod.Sub_Product_Line__c = 'Technology Support Sub-PL';
        insert prod;
        
         // create a test pricebook2
         price=new List<Pricebook2>();
        price = [select id, name, isActive from Pricebook2  where isstandard=true limit 1];
        
        // create a test Product2
        priceEntry = TestingSetupDataUtil.createPricebookEntry(prod.Id,true,price[0].Id,100,'USD');
        insert priceEntry;
        
        // create a test Lead products item
        productInterest = TestingSetupDataUtil.createProductInterest(newLead.Id, prod.Id);
        insert productInterest;
        
               
        //create a test sales territroy record.
        salesTerr = new Sales_Territory__c(Name = 'testSalesTerritory', IsActive__c = true,MyComp_Sales_Territory_Name__c ='ABC');
        insert salesTerr;
        
          /* Inserting User
        String randomstr = Math.round(Math.random()*Math.pow(10, 7))+'';
        user = new User();
        user = TestingSetupDataUtil.createUser('st'+randomstr.substring(0,4), randomstr+'standarduser@hp.com', randomstr+'standarduser@hp.com', 
                                                'UTF-8', 'U LastName', 'en_US', 'en_US', 'America/Los_Angeles', randomstr+'standarduser12@hp.com', 
                                                randomstr+'5', Userinfo.getProfileId());                 
        insert user; */
                
        
        //Create test User
        users = new List<User>();
        User user1 = new User();
        user1 = TestingSetupDataUtil.createUser('stTest1','abc@hp.com','email1@hp.com','UTF-8','Tertlan','en_US','en_US','America/Los_Angeles','saeest@hp.com','87654321',Userinfo.getProfileId());
        user1.Lead_Eligibility_Flag__c = true;
        user1.Global_Business_Unit__c = 'test';
        user1.Partner_Collaboration_Participating_User__c=true;
        
        
        
        //Create test User2
        User user2 = new User();
        user2 = TestingSetupDataUtil.createUser('stTest','abc2@hp.com','email12@hp.com','UTF-8','Tertlan','en_US','en_US','America/Los_Angeles','saeest2@hp.com','234567890',Userinfo.getProfileId());
        user2.Lead_Eligibility_Flag__c = true;
        user2.Global_Business_Unit__c = 'test';
        
       
        users.add(user1);
        users.add(user2);   
        
        insert users;
        
        //create user in sales terr
        salesTerrUsers = new List<Sales_Territory_User_Assignment__c>();
        Sales_Territory_User_Assignment__c salesTerrUser = new Sales_Territory_User_Assignment__c(Sales_Territory__c = salesTerr.Id, User__c = users[0].Id);
        Sales_Territory_User_Assignment__c salesTerrUser1 = new Sales_Territory_User_Assignment__c(Sales_Territory__c = salesTerr.Id, User__c = users[1].Id);
        salesTerrUsers.add(salesTerrUser);
        salesTerrUsers.add(salesTerrUser1);
        insert salesTerrUsers;
        
        // Create a account with record type - partner
        partAcc1 = TestingSetupDataUtil.createAccount('Test Partner Account1', 'partner1@partnercollab.com','Partner');
        partAcc1.Partner_Portal_Eligible__c = true;
        insert partAcc1;
        
        system.assertEquals(partAcc1.Partner_Portal_Eligible__c,true);
        //Enable the account as partner
        partAcc1.IsPartner = true;
        partAcc1.Partner_Portal_Eligible__c = true;
        partAcc1.HP_Lead_Status__c='Active';
        update partAcc1;  
        
        // Create a contact under the partner account
        partContact1 = TestingSetupDataUtil.createContact(partAcc1.Id, 'Test Prtnr Contact11');
        partContact1.Email='testcontact11@testing.com';
        insert partContact1;
        
        //Create Location
        loc= new Location__c(Location_Name__c='TestLocation', Name='1234567', Account__c=partAcc1.Id);
        insert loc;
        
        // fetch the partner profiles
        List<Profile> partnerProfiles = new List<Profile>();
        partnerProfiles = [Select p.UserType, p.UserLicenseId, p.Name, p.Id From Profile p where p.UserType like '%Partner%' ];
        // Create a partner user
        partUser1 = TestingSetupDataUtil.createUser('pruser1','partnerUser1@hp.com','5_1_partnerUser1@hp.com','UTF-8','parTneruser1','en_US','en_US','America/Los_Angeles','partnerUser1@hp.com','55145615',partnerProfiles[0].Id );
        partUser1.ManagerId = userInfo.getUserId();
        partUser1.ContactId = partContact1.Id;
        partUser1.Strike_Count__c=2;
        partUser1.Location_Record_Id__c=loc.Id;
        insert partUser1;
        
        /* Create a contact under the partner account
        partContact2 = TestingSetupDataUtil.createContact(partAcc1.Id, 'Test Prtnr Contact12');
        partContact2.Email='testcontact12@testing.com';
        insert partContact2;
        
        partUser2 = TestingSetupDataUtil.createUser('pruser21','partnerUser21@hp.com','5_1_partnerUser21@hp.com','UTF-8','parTneruser21','en_US','en_US','America/Los_Angeles','partnerUser21@hp.com','55145676',partnerProfiles[0].Id );
        partUser2.ManagerId = userInfo.getUserId(); 
        partUser2.ContactId = partContact2.Id;
        partUser2.Strike_Count__c=1;
        
        insert partUser2;  */

        //create a Sales Territory Account record
        salesTerrAcc = new Sales_Territory_Account_Assignment__c(Account__c = partAcc1.Id, Sales_Territory__c = salesTerr.Id);
        insert salesTerrAcc;
        
        //Create Partner Territory
        
        PartnersalesTerr = new Sales_Territory__c(Name = 'testSalesTerritory', IsActive__c = true, IsPartner__c= true,MyComp_Sales_Territory_Name__c ='ABC');
        insert PartnersalesTerr;
        
        
       //Sales territory location assignment
       
       salesTerrLoc = new Sales_Territory_Location_Assignment__c(Location__c=loc.Id, Sales_Territory__c = PartnersalesTerr.Id);
       insert salesTerrLoc;
       
       // Sales territory User assignment
       
       PsalesTerrUsers = new List<Sales_Territory_User_Assignment__c>();
       Sales_Territory_User_Assignment__c PsalesTerrUser = new Sales_Territory_User_Assignment__c(Sales_Territory__c = PartnersalesTerr.Id, User__c = users[0].Id);
       Sales_Territory_User_Assignment__c PsalesTerrUser1 = new Sales_Territory_User_Assignment__c(Sales_Territory__c = PartnersalesTerr.Id, User__c = users[1].Id);
       PsalesTerrUsers.add(PsalesTerrUser);
       PsalesTerrUsers.add(PsalesTerrUser1);
       insert PsalesTerrUsers;
        
        
        
        
    }
    
    static testMethod void Test() {
        
        
        Test.startTest();
        setUpData();
        
        
     /*   PageReference pageRef = Page.LeadManualAssigment;
        Test.setCurrentPageReference(pageRef);
        
        ApexPages.currentPage().getParameters().put('id',newLeads[0].Id);
        ApexPages.Standardsetcontroller sc1 = new ApexPages.Standardsetcontroller(newLeads);
        LeadAssignmentController leadAssign = new LeadAssignmentController(sc1);
        pageRef = leadAssign.assignLeads();
        pageRef = leadAssign.returnBack();
        
        */
        
        newLeads[0].ownerId=partUser1.id;
        newLeads[0].Partner_Owned__c=true;
        system.runAs(users[0]){
            update newLeads;
        }
       
        Test.stopTest();
        
    }
}