objects/Learning_Board__c.object
<CustomObject>
    <description>Created: Venkatesh S\Veeresh Alur
Date: 15/11/2013
Capablity: ES Offering
Release: 1
Description: Learning Board</description>
    <fields>
        <fullName>Default_Image_Name__c</fullName>
        <label>Default Image Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Featured__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Featured</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Learning Board</label>
    <nameField>
        <displayFormat>LB-{0000000000}</displayFormat>
        <label>Learning Board ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Boards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MyTrendsComment.cls
public class MyTrendsComment{
    public static void TComments(){
		 
        Integer TrendDays=Integer.valueOf(AthenaUtility.ApplicationSettingValue(AthenaUtility.MostCommentedTrendDays));
        system.debug('NoOfDays' + TrendDays);
        string typeComm='\'' + 'TextPost' + '\'';
       
        //Fetch all the Comments for all learning boards in N number days
        //List<FeedItem> feeddItmlst = [SELECT ParentId FROM FeedItem where Type='TextPost' and CreatedDate>= N_DAYS_AGO:TrendDays and ParentId IN (Select id from learning_board__c)];    
         List<FeedItem> feeddItmlst = Database.query('SELECT ParentId FROM FeedItem where Type=' + typeComm + ' and CreatedDate>= N_DAYS_AGO:' + TrendDays + ' and ParentId IN (Select id from learning_board__c)');    
        
		//Making the map of Learning Board Id anf Comment Count        
        Map<String,Integer> CmntCntMap = new Map<String,Integer>();
        system.debug('FI##'+feeddItmlst);
        for (FeedItem feedItm : feeddItmlst){            
            if(!CmntCntMap.containskey(feedItm.ParentId)){
                CmntCntMap.put(feedItm.ParentId,1);
            }
            else{
                integer i = CmntCntMap.get(feedItm.parentId);
                CmntCntMap.put(feedItm.parentId,i+1);            
            }
        }  
        system.debug('CmntCntMap'+CmntCntMap);          
        
		//Making Comment counts in Ascending order in  a list        
        List<integer> CmtCntLst = new List<integer>();
        CmtCntLst.addAll(CmntCntMap.Values());
        CmtCntLst.sort();
        System.debug(' Comment Count Lst' + CmtCntLst);
        
        //Making Comment counts in Descending order in  a list     
        List<integer> CmtCntDscLst = new List<integer>();
        for(Integer i = CmtCntLst.size()-1; i>=0;i--)
        {   
            CmtCntDscLst.add(CmtCntLst.get(i));
        }
		system.debug('CmtCntDscLst' + CmtCntDscLst);       
        
        //Getting Learning Board Ids in to a list 
        List<String> lrngBrdIdLstTmp = new List<string>();
        for(integer i : CmtCntDscLst){
            for(String s : CmntCntMap.keyset()){
                if(i==CmntCntMap.get(s)){
                    lrngBrdIdLstTmp.add(s);                    
                }
            }
        }
        
		Set<String> myset = new Set<String>();
        List<String> finallrngBrdIdLst = new List<String>();
        List<Learning_Board__c> lrngBrdLst=[SELECT Id, Name__c, Description__c, Featured__c, Is_Active__c, Default_Image_Name__c FROM Learning_Board__c where id in:lrngBrdIdLstTmp];
        List<Learning_Board__c> lstLearningBoard=new List<Learning_Board__c>();
        system.debug(' lrngBrdLst ' + lrngBrdLst);
       
        for (String s : lrngBrdIdLstTmp) {
          if (myset.add(s)) {
              finallrngBrdIdLst.add(s); 
              for(Learning_Board__c lb:lrngBrdLst)
              {
                  if(lb.id==s)
                  {
                      lstLearningBoard.add(lb);
                  }
              }
          }            
        }
        
        system.debug(' Final Learning Board Lst ' + finallrngBrdIdLst);
        System.debug(' lstLearningBoard ' + lstLearningBoard);
        
    }
   }