objects/Learning_Board__c.object
<CustomObject>
    <description>Created: Venkatesh S\Veeresh Alur
Date: 15/11/2013
Capablity: ES Offering
Release: 1
Description: Learning Board</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Learning Board</label>
    <nameField>
        <displayFormat>LB-{0000000000}</displayFormat>
        <label>Learning Board ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Boards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/controllerforcomponent.cls
public class controllerforcomponent{

public string learningBoard{get;set;}
public List<Learning_Board__c> learningBoardList{get;set;}
public String sQuery;
public List<Learning_Board__c> getRecords() {
        sQuery='';
         sQuery = sQuery + 'select id,name,description__c from ' + learningBoard;
         system.debug('squery:'+squery);
         learningBoardList = new LIst<Learning_Board__c>();
         learningBoardList = database.query(sQuery);
         if(learningBoardList.size() != null && learningBoardList.size()>0)
             return learningBoardList;
         else
             return null;
  }
}