objects/Learning__c.object
<CustomObject>
    <description>Created: Venkatesh S\Veeresh Alur 
Date: 15/11/2013 
Capablity: ES Offering 
Release: 1 
Description: Learning Board</description>
    <label>Learning</label>
    <nameField>
        <displayFormat>LE-{0000000000}</displayFormat>
        <label>Learning ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learnings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Learning_Board__c.object
<CustomObject>
    <description>Created: Venkatesh S\Veeresh Alur
Date: 15/11/2013
Capablity: ES Offering
Release: 1
Description: Learning Board</description>
    <label>Learning Board</label>
    <nameField>
        <displayFormat>LB-{0000000000}</displayFormat>
        <label>Learning Board ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Boards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Learning_Board_Learning__c.object
<CustomObject>
    <description>Created: Venkatesh S\Veeresh Alur 
Date: 17/11/2013 
Capablity: ES Offering 
Release: 1 
Description: Intersection Object between Learning Board and Learning to support Many to Many relationships</description>
    <fields>
        <fullName>Learning_Board_ID__c</fullName>
        <label>Learning Board ID</label>
        <referenceTo>Learning_Board__c</referenceTo>
        <relationshipLabel>Learning Board Learnings</relationshipLabel>
        <relationshipName>Learning_Board_Learnings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Learning_Category_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Category Id</label>
        <referenceTo>Learning_Category__c</referenceTo>
        <relationshipLabel>Learning Board Learnings</relationshipLabel>
        <relationshipName>Learning_Board_Learnings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Learning_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Learning ID</label>
        <referenceTo>Learning__c</referenceTo>
        <relationshipLabel>Learning Board Learnings</relationshipLabel>
        <relationshipName>Learning_Board_Learnings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Learning Board Learning</label>
    <nameField>
        <displayFormat>LL-{0000000000}</displayFormat>
        <label>Learning Board Learning ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Board Learnings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Learning_Category__c.object
<CustomObject>
    <description>Created By :- Veeresh Alur
Date: 27-Feb-14
Capability: ES Social Learning Platform
Release: 2
Description: Learning Categories</description>
    <label>Learning Category</label>
    <nameField>
        <displayFormat>LC-{00000000}</displayFormat>
        <label>Learning Category ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Tag_Item__c.object
<CustomObject>
    <description>Created By :- Veeresh Alur 
Date: 04-Feb-14 
Capability: ES Social Learning 
Release: 1.1 
Description: Associated tags will present</description>
    <fields>
        <fullName>Item_Identifier__c</fullName>
        <label>Item Identifier</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tag_ID__c</fullName>
        <label>Tag ID</label>
        <referenceTo>Tag__c</referenceTo>
        <relationshipLabel>Tag Items</relationshipLabel>
        <relationshipName>Tag_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tag Item</label>
    <nameField>
        <displayFormat>TITEM-{00000}</displayFormat>
        <label>Tag Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/datacleanup.cls
public class datacleanup {
    Public String LearningID{get;set;}
    Public String LearningBoardID{get;set;}
        
    Public List<Learning_Board_Learning__c> LBLList{get;set;}
    Public Learning__c LearningName{get;set;}
    Public List<Tag_Item__c> TagList{get;set;}        
    
    Public integer flag{get;set;}
    Public List<Learning_Board_Learning__c> LearningBoardList{get;set;}
    Public void deleteLearning(){
        LBLList= [select id,name,Learning_Board_ID__r.name,Learning_ID__r.name,Learning_Category_ID__r.name from learning_Board_Learning__c where Learning_ID__r.name =:LearningID];
        TagList = [SELECT name,Item_Name__c,Tag_ID__c,Item_Identifier__c FROM Tag_Item__c];
        system.debug('###'+LBLList); 
        system.debug('###'+TagList); 
        flag=1;       
    }
    Public void LearningBoard(){
        LearningBoardList= [select id,name,Learning_Board_ID__r.name,Learning_Category_ID__r.name from learning_Board_Learning__c where Learning_Board_ID__r.name=:LearningBoardID];
        system.debug('$$$'+LearningBoardList);
        flag=2;        
    }
}