objects/Legal_Issue__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Legal Issues</relationshipLabel>
        <relationshipName>Legal_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Content__c</fullName>
        <label>HP&apos;s Response</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Paragraph__c</fullName>
        <label>Customer Non Standard Positions</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Make Risk Category in Sequence..</description>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Legal Issue</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Legal Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legal Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Apts_OverwriteLegalIssueEditDeleteTest.cls
@isTest
public with sharing class Apts_OverwriteLegalIssueEditDeleteTest {
	public static testmethod void testAptsOverwriteLegalIssueEditDelete(){
		
		ID rtID = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Not yet selected').getRecordTypeID();
		
		Apttus__APTS_Agreement__c agmtObj = new Apttus__APTS_Agreement__c();
     	agmtObj.Name = 'Test Agreement';
     	agmtObj.RecordTypeID = rtID;
     	agmtObj.Number_of_times_SOAR_form_Generated__c = 12;
     	insert agmtObj;
		
		Legal_Issue__c li = new Legal_Issue__c();
     	li.Agreement__c = agmtObj.ID;
     	li.Initial_Content__c = 'test initail content';
     	li.Paragraph__c = 'test paragraph';
     	li.Sequence__c = 2;
     	insert li;
     	
		ApexPages.StandardController con = new ApexPages.StandardController(li);
     	Apts_OverwriteLegalIssueEditDelete aptLegalIssue = new Apts_OverwriteLegalIssueEditDelete(con);
     	
     	PageReference pref = aptLegalIssue.forwardToAgreement();
     	System.assertEquals(pref.getUrl(), '/'+li.Agreement__c);
	}
}