objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Relationship__c</fullName>
        <description>Reference to an Account&apos;s Business Relationship value.</description>
        <formula>Account__r.MDCP_Business_Relationship__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Relationship</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Address city.</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Address country.</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDCP_Organization_ID__c</fullName>
        <formula>Account__r.MDCP_Organization_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MDCP Organization ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sell_Into_Market__c</fullName>
        <description>World/Region or Country market this Locations is supporting for sales.</description>
        <label>Sell Into Market</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Account_ID__c</fullName>
        <description>External System ID. A Siebel PRM Partner ID.</description>
        <label>Source System Account ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define a Territory as Active/ Inactive</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MyComp_Sales_Territory_Name__c</fullName>
        <description>Created in R6</description>
        <label>Sales Territory Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MyComp_Territory_Country__c</fullName>
        <description>Added in r6 for SaaSPMO 3912: https://cs10.salesforce.com/a0rJ0000002CxZB</description>
        <label>Territory Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BQ</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MyComp_Territory_Region__c</fullName>
        <description>R6 - TM</description>
        <label>Territory Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Location_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <formula>Location__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Location__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>Location__r.Location_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Locator Id</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Location Assignment</label>
    <nameField>
        <label>STLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Location Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_User_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Record with ISActive checked signifies User&apos;s present in Group.</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Territory Short Name</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory User Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_User_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Territory_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory User Assignment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Sales Territory User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory User Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TMLocationTerritoryController.cls
/***************************************************************************************************************
* Class Name: TMLocationTerritoryController 
* Author: HP
* Date: 11-JUN-2013
* Requirement # Request Id : R5:CR-7730
* Description: This custom controller contains the logic to show Locations falling under logged in User 
               through Territory on a VF page
*****************************************************************************************************************/

public with sharing class TMLocationTerritoryController{
    
    public Integer numberOfRecords{get;set;}
    
    public Integer size{get;set;}
    
    public boolean hasNext{
        get{
            return setController.getHasNext();
        }
        set;
    }
    
    public boolean hasPrevious{
        get{
            return setController.getHasPrevious();
        }
        set;
    }
    
    public Integer pageNumber{
        get{
            return setController.getPageNumber();
        }
        set;
    } 

    public ApexPages.StandardSetController setController{
        get{
            if(setController == null){
                Set<Id> salesTerritorySet = getUsersSalesTerritorySet(UserInfo.getUserId());
                size = 200;
                setController = new ApexPages.StandardSetController(Database.getQueryLocator([Select location__c,location__r.Location_Name__c,location__r.Account__r.Name,location__r.Country__c,location__r.City__c,Sales_Territory__r.MyComp_Sales_Territory_Name__c,location__r.Sell_Into_Market__c,location__r.MDCP_Organization_ID__c,location__r.Business_Relationship__c,location__r.Source_System_Account_ID__c,Sales_Territory__r.MyComp_Territory_Region__c,Sales_Territory__r.MyComp_Territory_Country__c,Sales_Territory__c from Sales_Territory_Location_Assignment__c where Sales_Territory__c IN :salesTerritorySet]));
                setController.setPageSize(size);
                numberOfRecords = setController.getResultSize();
            }
            return setController;
        }
        set;
    }
    
    /**
    * @description:Fetches set of Sales Territory assigned to the logged in User.
    * @params: userId
    * @returns: Set<Id> 
    */
    public Set<Id> getUsersSalesTerritorySet(Id userId){
        Set<Id> usersSalesTerritorySet = new Set<Id>();
        if(userId != null){
            for(Sales_Territory_User_Assignment__c stua:[Select Sales_Territory__c,Sales_Territory__r.Name From Sales_Territory_User_Assignment__c where User__c = :userId AND IsActive__c = true AND Sales_Territory__r.IsActive__c = true]){
                usersSalesTerritorySet .add(stua.Sales_Territory__c);
            }
        }
        return usersSalesTerritorySet;
    }
    /**
    * @description:Fetches all the location records related to logged in user through territories
    * @params: none
    * @returns: List<Sales_Territory_Location_Assignment__c>
    */
    public List<Sales_Territory_Location_Assignment__c> getLocations(){
        return setController.getRecords();
    }
    
    /**
    * @description:Fetches next set of records.
    * @params: none
    * @returns: void
    */
    public void next() {
        setController.next();
    }
    
    /**
    * @description:Fetches previous set of records.
    * @params: none
    * @returns: void
    */
    public void previous(){
        setController.previous();
    }
    
    /**
    * @description:Returns the first page of records.
    * @params: none
    * @returns: void
    */
    public void first(){
        setController.first();
    }
    
    /**
    * @description:Returns the last page of records.
    * @params: none
    * @returns: void
    */
    public void last(){
        setController.last();
    }
     
}