objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Business_Relationship__c</fullName>
        <description>Reference to an Account&apos;s Business Relationship value.</description>
        <formula>Account__r.MDCP_Business_Relationship__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Relationship</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Address country.</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Demerit_Count__c</fullName>
        <description>To store the demerit count</description>
        <label>Demerit Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EvaluateTerritory__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EvaluateTerritory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HP_Lead_Status__c</fullName>
        <description>Picklist containing these values: Non compliant, Inactive, Active, Disqualified. Existing field carried over from Account object because of new partner data model. Tracks the reactivity of a partner at the location level in progressing through the life cycle of a Deal.</description>
        <label>HP Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Non Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDCP_Organization_ID__c</fullName>
        <formula>Account__r.MDCP_Organization_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MDCP Organization ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Address ZIP or Postal Code.</description>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Address state or province name.</description>
        <label>State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>World_Region1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>World Region</label>
        <referenceTo>World_Region__c</referenceTo>
        <relationshipLabel>Locations (World Region)</relationshipLabel>
        <relationshipName>Locations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LocationTriggerController.cls
/**********************************************************
* Class Name: LocationTriggerController
* Author: HP 
* Date: 13-Mar-2013 
* Description: To Update the strike count to zero when the HP Lead Status value changed from 
              'Non compliant' to either 'Active','Inactive' or 'Disqualified'
***********************************************************/

public class LocationTriggerController{

    /*
    *@description: Update the demerit count of the user to zero when location status changed from "Non Compliant" to "Active/Inactive/Disqualified"
    */

public static void toUpdateStrikeCount(Map<Id,Location__c> newLocationMap, Map<Id,Location__c> oldLocationMap){

List<Id> locationIdList= new List<Id>();
List<User> userList = new List<User>();
List<User> toUpdateUserList= new List<User>();

    for(Id updatedLocId : newLocationMap.keyset()){
        if((oldLocationMap.get(updatedLocId).HP_Lead_Status__c =='Non compliant') && (newLocationMap.get(updatedLocId).HP_Lead_Status__c !='Non compliant') && (newLocationMap.get(updatedLocId).HP_Lead_Status__c !=NULL)){
        locationIdList.add(newLocationMap.get(updatedLocId).Id);
        newLocationMap.get(updatedLocId).demerit_count__c=0;
        }
    }
    
    if(locationIdList.size() > 0){
        userList=[select id,Strike_Count__c from User where Location_Record_Id__c in :locationIdList];
        system.debug('user list'+userList.size());
        }
        
    if (userList.size() > 0){
        for(User user:userList){
        user.Strike_Count__c=0;
        toUpdateUserList.add(user);
        }
        Update toUpdateUserList;
    }
        
}

    /*
    *@description: To restrict the user to change the "HP Lead Status" value from "Inactive" to "Non Compliant"
    */

public static void locationStatusNotInactiveToNoncompliant(Map<Id,Location__c> newLocationMap, Map<Id,Location__c> oldLocationMap){

    for(Location__c loc:newLocationMap.values()){
        if(oldLocationMap.get(loc.id).HP_Lead_Status__c=='Inactive' && loc.HP_Lead_Status__c=='Non compliant'){
        loc.addError(System.Label.Cannot_Change_Lead_Status_from_Inactive_to_Non_compliant);
         return;
         }
     }
  }
  
/**
    * @description: This method is called from before update trigger
    *               It identifies Locations which are updated
    *               & set evaluate territory flag to true . 
    * @param: List of new Location__c records
    * TM: Vinay M: Req:6021 Apr 8,2013
    **/
public static void beforeUpdate(Map<Id,Location__c> newLocationMap, Map<Id,Location__c> oldLocationMap){
    
    List<Location__c> locationsToUpdateList = new List<Location__c>();
    
    if(newLocationMap != null && newLocationMap.size() > 0 && oldLocationMap != null && oldLocationMap.size() > 0){
        for(Id locationId: newLocationMap.keyset()){
            if(newLocationMap.get(locationId).Business_Relationship__c != oldLocationMap.get(locationId).Business_Relationship__c ||
               newLocationMap.get(locationId).Country__c != oldLocationMap.get(locationId).Country__c ||
               newLocationMap.get(locationId).Location_Name__c != oldLocationMap.get(locationId).Location_Name__c ||
               newLocationMap.get(locationId).MDCP_Organization_ID__c != oldLocationMap.get(locationId).MDCP_Organization_ID__c ||
               newLocationMap.get(locationId).State__c != oldLocationMap.get(locationId).State__c ||
               newLocationMap.get(locationId).World_Region1__c != oldLocationMap.get(locationId).World_Region1__c ||
               newLocationMap.get(locationId).Postal_Code__c != oldLocationMap.get(locationId).Postal_Code__c){
               locationsToUpdateList.add(newLocationMap.get(locationId));
            }
        }
    }
    
    if(locationsToUpdateList.size() > 0){
        for(Location__c loc: locationsToUpdateList){
            loc.EvaluateTerritory__c = true;
        }
    }
}
    
}