objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Revenue__c</fullName>
        <label>Annual Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Relationship__c</fullName>
        <description>Reference to an Account&apos;s Business Relationship value.</description>
        <formula>Account__r.MDCP_Business_Relationship__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Relationship</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Address city.</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Address country.</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DUNS__c</fullName>
        <label>DUNS Site Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Demerit_Count__c</fullName>
        <description>To store the demerit count</description>
        <label>Demerit Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EvaluateTerritory__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EvaluateTerritory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HP_Lead_Status__c</fullName>
        <description>Picklist containing these values: Non compliant, Inactive, Active, Disqualified. Existing field carried over from Account object because of new partner data model. Tracks the reactivity of a partner at the location level in progressing through the life cycle of a Deal.</description>
        <label>HP Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Non Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HP_SFDC_Access__c</fullName>
        <description>Existing field carried over from Account object because of new partner data model. The field drives application logic related to Lead/Opportunity assignment to users of  portal-enabled partners&apos; Locations.</description>
        <label>HP SFDC Access</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Status__c</fullName>
        <description>Location record&apos;s business activeness. Active/Inactive.</description>
        <label>Location Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDCP_Organization_ID__c</fullName>
        <formula>Account__r.MDCP_Organization_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MDCP Organization ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDCP_Other_Party_Site_Instance_ID__c</fullName>
        <description>MDCP Other Party Site Instance ID for this Site Business Relationship with address.</description>
        <label>MDCP Site Instance ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Of_Employees__c</fullName>
        <label>Employees</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Out_Of_Business__c</fullName>
        <label>Out Of Business</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Portal_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Portal Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Address ZIP or Postal Code.</description>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to signal that this Location/OPSI is primary for its parent Business Relationship.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sell_Into_Market__c</fullName>
        <description>World/Region or Country market this Locations is supporting for sales.</description>
        <label>Sell Into Market</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>MDCP Business Relationship Item sequence number univocally identifying a Site Business Relationship.</description>
        <label>Sequence</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Account_ID__c</fullName>
        <description>External System ID. A Siebel PRM Partner ID.</description>
        <label>Source System Account ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Address state or province name.</description>
        <label>State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Address Line1 to Line 3 concatenated string.</description>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Userkey__c</fullName>
        <description>Location record unique key.</description>
        <externalId>true</externalId>
        <label>Userkey</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WorldRegion_Hierarchy__c</fullName>
        <formula>World_Region1__r.Geographic_Hierarchy__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geographic Hierarchy</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorldRegion_Region__c</fullName>
        <description>The field displays the &quot;Region&quot; value the Country defined in the address belongs to. The master field used for the evaluation of Region is Location.Country_Code__c, i.e., Lookup(World_Region_c).</description>
        <formula>World_Region1__r.Region__c</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorldRegion_SubRegion1__c</fullName>
        <formula>World_Region1__r.Sub_Region1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubRegion1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorldRegion_SubRegion2__c</fullName>
        <formula>World_Region1__r.Sub_Region2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubRegion2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorldRegion_SubRegion3__c</fullName>
        <formula>World_Region1__r.Sub_Region3__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubRegion3</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>World_Region1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>World Region</label>
        <referenceTo>World_Region__c</referenceTo>
        <relationshipLabel>Locations (World Region)</relationshipLabel>
        <relationshipName>Locations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TerritoryDeltaChanges__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Territory_Evaluation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Territory Evaluation</label>
        <type>Checkbox</type>
    </fields>
    <label>TerritoryDeltaChanges</label>
</CustomObject>

objects/TMEngineAccountRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>AccountRecordType__c</fullName>
        <label>AccountRecordType</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>TMEngineAccountRecordType</label>
</CustomObject>

objects/TMEngineScheduledFlag__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>TMEngineScheduled to be flagged TRUE until all batches complete, next schedule will only begin if flag is FALSE i.e all batches from first instance executed.</description>
    <fields>
        <fullName>SchedularFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SchedularFlag</label>
        <type>Checkbox</type>
    </fields>
    <label>TMEngineScheduledFlag__c</label>
</CustomObject>

objects/World_Region__c.object
<CustomObject>
    <description>For testing World Region</description>
    <label>World Region</label>
    <nameField>
        <label>World Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>World Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TMBatchHelper.cls
/**********************************************************
* Class Name: TMBatchHelper
* Author: Accenture
* Date: 19-JUL-2012  
* Requirement # Request Id: 
* Description: Helper Class for Query String in Batch and
*              Email Notifivation Template for all Batches.  
***********************************************************/

public class TMBatchHelper {
    

    /**
    * @description: Initialiases query string to be used in batch.
    **/
    // TM: Debmalya: Req-2091 Aug 28, 2012:Handling Recordtype Partner for Account - Start
    /*public static String queryString1 = 'Select Id, Regions__c, RecordTypeId, RAD__c, MDCP_Organization_ID__c, ' +  
                                        'Industry, Confidential_Account__c, World_Region__c, AMID_L2__c, ' + 
                                        'ShippingState, ShippingPostalCode, ShippingCountry, ' + 
                                        'Source_System_Account_ID__c, Named_Account__c, LastAssignmentDate__c, AccountProfileEvaluated__c, ' +
                                        'LastAcountProfAssignmentDate__c, LastIndustryAssignmentDate__c, LastCoverageAssignmentDate__c, ' + 
                                        'Industry_Vertical__c, Coverage_Segmentation__c, EvaluateTerritory__c ' +
                                    'From Account ' +
                                    'Where EvaluateTerritory__c = true AND RecordType.Name = \'Customer\'';

    public static String queryString(){
        TMEngineScheduledFlag__c flag = TMEngineScheduledFlag__c.getInstance('AccountProfFullRun');
        if(flag != null && !flag.SchedularFlag__c){
            queryString1 += ' AND AccountProfileEvaluated__c = false';
        }        
        return queryString1;
    }*/
    public static String queryString {
        set;
        get{
            TMEngineAccountRecordType__c obj1 = TMEngineAccountRecordType__c.getValues(Label.AccRecTypeVal);
            String currAccountRecordType = obj1.AccountRecordType__c;
            queryString = 'Select Id, Regions__c, RecordTypeId, RAD__c, MDCP_Organization_ID__c, MDCP_Business_Relationship__c, ' +  
                                   'Industry, Confidential_Account__c, World_Region__c, AMID_L2__c, ' + 
                                   'ShippingState, ShippingPostalCode, ShippingCountry, ' + 
                                   'Source_System_Account_ID__c, Named_Account__c, LastAssignmentDate__c, ' + 
                                   'Industry_Vertical__c, Coverage_Segmentation__c, EvaluateTerritory__c,' +
            //sreenath added code for Region value evaluation 2089
            //TM:R4:CR3999:Debmalya:4th Jan,2013:get BA Market Segmentfrom Account
                                   'WorldRegion_Hierarchy__c, BG_Target_Segments__c ' +
                                   'From Account ' +
            //sreenath added code for Region value evaluation 2089
            //                       'Where EvaluateTerritory__c = true AND RecordType.Name = \'' + currAccountRecordType + '\'';
                                   'Where RecordType.Name = \'' + currAccountRecordType + '\''; 
            //sreenath added code for Region value evaluation 2089
            TMEngineAccountRecordType__c Robj2 = TMEngineAccountRecordType__c.getValues('Realignment_Region');
            string Regionvalue = Robj2.AccountRecordType__c;
            system.debug('+++++'+querystring);
            if(null != Robj2 && Robj2.AccountRecordType__c != 'None'){
                querystring = querystring + ' AND WorldRegion_Region__c = \'' + Regionvalue + '\'';
                TMEngineAccountRecordType__c objSR = TMEngineAccountRecordType__c.getValues('Realignment_SubRegion1');
                if(null != objSR && objSR.AccountRecordType__c != '' && objSR.AccountRecordType__c != null){
                    querystring += ' AND WorldRegion_SubRegion1__c = \'' + objSR.AccountRecordType__c + '\'';
                    system.debug('+++++'+querystring);
                }
            }else{
                querystring = querystring + ' AND EvaluateTerritory__c = true '; 
                system.debug('+++++'+querystring);
            } 
             
            TMEngineScheduledFlag__c flag = TMEngineScheduledFlag__c.getInstance('AccountProfFullRun');
            if(flag != null && !flag.SchedularFlag__c){
               queryString += ' AND AccountProfileEvaluated__c = false';
               system.debug('+++++'+querystring);
            }                                    
             system.debug('+++++'+querystring);
             //TM:R6:CR-11429:If Batch is Partner and Hourly, fetch 100 Accounts at a time-Start
             /*TerritoryDeltaChanges__c weekendFlagObj = TerritoryDeltaChanges__c.getInstance('RealignmentProcess');
             Boolean weekendFlag = weekendFlagObj.Territory_Evaluation__c;
             if(currAccountRecordType == 'Partner' && weekendFlag == false && Regionvalue == 'None'){
                queryString += ' LIMIT 100';
             }*/
             //TM:R6:CR-11429:If Batch is Partner fetch 100 Accounts at a time-End
             return queryString;
             
       }
    }
   
                                        
    /**
    * @description: Initialiases query string to be used in batch based on AccountProfile Evaluation flag.
    **/
    /*public static String queryString2 = 'Select Id, Regions__c, RecordTypeId, RAD__c, MDCP_Organization_ID__c, ' +  
                                            'Industry, Confidential_Account__c, World_Region__c, AMID_L2__c, ' + 
                                            'ShippingState, ShippingPostalCode, ShippingCountry, ' + 
                                            'Source_System_Account_ID__c, Named_Account__c, LastAssignmentDate__c, AccountProfileEvaluated__c, ' + 
                                            'LastAcountProfAssignmentDate__c, LastIndustryAssignmentDate__c, LastCoverageAssignmentDate__c, ' + 
                                            'Industry_Vertical__c, Coverage_Segmentation__c, EvaluateTerritory__c ' +
                                        'From Account ' +
                                        'Where EvaluateTerritory__c = true AND RecordType.Name = \'Customer\' AND AccountProfileEvaluated__c = true';*/
    public static String queryString2 {
        set;
        get{
            TMEngineAccountRecordType__c obj1 = TMEngineAccountRecordType__c.getValues(Label.AccRecTypeVal);
            String currAccountRecordType = obj1.AccountRecordType__c;
            queryString2 = 'Select Id, Regions__c, RecordTypeId, RAD__c, MDCP_Organization_ID__c, ' +  
                                            'Industry, Confidential_Account__c, World_Region__c, AMID_L2__c, ' + 
                                            'ShippingState, ShippingPostalCode, ShippingCountry, ' + 
                                            'Source_System_Account_ID__c, Named_Account__c, LastAssignmentDate__c, AccountProfileEvaluated__c, ' + 
                                            'LastAcountProfAssignmentDate__c, LastIndustryAssignmentDate__c, LastCoverageAssignmentDate__c, ' + 
                                            'Industry_Vertical__c, Coverage_Segmentation__c, EvaluateTerritory__c, ' +
            //sreenath added code for Region value evaluation 2089
            //TM:R4:CR3999:Debmalya:4th Jan,2013:get BA Market Segmentfrom Account
                                   'WorldRegion_Hierarchy__c, BG_Target_Segments__c ' +
                                   'From Account ' +
            //sreenath added code for Region value evaluation 2089
            //                       'Where EvaluateTerritory__c = true AND RecordType.Name = \'' + currAccountRecordType + '\'';
                                   'Where RecordType.Name = \'' + currAccountRecordType + '\' AND AccountProfileEvaluated__c = true'; 
            //sreenath added code for Region value evaluation 2089
             TMEngineAccountRecordType__c Robj2 = TMEngineAccountRecordType__c.getValues('Realignment_Region');
              string Regionvalue = Robj2.AccountRecordType__c;
              if(null != Robj2 && Robj2.AccountRecordType__c != 'None'){
                querystring2 = querystring2 + ' AND WorldRegion_Region__c = \'' + Regionvalue + '\'';
             }                               
             return queryString2;
       }
    }
    
    //TM: Vinay: Req-6201 Apr 9,2013: Location query for Location Rules - Start
    public static String queryString3 {
        set;
        get{
            queryString3 = 'Select Account__c, Annual_Revenue__c, Business_Relationship__c, City__c,'+
                           'Country__c, Demerit_Count__c, DUNS__c, Number_Of_Employees__c,'+
                           'EvaluateTerritory__c, Fax__c, WorldRegion_Hierarchy__c, HP_Lead_Status__c,'+
                           'HP_SFDC_Access__c, Location_Status__c, Location_Name__c,'+ 
                           'MDCP_Organization_ID__c, MDCP_Other_Party_Site_Instance_ID__c, Out_Of_Business__c, Partner_Portal_Eligible__c,'+ 
                           'Phone__c, Primary__c, WorldRegion_Region__c, Sell_Into_Market__c, Sequence__c,'+
                           'Source_System_Account_ID__c, State__c, Street__c, WorldRegion_SubRegion1__c, WorldRegion_SubRegion2__c,'+
                           'WorldRegion_SubRegion3__c, Userkey__c, World_Region1__c, Postal_Code__c, Name,'+
                           'CurrencyIsoCode, Id From Location__c ';
                           
            //Condition to fetch Location records region wise               
            TMEngineAccountRecordType__c region = TMEngineAccountRecordType__c.getValues('Realignment_Region');
            String regionValue = region.AccountRecordType__c;
            
            if(regionValue != null && regionValue != 'None'){
                queryString3 += 'Where WorldRegion_Region__c = \''+regionValue+'\'';
                TMEngineAccountRecordType__c subRegion1 = TMEngineAccountRecordType__c.getValues('Realignment_SubRegion1');
                String subRegion1Value = subRegion1.AccountRecordType__c;
                if(subRegion1Value != null && subRegion1Value != ''){
                    queryString3 += 'AND WorldRegion_SubRegion1__c = \''+subRegion1Value+'\'';
                }
            }else{
                queryString3 += 'Where EvaluateTerritory__c = true';
            }
            //TM:R5:EF02:Vinay
             TerritoryDeltaChanges__c weekendFlagObj = TerritoryDeltaChanges__c.getInstance('RealignmentProcess');
             Boolean weekendFlag = weekendFlagObj.Territory_Evaluation__c;
                
                if(Test.isRunningTest()){
                    queryString3 += ' Limit 5';
                }                
            return queryString3;
        }
    }
    //TM: Vinay: Req-6201 Apr 9,2013: Location query for Location Rules - End
    
    // TM: Debmalya: Req-2091 Aug 28, 2012:Handling Recordtype Partner for Account - End
    // Email Notification Based on Type.                                
    /**
    * @description: Sends Email Notification after batch Completion
    **/
    public static void sendEmailNotification(Database.BatchableContext ctx, String ruleType) {
        
        if (ctx != null) {
            AsyncApexJob apexJob = [SELECT id, ApexClassId,   
                                       JobItemsProcessed, TotalJobItems,   
                                       NumberOfErrors, CreatedBy.Email   
                                    FROM AsyncApexJob   
                                    WHERE id = :ctx.getJobId()];  
            
            //TM:Vinay: Req-6201 Apr 4,2013:Handling Location Rule type - Start
            String emailMessage;
            if(ruleType == 'Location'){
                    emailMessage = Label.NotificationMessage4+' ' + ruleType + ' '+Label.NotificationMessage2+' '  
                        + apexJob.totalJobItems   
                        + ' '+Label.NotificationMessage3; 
            }
            //TM:Vinay: Req-6201 Apr 4,2013:Handling Location Rule type - Start
            else{
                emailMessage = Label.NotificationMessage1+' ' + ruleType + ' '+Label.NotificationMessage2+' '  
                  + apexJob.totalJobItems   
                  + ' '+Label.NotificationMessage3;  
            }
            Messaging.SingleEmailMessage mail =   
                  new Messaging.SingleEmailMessage();  
            String[] toAddresses = new String[] {apexJob.CreatedBy.Email};  
            mail.setToAddresses(toAddresses);  
            mail.setReplyTo('noreply@salesforce.com');  
            mail.setSenderDisplayName(Label.SenderDisplayName);  
            mail.setSubject(Label.Subject);  
            mail.setPlainTextBody(emailMessage);  
            mail.setHtmlBody(emailMessage);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]  
                              { mail });
        }
        
    }                                      
}