objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Address country.</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HP_Lead_Status__c</fullName>
        <description>Picklist containing these values: Non compliant, Inactive, Active, Disqualified. Existing field carried over from Account object because of new partner data model. Tracks the reactivity of a partner at the location level in progressing through the life cycle of a Deal.</description>
        <label>HP Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Non Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDCP_Organization_ID__c</fullName>
        <formula>Account__r.MDCP_Organization_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MDCP Organization ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Address ZIP or Postal Code.</description>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Address state or province name.</description>
        <label>State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>World_Region1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>World Region</label>
        <referenceTo>World_Region__c</referenceTo>
        <relationshipLabel>Locations (World Region)</relationshipLabel>
        <relationshipName>Locations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/World_Region__c.object
<CustomObject>
    <description>For testing World Region</description>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>World Region</label>
    <nameField>
        <label>World Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>World Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PCLM_NoncompliantRemovalControllerTest.cls
/**********************************************************
* Class Name: PCLM_NoncompliantRemovalControllerTest    
* Author: HP 
* Date: 10-May-2013
* Description: This class contains the test code coverage for the class "LocationTriggerController"
***********************************************************/
@isTest(seeAllData = true)
Private class PCLM_NoncompliantRemovalControllerTest {  
public static testMethod void testProbationRemoval(){
    Recordtype recordId=[Select Id,Name from recordtype where Name='Partner'];
   
    //Test Account Insertion     
    Account newAcc=new Account(Name='Test Account11',ShippingCountry='India',RecordTypeId=recordId.Id,MDCP_Organization_ID__c='2343478',MDCP_Business_Relationship_ID__c='485345786');
    Insert newAcc;
    
    Account newCustAcc=new Account(Name='Test Customer Account',ShippingCountry='India');
    Insert newCustAcc;
    
    
    World_Region__c newWorld=new World_Region__c(Name='Test',Country_Name__c='India');
    Insert newWorld;
    
    World_Region__c newWorld1=new World_Region__c(Name='Test1',Country_Name__c='US');
    Insert newWorld1;
    
    Contact newCon=new Contact(LastName='test',AccountId=newAcc.Id,Email='anh1@hp.com');
    Insert newCon;
    
    Location__c newLoc=new Location__c(Name='33586574',Account__c=newAcc.Id,HP_Lead_Status__c='Non compliant',Country__c='India',Location_Name__c='test1',State__c='Karnataka',World_Region1__c=newWorld.Id,Postal_Code__c='1283983');
    Insert newLoc;  

    newAcc.MDCP_Organization_ID__c='23434785';
    newAcc.MDCP_Business_Relationship_ID__c='4853457869';
    Update newAcc;
    
    newLoc.HP_Lead_Status__c='Inactive';
    newLoc.Country__c='US';
    newLoc.Location_Name__c='test12';
    newLoc.State__c='UP';
    newLoc.World_Region1__c=newWorld1.Id;
    newLoc.Postal_Code__c='12839831';
    Update newLoc;
               
    Location__c newLoc1=new Location__c(Name='33586574',Account__c=newAcc.Id,HP_Lead_Status__c='Inactive');
    Insert newLoc1; 
    try{   
    newLoc1.HP_Lead_Status__c='Non compliant';
    Update newLoc1;
    }catch(exception e){}
    
     //Test opportunity Insertion              
    Opportunity newOppty=new Opportunity(AccountId=newCustAcc.Id,Name='Test Opty111',CloseDate=Date.today(),StageName='01 - Understand Customer');
    Insert newOppty;
    
    Test.startTest();
    PCLM_FutureInsertACP.insertACP(newAcc.Id,newOppty.Id,newLoc.Id);
        PCLM_NoncompliantRemovalController x = new PCLM_NoncompliantRemovalController();

    Test.stopTest();
    
    }

}