objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Address country.</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDCP_Organization_ID__c</fullName>
        <formula>Account__r.MDCP_Organization_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MDCP Organization ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Account_ID__c</fullName>
        <description>External System ID. A Siebel PRM Partner ID.</description>
        <label>Source System Account ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>World_Region1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>World Region</label>
        <referenceTo>World_Region__c</referenceTo>
        <relationshipLabel>Locations (World Region)</relationshipLabel>
        <relationshipName>Locations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/World_Region__c.object
<CustomObject>
    <description>For testing World Region</description>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ParentId</label>
        <referenceTo>World_Region__c</referenceTo>
        <relationshipName>CountryRegionHierarchies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>IF( NOT( ISBLANK( Country_Name__c ) ), BLANKVALUE( ParentId__r.ParentId__r.ParentId__r.ParentName__c , BLANKVALUE( ParentId__r.ParentId__r.ParentName__c , BLANKVALUE(  ParentId__r.ParentName__c , BLANKVALUE(  ParentName__c , &apos;&apos; )))), Country_Name__c )</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>World Region</label>
    <nameField>
        <label>World Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>World Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CPQPartnerHPQuoteControllerTest.cls
@isTest(SeeAllData=true)
private class CPQPartnerHPQuoteControllerTest{
    ///Test Method 
        public static testMethod void CPQPartnerHPCTest() {
        Test.startTest();
        /*
        // Create WorldRegion
        World_Region__c objWR1 = new World_Region__c(Name = 'US',Country_Name__c='United States');
        Insert objWR1;
        objWR1 = [select Region__c from World_Region__c where ID =: objWR1.Id];
        
         World_Region__c objWR = new World_Region__c(Name = 'US',Country_Name__c='United States', ParentId__c=objWR1.id);
        Insert objWR;
        objWR = [select Region__c from World_Region__c where ID =: objWR.Id];
        system.debug('*******objWR*****'+objWR);
         system.debug('*******objWR.Region__c*****'+objWR.Region__c);*/
        
        //Create Location
        //Location__c ObjLOC = new Location__c(Name='Test', World_Region1__c=objWR.Id);
        Location__c ObjLOC = new Location__c(Name='Test', Source_System_Account_ID__c='Test',Country__c='India');
        Insert ObjLOC;
        
        // Create Account
        Account objAccount = TestingSetupDataUtil.createAccount('TestAccount', 'shaijan.thomas@hp.com','Customer');
        objAccount.MDCP_Organization_ID__c = '12345';
        objAccount.Mdcp_SiteId__c ='1234';
        objAccount.MDCP_Site_Instance_Id__c='1234';
        Insert objAccount;
        
        // Create Opportunity
        Opportunity objOpportunity = TestingSetupDataUtil.createOpportunity(objAccount.Id, 'test Oppty1',system.today()+30);
        objOpportunity.Deal_Id__c = '123456';
        insert objOpportunity;
        
        // Search for login user for Self enabled 
        user objUser = [select Id, Partner_Self_Service_Enabled__c from user where id =:Userinfo.getUserId()];
        objUser.Portal_Tab_Access__c = 'Deal Reg';
        objUser.Location_Record_Id__c = ObjLOC.Id;
        objUser.HPPID__c = '123';
        update objUser;
        
        //Query to get the Opportunity_ID__c, auto number Field
       Opportunity objOpportunity1 = [select Account.Mdcp_SiteId__c,Account.MDCP_Site_Instance_Id__c,CurrencyIsoCode,Account.MDCP_Organization_ID__c,Deal_Id__c,Opportunity_ID__c  from Opportunity where id=:objOpportunity.Id];
        objUser.Partner_Self_Service_Enabled__c=false;
        update objUser;
         
        ApexPages.StandardController PartnerQuote = new ApexPages.StandardController(objOpportunity1);
        CPQPartnerHPQuoteController PartnerQu = new CPQPartnerHPQuoteController(PartnerQuote);
        PartnerQu.Wait();
        PartnerQu.createQuote();
        PartnerQu.editQuote(); 
        
        objUser.Partner_Self_Service_Enabled__c=true;
        update objUser;
        ApexPages.StandardController PartnerQuote1 = new ApexPages.StandardController(objOpportunity1);
        CPQPartnerHPQuoteController PartnerQu1 = new CPQPartnerHPQuoteController(PartnerQuote1);
        PartnerQu1.createQuote();
        PartnerQu1.editQuote();
        
        Test.stopTest();
    }
}