objects/Location__c.object
<CustomObject>
    <description>The Location object supports the multiple addresses an Organization can have. The object combines information from an MDCP Site Business Relationship and its related Other Party Site Instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to an Account object&apos;s record of type Partner and Subtype Business Relationship. As per MDCP Data Model, this custom objects implements an intersection between a Site Business Relationship and its address and an Account record of type or Business Relationship.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EvaluateTerritory__c</fullName>
        <defaultValue>true</defaultValue>
        <label>EvaluateTerritory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sell_Into_Market__c</fullName>
        <description>World/Region or Country market this Locations is supporting for sales.</description>
        <label>Sell Into Market</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define a Territory as Active/ Inactive</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsConfidential__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate sales territory is confidential or not.</description>
        <label>IsConfidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean indicating whether Territory is exposed to Partner Accounts only</description>
        <label>IsPartner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MyComp_Sales_Territory_Name__c</fullName>
        <description>Created in R6</description>
        <label>Sales Territory Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Account_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Territory Account Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Account_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory Short Name</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Account Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Account_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Account Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Sales Territory Account Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Account Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Location_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Location_Name__c</fullName>
        <formula>Location__r.Location_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Locator Id</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Territory</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Location Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_Location_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory Location Assignment</label>
    <nameField>
        <label>STLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Location Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_User_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Add_to_Account_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add to Account Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Record with ISActive checked signifies User&apos;s present in Group.</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Territory Short Name</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory User Assignments</relationshipLabel>
        <relationshipName>Sales_Territory_User_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Territory_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Territory User Assignment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Sales Territory User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory User Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TMDisplayTerritoryUsersControllerTest.cls
@isTest(seeAllData=true)
private class TMDisplayTerritoryUsersControllerTest{
      // Test Coverage for Display Territory User for Location
    static testMethod void DisplayTerritoryUsersLocationTest() {
        
        test.startTest();
            TMDisplayTerritoryUsersController displayLocUser;
            
            Sales_Territory__c st = new Sales_Territory__c (Name='test ST', MyComp_Sales_Territory_Name__c='test ST',IsPartner__c=true, IsActive__c=true, IsConfidential__c=true);       
            insert st;
            Account account = TestingSetupDataUtil.createAccount('testAccount1', 'accountEmail@email.com','Partner');
            insert account ;
            Location__c loc  = new Location__c(Account__c=account.id, Name = 'testLocation', Location_Name__c = '12345',Sell_Into_Market__c='TestMarkt', EvaluateTerritory__c = false);
            insert loc;
            Sales_Territory_Location_Assignment__c stla = new Sales_Territory_Location_Assignment__c(Location__c = loc.Id, Sales_Territory__c = st.Id);
             insert stla;
            
            //Create Sales Terr User Assignment Records
            User currentUser = [select Id from user where Id =: UserInfo.getUserId()];
                 Sales_Territory_User_Assignment__c stua = new Sales_Territory_User_Assignment__c(User__c = currentUser.Id, Sales_Territory__c = st.Id, IsActive__c=true, Add_to_Account_Team__c = false);
             insert stua;                                                                                           
            
            ApexPages.StandardController stdController = new ApexPages.StandardController(loc);
            displayLocUser = new TMDisplayTerritoryUsersController(stdController);
            displayLocUser.getSortDirection();
            displayLocUser.setSortDirection('DESC');
            displayLocUser.getsalesTerritoryLocAssign();
            displayLocUser.ViewData();
            displayLocUser.sortExpression='User__r.Name';
            displayLocUser.sortExpression='DESC';
            displayLocUser.sortExpression='';
            displayLocUser.getSortDirection();
            displayLocUser.backPage();
            displayLocUser.next();
            displayLocUser.beginning();
            displayLocUser.End();
            displayLocUser.previous();
            displayLocUser.getDisablePrevious();
            displayLocUser.getDisableNext();
            displayLocUser.getTotalPages();
            displayLocUser.getTotal_size();
            displayLocUser.getPageNumber();
            displayLocUser.getListSize();
            displayLocUser.getDisableExportToXLS();
            displayLocUser.exportToExcel();
    
         test.stopTest();
        
    }
    // Test Coverage for Display Territory User for Account
    
     static testMethod void DisplayTerritoryUsersAccountTest() {
        
        test.startTest();
            TMDisplayTerritoryUsersControllerAccts displayAccUser;
            
            Sales_Territory__c st = new Sales_Territory__c (Name='test ST', MyComp_Sales_Territory_Name__c='test ST',IsPartner__c=true, IsActive__c=true, IsConfidential__c=true);       
            insert st;
            Account account = TestingSetupDataUtil.createAccount('testAccount1', 'accountEmail@email.com','Partner');
            insert account ;
           
            Sales_Territory_Account_Assignment__c staa = new Sales_Territory_Account_Assignment__c(Account__c = Account.Id, Sales_Territory__c = st.Id);
             insert staa;
            
            //Create Sales Terr User Assignment Records
            User currentUser = [select Id from user where Id =: UserInfo.getUserId()];
                 Sales_Territory_User_Assignment__c stua = new Sales_Territory_User_Assignment__c(User__c = currentUser.Id, Sales_Territory__c = st.Id, IsActive__c=true, Add_to_Account_Team__c = false);
             insert stua;                                                                                           
            
            ApexPages.StandardController stdController = new ApexPages.StandardController(account);
            displayAccUser = new TMDisplayTerritoryUsersControllerAccts(stdController);
            displayAccUser.getSortDirection();
            displayAccUser.setSortDirection('DESC');
            displayAccUser.getsalesTerritoryLocAssign();
            displayAccUser.ViewData();
            displayAccUser.sortExpression='User__r.Name';
            displayAccUser.sortExpression='DESC';
            displayAccUser.sortExpression='';
            displayAccUser.getSortDirection();
            displayAccUser.backPage();
            displayAccUser.next();
            displayAccUser.beginning();
            displayAccUser.End();
            displayAccUser.previous();
            displayAccUser.getDisablePrevious();
            displayAccUser.getDisableNext();
            displayAccUser.getTotalPages();
            displayAccUser.getTotal_size();
            displayAccUser.getPageNumber();
            displayAccUser.getListSize();
            displayAccUser.getDisableExportToXLS();
            displayAccUser.exportToExcel();
    
         test.stopTest();
        
    }
    
   
}