objects/Offering_Release_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Allowable_Variance__c</fullName>
        <label>Allowable Variance</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offering_Release_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offering Release ID</label>
        <referenceTo>Offering_Release__c</referenceTo>
        <relationshipLabel>Offering Release Stages</relationshipLabel>
        <relationshipName>Offering_Release_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAC__c</fullName>
        <label>PAC</label>
        <picklist>
            <picklistValues>
                <fullName>ABS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITO</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Stage ID</label>
        <referenceTo>Stage__c</referenceTo>
        <relationshipLabel>Offering Release Stages</relationshipLabel>
        <relationshipName>Offering_Release_Stages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Offering Release Stage</label>
    <nameField>
        <displayFormat>ORS-{0000}</displayFormat>
        <label>Offering Release Stage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offering Release Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestPLMTraggers.cls
@isTest(SeeAllData=true)
private class TestPLMTraggers{
    // Release Stage generator
    static Offering_Release_Stage__c createNewReleaseStage() {
        // Create test stage and insert it into the database
        Offering_Release_Stage__c stage = new Offering_Release_Stage__c();
        stage.Offering_Release_ID__c = id.valueOf('a6yZ0000000CxiU');
        stage.Stage_ID__c = id.valueOf('a6zZ00000008ekr');
        stage.Start_Date__c = date.newInstance(2013, 12, 15);
        stage.Allowable_Variance__c = date.newInstance(2013, 12, 15);
        stage.Status__c = 'Not Started';
        stage.PAC__c = 'ABS';
        return stage;
    }
    
	// Single row Release Stage => Create
    static testMethod void verifyReleaseStageCreate(){
        Offering_Release_Stage__c stage = createNewReleaseStage();
 
        // Delete the Invoice, capture the result
        Database.SaveResult result = Database.insert(stage, false);
 
        // Assert success, because target Invoice doesn't have Line Items
        System.assert(result.isSuccess());
    }
}