objects/Offering_Release__c.object
<CustomObject>
    <fields>
        <fullName>Flight_Plan_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flight Plan ID</label>
        <referenceTo>Flight_Plan__c</referenceTo>
        <relationshipName>Offering_Release</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Plan_Name__c</fullName>
        <formula>Flight_Plan_ID__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Opportunity Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>OPP-{0000000000}</displayFormat>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Release_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Offering_Release_ID__c</fullName>
        <label>Opportunity ID</label>
        <referenceTo>Offering_Release__c</referenceTo>
        <relationshipLabel>Stage</relationshipLabel>
        <relationshipName>Release_Stage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage_Name__c</fullName>
        <formula>Stage_ID__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Stage Name</label>
        <type>Text</type>
    </fields>
    <label>Stage</label>
    <nameField>
        <displayFormat>S-{0000000000}</displayFormat>
        <label>Stage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Work_Element__c.object
<CustomObject>
    <fields>
        <fullName>Deliverable_Name__c</fullName>
        <formula>Deliverable_ID__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Deliverable Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Review_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Review Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage_Name__c</fullName>
        <formula>Stage_ID__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Stage Name</label>
        <type>Text</type>
    </fields>
    <label>Process Work Element</label>
    <nameField>
        <displayFormat>PWE-{0000000000}</displayFormat>
        <label>Process Work Element ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Work Element</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ExtendedLoadStageWorkElementClass.cls
public class ExtendedLoadStageWorkElementClass {

    public string para_RelStgName{get; set;}
    public string para_RelStgID{get; set;}
    public string para_WkEleId{get; set;}
    
    public string curRelStg{get;set;}
    public List<Work_Element__c> WEC {get;set;}
    public Release_Stage__c RSC{get;set;}

    public string FlightPlanID{get; set;}

    public ExtendedLoadStageWorkElementClass (){
        para_RelStgName= ApexPages.currentPage().getParameters().get('RelStgName');
        para_RelStgID = ApexPages.currentPage().getParameters().get('RelStgID');
        
        RSC = [select Offering_Release_ID__r.Flight_Plan_ID__c, Offering_Release_ID__r.Flight_Plan_Name__c, Stage_Name__c from Release_Stage__c where id =:para_RelStgID];
        
        WEC = [select Name__c, Deliverable_Name__c, Is_Active__c , Review_Required__c, Stage_Name__c from Work_Element__c where Stage_Name__c =:RSC.Stage_Name__c];
    }
    public PageReference cancel() {
        return null;
    }
    public PageReference save() {
        return null;
    }

}