objects/Product_Specialty__c.object
<CustomObject>
    <description>Specialty Object- Main parent object for the Specialty Functionality.</description>
    <fields>
        <fullName>New_Specialty_search__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Specialty search</label>
        <type>Checkbox</type>
    </fields>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Specialty_User_Assignment__c.object
<CustomObject>
    <description>Specialty User Assignment - This is child object to Specialty which is for storing records for Users assigned the particular specialty.</description>
    <fields>
        <fullName>New_User_Insert_Sales_Territory__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field provides the information about the new user which is inserted in sales territory and the same user is present in Specialty user assignment then this checkbox gets checked.</description>
        <label>New User Insert Sales Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Specialty__c</fullName>
        <description>Specialty</description>
        <inlineHelpText>Specialty</inlineHelpText>
        <label>Specialty</label>
        <referenceTo>Product_Specialty__c</referenceTo>
        <relationshipLabel>Specialty User Assignments</relationshipLabel>
        <relationshipName>Product_Specialty_User_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Specialty User Assignment</label>
    <nameField>
        <displayFormat>PSU-{000000}</displayFormat>
        <label>Specialty User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specialty User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>DateTime_User_Insert__c</fullName>
        <description>This field carry the information about the user who gets inserted into sales territory user assignment, and this field gets updated with the time, when that user was inserted.</description>
        <label>DateTime User Insert</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>New_User_Alert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When a user is inserted into Sales territory user assignment,It checks weather this user is in Specialty or not,if user is in specialty, this checkbox gets checked in sales territory and those accounts are picked in the batch.</description>
        <label>New_User_Alert</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TMEngineScheduledFlag__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>TMEngineScheduled to be flagged TRUE until all batches complete, next schedule will only begin if flag is FALSE i.e all batches from first instance executed.</description>
    <fields>
        <fullName>SchedularFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SchedularFlag</label>
        <type>Checkbox</type>
    </fields>
    <label>TMEngineScheduledFlag__c</label>
</CustomObject>

classes/TMProcessLocSOMCrtBatch.cls
/**********************************************************
    * Class Name: TMProcessLocSOMCrtBatch
    * Author: Raghvendra Jha
    * Date: 04-Jan-2013  
    *  Requirement # Req Id:10320 
    * Description: This batch class is a handle the SOM logic.
    ***********************************************************/
    global class TMProcessLocSOMCrtBatch implements Database.batchable<sObject> ,  Database.Stateful{
       
        public String productLineItem='select id from OpportunityLineItem'+
                            ' where (OpportunityId IN :opptyIdSet) AND (Opportunity.IsClosed=False)';
        global string stDatetime;
        global set<ID> opptyIdSet= new set<ID>();
        
        public TMProcessLocSOMCrtBatch (set<Id> oppIdSet,String datetime2){
            opptyIdSet=oppIdSet; 
            stDatetime= datetime2;  
        } 
        
        
        global Database.queryLocator start(Database.BatchableContext ctx){ 
            if ( Test.isRunningTest() ) productLineItem+= ' limit 30';
            return Database.getQueryLocator(productLineItem); 
           
        }
        
        // this method prepares MAP for Opportunity id and product.
        global void execute(Database.BatchableContext ctx, List<OpportunityLineItem > opportunitylineItemList){
           
            set<Id> oliSet= new set<Id>();
            Map<Id,Set<Id>> oppLineItemProductSetMap = new Map<Id,Set<Id>>();       
            for(OpportunityLineItem olItem :opportunitylineItemList){
                oliSet.add(olItem.id);           
            }
            for(OpportunityLineItem oppLineItemObj : [Select o.Id, o.Product__c, o.OpportunityId From OpportunityLineItem o Where id in : oliSet ]){ 
                Set<id> productSet = oppLineItemProductSetMap.get(oppLineItemObj.OpportunityId);
                if(null == productSet){
                    productSet = new Set<Id>(); 
                } 
                productSet.add(oppLineItemObj.Product__c);
                oppLineItemProductSetMap.put(oppLineItemObj.OpportunityId,productSet);
            }
              
            SOMCreationController.executeSomLogic(oppLineItemProductSetMap);     
        }
        
        
        global void finish(Database.BatchableContext ctx){
         TMEngineScheduledFlag__c TMEngineScheduledFlagObj = TMEngineScheduledFlag__c.getValues(Label.TMProcessProdLineItemSOMBatch);
                boolean flag = TMEngineScheduledFlagObj.SchedularFlag__c;
                if(flag== True){
                    TMEngineScheduledFlagObj.SchedularFlag__c = False;
                    update TMEngineScheduledFlagObj;
                }  
                
                String queParam = 'Select Id,New_Specialty_search__c from Product_Specialty__c where New_Specialty_search__c = true' +  ' AND' +  ' LastModifiedDate <'+ stDatetime;
                String param = 'New_Specialty_search__c';            
                //TM:Sreenath scheduling a batch from a batch without cron expression starts
                EvaluateTerrRealignBatch ETRB = new EvaluateTerrRealignBatch(queParam,param);
                String cronID1 = System.scheduleBatch(ETRB, 'EvaluateTerrRealign_Batch_Job1', 3);
                //TM:Sreenath scheduling a batch from a batch without cron expression ends
                
                
                String queParam1 = 'Select Id,New_User_Alert__c from sales_Territory__c where New_User_Alert__c = true' +  ' AND' +  ' DateTime_User_Insert__c <'+ stDatetime;
                String param1 = 'New_User_Alert__c';               
                //TM:Sreenath scheduling a batch from a batch without cron expression starts
                EvaluateTerrRealignBatch ETRB1 = new EvaluateTerrRealignBatch(queParam1,param1);
                String cronID2 = System.scheduleBatch(ETRB1, 'EvaluateTerrRealign_Batch_Job2', 6);
                //TM:Sreenath scheduling a batch from a batch without cron expression ends
                
                String queParam2 = 'Select Id,New_User_Insert_Sales_Territory__c from Product_Specialty_User_Assignment__c where New_User_Insert_Sales_Territory__c = true' +  ' AND' +  ' LastModifiedDate <'+ stDatetime;
                String param2 = 'New_User_Insert_Sales_Territory__c';                        
                //TM:Sreenath scheduling a batch from a batch without cron expression starts
                EvaluateTerrRealignBatch ETRB2 = new EvaluateTerrRealignBatch(queParam2,param2);
                String cronID3 = System.scheduleBatch(ETRB2, 'EvaluateTerrRealign_Batch_Job3', 10);
                //TM:Sreenath scheduling a batch from a batch without cron expression ends
                
                if (ctx != null) {
                AsyncApexJob apexJob = [SELECT id, ApexClassId,   
                               JobItemsProcessed, TotalJobItems,   
                               NumberOfErrors, CreatedBy.Email   
                            FROM AsyncApexJob   
                            WHERE id = :ctx.getJobId()];  
                
                String emailMessage = 'Your APEX Batch Job for TMProcessLocationSOMBatch has been completed ';  
                Messaging.SingleEmailMessage mail =   
                new Messaging.SingleEmailMessage();  
                String[] toAddresses = new String[] {apexJob.CreatedBy.Email};
                mail.setToAddresses(toAddresses);  
                mail.setReplyTo('noreply@salesforce.com');  
                mail.setSenderDisplayName(Label.SenderDisplayName);  
                mail.setSubject(Label.Subject);  
                mail.setPlainTextBody(emailMessage);  
                mail.setHtmlBody(emailMessage);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[]  
                      { mail });
                }
                
        
        }
    }