objects/Release_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Include__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Include checkbox indicates the Release Stage
should be included (checked) or excluded (unchecked) for the
Offering Release.</description>
        <inlineHelpText>The Include indicates the Release Stage
should be included (checked) or excluded (unchecked) for the
Offering Release.</inlineHelpText>
        <label>Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offering_Release_ID__c</fullName>
        <label>Opportunity ID</label>
        <referenceTo>Offering_Release__c</referenceTo>
        <relationshipLabel>Stage</relationshipLabel>
        <relationshipName>Release_Stage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Stage</label>
    <nameField>
        <displayFormat>S-{0000000000}</displayFormat>
        <label>Stage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Stage_Work_Element__c.object
<CustomObject>
    <fields>
        <fullName>Include__c</fullName>
        <formula>IF(Release_Stage_ID__r.Include__c  = TRUE &amp;&amp;  Release_Deliverable_ID__r.Include__c = TRUE ,TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release_Stage_ID__c</fullName>
        <label>Stage ID</label>
        <referenceTo>Release_Stage__c</referenceTo>
        <relationshipName>Stage_Work_Elements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Element_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Process Work Element ID</label>
        <referenceTo>Work_Element__c</referenceTo>
        <relationshipLabel>Work Elements</relationshipLabel>
        <relationshipName>Stage_Work_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Element_Name__c</fullName>
        <formula>Work_Element_ID__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Work Element Name</label>
        <type>Text</type>
    </fields>
    <label>Work Element</label>
    <nameField>
        <displayFormat>WE-{0000000000}</displayFormat>
        <label>Work Element ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Stage_Work_Element_Predecessor__c.object
<CustomObject>
    <fields>
        <fullName>Include__c</fullName>
        <formula>IF (  Stage_Work_Element__r.Include__c = TRUE &amp;&amp;  Predecessor_Stage_Work_Element_ID__r.Include__c = TRUE,TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Predecessor_Stage_Work_Element_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Predecessor  Work Element ID</label>
        <referenceTo>Stage_Work_Element__c</referenceTo>
        <relationshipLabel>Work Element Predecessors (Predecessor Stage Work Element ID)</relationshipLabel>
        <relationshipName>Stage_Work_Element_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Predecessor_Stage_Work_Element_Name__c</fullName>
        <formula>Predecessor_Stage_Work_Element_ID__r.Name__c</formula>
        <label>Predecessor Work Element Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Work_Element_Name__c</fullName>
        <formula>Stage_Work_Element__r.Name__c</formula>
        <label>Work Element Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Work_Element__c</fullName>
        <label>Work Element Id</label>
        <referenceTo>Stage_Work_Element__c</referenceTo>
        <relationshipLabel>Work Element Predecessors (Stage Work Element Id)</relationshipLabel>
        <relationshipName>Stage_Work_Element_Predecessors1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Element__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Predecessor Process Work Element Id</label>
        <referenceTo>Work_Element__c</referenceTo>
        <relationshipLabel>Work Element Predecessors</relationshipLabel>
        <relationshipName>Stage_Work_Element_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Element Predecessor</label>
    <nameField>
        <displayFormat>WEP-{0000000000}</displayFormat>
        <label>Work Element Predecessor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Element Predecessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Work_Element__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Process Work Element</label>
    <nameField>
        <displayFormat>PWE-{0000000000}</displayFormat>
        <label>Process Work Element ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Work Element</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ODP_Extension_WorkElementPredecessor.cls
/*Change History
Modified By: Ning Kang - 04/28/2014
Change Content: Everywhere in the sysem, do not show user system error messages

*/
public with sharing class ODP_Extension_WorkElementPredecessor {
    public Stage_Work_Element_Predecessor__c stageWorkElementPredecessor{get;set;}
    public Stage_Work_Element__c workElements = new Stage_Work_Element__c();
    public String myEditWEP{get;set;}
    public string UserID{get;set;}

    public string retURL{get;set;}
    public String[] splitString {get;set;}
    public List<Stage_Work_Element__c> workElementsList{get;set;}
    public List<Stage_Work_Element_Predecessor__c> wepList{get;set;}
    
    //add by june 05/26/2014
     public List<Stage_Work_Element_Predecessor__c> sweps{get;set;}
     public ID currentSWEId{get;set;}
     public Set<ID> wes{Get;set;}
     //--end--
    
    public ODP_Extension_WorkElementPredecessor(ApexPages.StandardController controller) {
        stageWorkElementPredecessor = (Stage_Work_Element_Predecessor__c)controller.getRecord();
        
        UserID = UserInfo.getUserId();
        
        retURL =  ApexPages.currentPage().getParameters().get('retURL');
        if(string.isNotEmpty(retURL)){
            retURL =  ApexPages.currentPage().getParameters().get('retURL');    
        }
        if(retURL!='' )
        {
         splitString=retURL.split('/');
         
        }
        
        if(stageWorkElementPredecessor.Id == null && splitString[1]!= '')
        {
            myEditWEP = 'Create';
                    workElements = [select Id,Name__c,Work_Element_ID__c,Work_Element_Name__c,Release_Stage_ID__r.Offering_Release_ID__c,Include__c,Release_Stage_ID__c from Stage_Work_Element__c where id=:splitString[1]];
                    //System.debug('*********'+workElements);
                    //modified by june 05/28/2014
                    workElementsList = [select Work_Element_ID__c,Id,Name__c,Work_Element_Name__c,Release_Stage_ID__r.Offering_Release_ID__c from Stage_Work_Element__c where Release_Stage_ID__r.Offering_Release_ID__c =:workElements.Release_Stage_ID__r.Offering_Release_ID__c and include__c = true and Release_Stage_ID__c=:workElements.Release_Stage_ID__c];
                    //--end--
                //    System.debug('++++++++++'+workElementsList.size());
                    wepList = [Select Id,
                                      Name,
                                      Predecessor_Stage_Work_Element_ID__c,
                                      Work_Element__c,Stage_Work_Element__c,
                                      Include__c,
                                      Predecessor_Stage_Work_Element_Name__c,
                                      Stage_Work_Element_Name__c
                                      from Stage_Work_Element_Predecessor__c where Stage_Work_Element__r.Release_Stage_ID__r.Offering_Release_ID__c =:workElements.Release_Stage_ID__r.Offering_Release_ID__c]; 
             //add by june 05/26/2014     

             currentSWEId = stageWorkElementPredecessor.Stage_Work_Element__c;                 
             wes = CheckPWEHaveWE(stageWorkElementPredecessor);
             //--end--
        } 
        else
        {    //modified by june 05/28/2014
            stageWorkElementPredecessor = [Select Id,
                                                  Name,
                                                  Predecessor_Stage_Work_Element_ID__c,
                                                  Work_Element__c,Stage_Work_Element__c,
                                                  Include__c,
                                                  Predecessor_Stage_Work_Element_Name__c,
                                                  Stage_Work_Element_Name__c,
                                                  Stage_Work_Element__r.Release_Stage_ID__r.Offering_Release_ID__c,
                                                  Stage_Work_Element__r.Release_Stage_ID__c
                                                  from Stage_Work_Element_Predecessor__c where Id=:stageWorkElementPredecessor.Id];
             //--end--
            //System.Debug('Test'+stageWorkElementPredecessor);
            workElementsList = new List<Stage_Work_Element__c>();
            wepList = new List<Stage_Work_Element_Predecessor__c>();
            //modified by june 05/28/2014
            workElementsList = [select Id,Name__c,Work_Element_ID__c,Work_Element_Name__c,Release_Stage_ID__r.Offering_Release_ID__c from Stage_Work_Element__c where Release_Stage_ID__r.Offering_Release_ID__c =:stageWorkElementPredecessor.Stage_Work_Element__r.Release_Stage_ID__r.Offering_Release_ID__c AND Include__c = true and Release_Stage_ID__c=:stageWorkElementPredecessor.Stage_Work_Element__r.Release_Stage_ID__c];
            //--end--
            wepList = [Select Id,
                              Name,
                              Predecessor_Stage_Work_Element_ID__c,
                              Work_Element__c,Stage_Work_Element__c,
                              Include__c,
                              Predecessor_Stage_Work_Element_Name__c,
                              Stage_Work_Element_Name__c
                              from Stage_Work_Element_Predecessor__c where Stage_Work_Element__r.Release_Stage_ID__r.Offering_Release_ID__c =:stageWorkElementPredecessor.Stage_Work_Element__r.Release_Stage_ID__r.Offering_Release_ID__c];
            myEditWEP = 'Update';
            //add by june 05/26/2014
            currentSWEId = stageWorkElementPredecessor.Stage_Work_Element__c;
            wes = CheckPWEHaveWE(stageWorkElementPredecessor);
            //--end--

        }

    }
    
    //add by june 05/26/2014
    public Set<ID> CheckPWEHaveWE(Stage_Work_Element_Predecessor__c stageWorkElementPredecessor){
         sweps = [select Id,Name,Stage_Work_Element__c,Predecessor_Stage_Work_Element_ID__c,Predecessor_Stage_Work_Element_Name__c from Stage_Work_Element_Predecessor__c where Stage_Work_Element__c =:stageWorkElementPredecessor.Stage_Work_Element__c];
           Set<ID> ids = new Set<ID>();
            for(Stage_Work_Element_Predecessor__c swep: sweps){
                if(swep.Stage_Work_Element__c == stageWorkElementPredecessor.Stage_Work_Element__c)
                    ids.add(swep.Predecessor_Stage_Work_Element_ID__c);
            }  
            return ids;
    }
    //--end--
    
    
    
    
    public PageReference Save(){
        try{
            system.debug('pavi'+stageWorkElementPredecessor);
            upsert stageWorkElementPredecessor;
            PageReference WEPage = new PageReference('/'+stageWorkElementPredecessor.Id);
            WEPage.setRedirect(true);
            return WEPage;
        }
        catch(exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Work Element Predecessor Saving Exception, Please contact IT Administrator'));
            return null;   
        }
    }
    
    public List<SelectOption> displayWorkElementsOfCurretProject{
        get{
            List<SelectOption> options = new List<SelectOption>();
            //modify by june 05/26/2014
            if(myEditWEP=='Create')
                options.add(new SelectOption('----Select----','----Select----'));
            else
                options.add(new SelectOption(stageWorkElementPredecessor.Predecessor_Stage_Work_Element_ID__c,stageWorkElementPredecessor.Predecessor_Stage_Work_Element_Name__c));
            for(Stage_Work_Element__c workEle:workElementsList) {
                  //add by june 06/04/2014
               //   if(myEditWEP=='Create')
               //   {
               //       options.add(new SelectOption(workEle.Id,workEle.Name__c));
               //       continue;
               //   } 
                  //--end--
                  if(wes.contains(workEle.Id)||workEle.Id==currentSWEId)
                  {
                      continue;
                  }
                  options.add(new SelectOption(workEle.Id,workEle.Name__c));
            }
            //--end--
             return options;
        }
        
        
    }

}