objects/Reviewer_Workspace__c.object
<CustomObject>
    <label>Workspace</label>
    <nameField>
        <displayFormat>W-{00000}</displayFormat>
        <label>Reviewer Workspace Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workspaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WS_Approver__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejeted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer_Workspace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workspace</label>
        <referenceTo>Reviewer_Workspace__c</referenceTo>
        <relationshipLabel>Approvers</relationshipLabel>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approver</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DGApproverNewController.cls
public with sharing class DGApproverNewController {


public ApexPages.StandardController std; 
    public String id;
    public List<ApproverWrapperClass> ApproverWrapper;
    public boolean isaddrow;   
    public user activeUser {get;set;}
    public Opportunity oppty {get; set;}
    public Boolean isInsert;
    Public string str;
 public DGApproverNewController(ApexPages.StandardController controller) {
        Str =ApexPages.currentPage().getParameters().get('retURL').substringAfter('/');
        ApproverWrapper=new List<ApproverWrapperClass>();
          
        isaddrow=True;
        isInsert=false;
       
    }

/*getter seter for add row*/
    public List<ApproverWrapperClass> getApproverWrapper(){
        If(isaddrow == true){
         for(Integer i=0;i<6;i++){
            //ompetitorList.add(new CompetitorClass(competitorRecord.Opportunity__c));
        
            system.debug('******addrow2*******'+isaddrow);
            WS_Approver__c prAddRow=new WS_Approver__c();
            system.debug('******addrow3*******'+isaddrow);
            ApproverWrapperClass persuitresWrapper = new ApproverWrapperClass(prAddRow);
            system.debug('******addrow4*******'+isaddrow);
            persuitresWrapper.index = ApproverWrapper.size()+1;
            system.debug('******index *******'+ApproverWrapper.size());
            ApproverWrapper.add(persuitresWrapper);
            system.debug('******ApproverWrapper*******'+ApproverWrapper);
            }
            isaddrow = false;
            
        }
        return ApproverWrapper;
    }
  
    /* Custom save for adding the Pursuit Resource to the save*/ 
    public PageReference customSave(){ 
        Savepoint sp = Database.setSavepoint();
       
        try{
           
    
        
        List<WS_Approver__c> opprrToInsertList=new List<WS_Approver__c >();
        for (ApproverWrapperClass ppwc: ApproverWrapper) {
          if(ppwc.oApproverObj.Approver__c !=null  ){
          system.debug('ppwc.oApproverObj.Approver__c------'+ppwc.oApproverObj.Approver__c);
         
            ppwc.oApproverObj.Approval_status__c ='Pending';
            ppwc.oApproverObj.Reviewer_Workspace__c = str; 
            opprrToInsertList.add(ppwc.oApproverObj);
            }
        }
        system.debug('List*********  '+opprrToInsertList.size());
        insert opprrToInsertList;
        PageReference pr = new PageReference('/'+str);
        pr.setRedirect(true); 
        return pr;
        }
        catch(Exception e){
          //Database.rollback( sp );
          isInsert=true;
          string msg=e.getMessage();
          system.debug('msg***************'+msg);
          ApexPages.addmessages(e);
        return null;
        }
       
    }  

/*Wrapper class for adding and deleting row on fly without committing to the database.*/
    public class ApproverWrapperClass
    {

        public integer index {get;set;}
        public WS_Approver__c oApproverObj{get;set;}
        public ApproverWrapperClass(WS_Approver__c oApproverObj){
            system.debug('Index****wrapper class:'+this.index);
            this.oApproverObj=oApproverObj;
        }
    }



}