objects/Role__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <label>Process Role Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Process Role</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Process Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProcessRolePlan.cls
global class ProcessRolePlan {
  
   webservice String area; 
   webservice String region; 
   
   //Define an object in apex that is exposed in apex web service
   global class ProcessRole{
      webservice String name;
      webservice String Description;
      webservice Id roleId;
   }

   webservice static ProcessRole createProcessRolePlan(ProcessRole vProcessRole) {
       
       //A plan maps to the Account object in salesforce.com. 
       //So need to map the Plan class object to Account standard object
       Role__c role = new Role__c();
       role.Role_Name__c = vProcessRole.name;
       role.Description__c= vProcessRole.Description;
       insert role;
       
       vProcessRole.roleId=role.Id;
       return vProcessRole;
  }
  

}