objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Access__c</fullName>
        <label>Case Access</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsConfidential__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate sales territory is confidential or not.</description>
        <label>IsConfidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean indicating whether Territory is exposed to Partner Accounts only</description>
        <label>IsPartner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MyComp_Sales_Territory_Name__c</fullName>
        <description>Created in R6</description>
        <label>Sales Territory Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Territory_Definition__c.object
<CustomObject>
    <fields>
        <fullName>AMID__c</fullName>
        <label>AMID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountPreviewQuery__c</fullName>
        <formula>IF(Sales_Territory__r.IsConfidential__c, &quot; (Confidential_Account__c=TRUE&quot;, &quot; (Confidential_Account__c=FALSE&quot;)&amp;
IF(Sales_Territory__r.IsPartner__c , &quot; AND Recordtype.Name=&apos;Partner&apos;&quot;, &quot; AND Recordtype.Name=&apos;Customer&apos;&quot;)&amp;
IF( Exclude__c,
IF(NOT(ISBLANK(AMID__c)),&quot; AND AMID_L2__c != &apos;&quot;&amp;AMID__c&amp;&quot;&apos;) AND&quot;,
IF(NOT(ISBLANK(MDCP_ID__c)),&quot;AND MDCP_Organization_ID__c != &apos;&quot;&amp;MDCP_ID__c&amp;&quot;&apos;) AND&quot;,
IF(NOT(ISBLANK( Industry_Vertical__c )),&quot; AND Industry_Vertical__c != &apos;&quot;&amp; Industry_Vertical__c&amp;&quot;&apos;) AND&quot;,
IF(NOT(ISBLANK(BG_Sales_Coverage_Segment__c)),&quot; AND (NOT Coverage_Segmentation__c LIKE &apos;%&quot;&amp; BG_Sales_Coverage_Segment__c&amp;&quot;%&apos;)) AND&quot;,&quot;&quot;)))),
IF(ISBLANK(AMID__c), &quot;&quot;, &quot; AND AMID_L2__c=&apos;&quot;&amp;AMID__c&amp;&quot;&apos;&quot;)&amp;
IF(ISBLANK( MDCP_ID__c ), &quot;&quot;, &quot; AND MDCP_Organization_ID__c=&apos;&quot;&amp;MDCP_ID__c&amp;&quot;&apos;&quot;)&amp;
IF(ISBLANK( Business_Relationship__c ), &quot;&quot;, &quot; AND MDCP_Business_Relationship__c=&apos;&quot;&amp;Business_Relationship__c&amp;&quot;&apos;&quot;)&amp;
IF(ISBLANK( Source_System_ID__c ), &quot;&quot;, &quot; AND Source_System_Account_ID__c=&apos;&quot;&amp; Source_System_ID__c&amp;&quot;&apos;&quot; )&amp;
IF(ISBLANK( Industry_Vertical__c ), &quot;&quot;, &quot; AND Industry_Vertical__c=&apos;&quot;&amp; Industry_Vertical__c&amp;&quot;&apos;&quot; )&amp;
IF(ISBLANK( Named_Account__c ), &quot;&quot;, &quot; AND Named_Account__c LIKE &apos;%&quot;&amp; Named_Account__c&amp;&quot;%&apos;&quot; )&amp;
IF(ISBLANK( RAD__c ), &quot;&quot;, &quot; AND RAD__c LIKE &apos;%&quot;&amp; RAD__c &amp;&quot;%&apos;&quot; )&amp;
IF(ISBLANK( BG_Sales_Coverage_Segment__c ), &quot;&quot;, &quot; AND Coverage_Segmentation__c LIKE &apos;%&quot;&amp; BG_Sales_Coverage_Segment__c&amp;&quot;%&apos;&quot; )&amp;
IF(ISBLANK( BA_Market_Segment__c ), &quot;&quot;, &quot; AND BG_Target_Segments__c LIKE &apos;%&quot;&amp; BA_Market_Segment__c&amp;&quot;%&apos;&quot; )&amp;
IF(ISBLANK( Geographic_Hierarchy__c ), &quot;&quot;, &quot; AND WorldRegion_Hierarchy__c LIKE &apos;%&quot;&amp; Geographic_Hierarchy__c &amp;&quot;%&apos;&quot; )&amp;
IF(ISBLANK (Country__c ), &quot;&quot;, &quot; AND ShippingCountry=&apos;&quot;&amp; Country__c &amp;&quot;&apos;&quot;)&amp;
IF(ISBLANK ( State_Province__c ), &quot;&quot;, &quot; AND ShippingState=&apos;&quot;&amp; State_Province__c &amp;&quot;&apos;&quot;)&amp;
IF(ISBLANK ( Postal_Code_Start__c ), &quot;&quot;, &quot; AND ShippingPostalCode&gt;=&apos;&quot;&amp; Postal_Code_Start__c &amp;&quot;&apos;&quot;)&amp;
IF(ISBLANK ( Postal_Code_End__c ), &quot;) OR&quot;, &quot; AND ShippingPostalCode&lt;=&apos;&quot;&amp; Postal_Code_End__c &amp;&quot;&apos;) OR&quot;))</formula>
        <label>AccountPreviewQuery</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to exclude the Account which match this definition for a particular field</description>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Industry_Vertical__c</fullName>
        <label>Industry Vertical</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDCP_ID__c</fullName>
        <label>MDCP Organization ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_End__c</fullName>
        <label>Postal Code (End)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Start__c</fullName>
        <label>Postal Code (Start)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Territory Short Name</label>
        <referenceTo>Sales_Territory__c</referenceTo>
        <relationshipLabel>Sales Territory Definitions</relationshipLabel>
        <relationshipName>Sales_Territory_Definitions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Source System ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Territory Definition</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Sales Territory Definition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Territory Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SalesTerritoryExtensionControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=false)
private class SalesTerritoryExtensionControllerTest {

    static SalesTerritoryPreview salesTerritoryObj,salesTerritoryObj1;
    static Sales_Territory__c salesTerr,salesTerr1;
    static PageReference pageRef;
    
     static testMethod void testSalesTerrReport() {
        
        //TM:Debmalya:R3: Adding Account data
        String RecordTypeId = RecordTypeIdHelper.getRecordTypeId('Account','Customer');
        Account acc= new Account(Name='Acctest',AMID_L2__c='AMID1',RecordTypeId = RecordTypeId,ShippingCountry = 'India',ShippingState = 'MAH',
                                MDCP_Organization_ID__c = '1234STR', Source_System_Account_ID__c = '54321STR');
        insert acc;
        Account acc1= new Account(Name='Acctest1',RecordTypeId = RecordTypeId,ShippingCountry = 'India',ShippingPostalCode = '1234', 
                                MDCP_Organization_ID__c = 'MPDP123', Source_System_Account_ID__c = '54321STR1');
        insert acc1;
        salesTerr = new Sales_Territory__c (Name='Test',MyComp_Sales_Territory_Name__c='Test',Account_Access__c='Edit',Case_Access__c='Edit',Opportunity_Access__c='Edit',IsConfidential__c=False,IsPartner__c=false);
        salesTerr1 = new Sales_Territory__c (Name='Test1',MyComp_Sales_Territory_Name__c='Test1',Account_Access__c='Edit',Case_Access__c='None',Opportunity_Access__c='None');
        insert salesTerr;
        insert salesTerr1;
        Sales_Territory_Definition__c salesTerrDefn=new Sales_Territory_Definition__c(Sales_Territory__c=salesTerr.Id,AMID__c='AMID01',State_Province__c='MAH',Country__c='India');
       // Sales_Territory_Definition__c salesTerrDefn1=new Sales_Territory_Definition__c(Sales_Territory__c=salesTerr1.Id, Source_System_ID__c='ADE34XX',Industry_Vertical__c='Test');
        Sales_Territory_Definition__c salesTerrDefn2=new Sales_Territory_Definition__c(Sales_Territory__c=salesTerr.Id,MDCP_ID__c='MPDP0123',Postal_Code_Start__c='1234',Postal_Code_End__c='12345',Country__c='India');
        insert salesTerrDefn;
        Sales_Territory_Definition__c salesTerrDefn3=new Sales_Territory_Definition__c(Sales_Territory__c=salesTerr.Id,MDCP_ID__c='MPDP00123',Exclude__c = true);
        insert salesTerrDefn3;
        system.debug('*******salesTerrDefn***preview**'+salesTerrDefn+'*****'+salesTerrDefn.AccountPreviewQuery__c);
        system.debug('*******AccountPreviewQuery*****'+salesTerrDefn.AccountPreviewQuery__c);
        //insert salesTerrDefn1;
        insert salesTerrDefn2;
        system.debug('*******AccountPreviewQuery*****'+salesTerrDefn2.AccountPreviewQuery__c);
       
        /* Testing Constructor */
       ApexPages.StandardController stdController = new ApexPages.StandardController(salesTerr);
       salesTerritoryObj = new SalesTerritoryPreview (stdController);
      //ApexPages.StandardController stdController1 = new ApexPages.StandardSetController(salesTerritoryObj.getQuery());
      salesTerritoryObj.next();
      salesTerritoryObj.Beginning();
      salesTerritoryObj.End();
      salesTerritoryObj.previous();
      salesTerritoryObj.getDisablePrevious();
      salesTerritoryObj.getDisableNext();
      salesTerritoryObj.getTotalPages();
      salesTerritoryObj.getPageNumber();
      salesTerritoryObj.getTotal_size();
        
    }
}