objects/Service_Line__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <inlineHelpText>Identify the service line name</inlineHelpText>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Description</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <label>Service Line</label>
    <nameField>
        <displayFormat>SL-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PLMAdminController.cls
public class PLMAdminController {

    public String CurSLName{get;set;}
    public String CurDescripion{get;set;}
    public Boolean CurActive{get;set;}
    public PageReference save() {
        try{
            SLC = new Service_Line__c(Name__c =CurSLName, Short_Description__c =CurDescripion, Is_Active__c=CurActive );
            insert SLC;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'OK'));        
        
        }
        catch(exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please Check your input before saving. Name must be provided and unique'));        
        
        }
        return null;
    }


    public Service_Line__c SLC{get;set;}
}