objects/SLP_IDOL_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Database__c</fullName>
        <defaultValue>&quot;GSS_SIC&quot;</defaultValue>
        <description>Crawl database used for queries</description>
        <label>Database</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Maximum_Hits__c</fullName>
        <defaultValue>5000</defaultValue>
        <description>The absolute maximum number of hits returned, regardless of Page Size.</description>
        <label>Maximum Hits</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page_Size__c</fullName>
        <defaultValue>10</defaultValue>
        <description>Number of hits to return at one time. If there are more hits than the current page size, the results will be on the next page.</description>
        <label>Page Size</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Server_URL__c</fullName>
        <defaultValue>&quot;https://it-services-gw-csc-itg.external.hp.com/gw/esit/sfdc/idol&quot;</defaultValue>
        <description>Base Server External URL</description>
        <label>Server URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>SLP IDOL Settings</label>
</CustomObject>

classes/SLP_IdolQuery_TempItgTest.cls
public class SLP_IdolQuery_TempItgTest
{
    // INTERNAL SERVER: http://c0004793.itcs.hp.com:9000
    // EXTERNAL GATEWAY: https://it-services-gw-csc-itg.external.hp.com/gw/esit/sfdc/idol
    private static final SLP_IDOL_Settings__c appSettings; // SalesForce Custom Settings object (application global)
    private static final string DATABASE;
    private static final string SERVER;
    private static final integer PAGE_SIZE;
    private static final integer MAX_HITS;    

    static // cool... Apex supports static CTORs
    {
        // Note that by default SalesForce won't let you access pre-defined data (such as Custom Settings) 
        // so this is one reason this class cannot markled as a unit test.
        appSettings = SLP_IDOL_Settings__c.getOrgDefaults();
        
        PAGE_SIZE = appSettings.Page_Size__c.intValue();
        MAX_HITS = appSettings.Maximum_Hits__c.intValue();
        DATABASE = appSettings.Database__c;
        SERVER = appSettings.Server_URL__c;
        system.debug('PAGE_SIZE: ' + PAGE_SIZE);
        system.debug('MAX_HITS: ' + MAX_HITS);
        system.debug('DATABASE: ' + DATABASE);
        system.debug('SERVER: ' + SERVER);
    }
   
    public static void go()
    {         
        // Run Test
        string test = 'Barcelona and \"Big Data\"';        
        //string test = 'I me we'; //stop words only
        SLP_IdolQuery idol = new SLP_IdolQuery(SERVER, DATABASE, test, PAGE_SIZE, MAX_HITS);
        if(idol.ErrorText != '')
        {
             System.debug('ErrorText: ' + idol.ErrorText);
        }
        
        // Page through the results
        final integer MAX_CALLOUTS_ALLOWED = 10;
        integer checkLimit = 1;
        for(integer i = 1; i < idol.Hits && checkLimit < MAX_CALLOUTS_ALLOWED; i += PAGE_SIZE) 
        {
            checkLimit++;
            System.debug(string.format('page frame: item #{0}, page size: {1}; total hits: {2}',
                 new string[] {string.valueof(i), string.valueof(PAGE_SIZE), string.valueof(idol.Hits)}));
            
            List<SLP_IdolQueryResponse> results = idol.Fetch(i);
            for(SLP_IdolQueryResponse r: results)
            {
                // Until we build a UI to consume, dump results for informal test
                System.debug('url: ' + r.Url + '; weight: ' + r.Weight + '; title: ' + r.Title + '; summary: ' + r.Summary);
            }            
        }
        
        if(checkLimit == MAX_CALLOUTS_ALLOWED)
        {
            System.debug('We hit the callout limit per transaction so we stopped early');
        }
        
        // Validate Results... NOTE: if content changes we may need to adjust
        // ...that's another reason why this isn't a true unit test.
        integer minimalHits = 20;
        string msg = string.format('Expected at least {0} hits but got {1} instead.', 
                                   new string[] {string.valueof(minimalHits), string.valueof(idol.Hits)});
        System.assert(idol.hits > minimalHits, msg);
    }   
}