objects/Stage_Work_Element_Predecessor__c.object
<CustomObject>
    <fields>
        <fullName>Predecessor_Stage_Work_Element_Name__c</fullName>
        <formula>Predecessor_Stage_Work_Element_ID__r.Name__c</formula>
        <label>Predecessor Work Element Name</label>
        <type>Text</type>
    </fields>
    <label>Work Element Predecessor</label>
    <nameField>
        <displayFormat>WEP-{0000000000}</displayFormat>
        <label>Work Element Predecessor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Element Predecessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ODP_Extension_Work_Element_Predecessor.cls
public class ODP_Extension_Work_Element_Predecessor {
   public Stage_Work_Element_Predecessor__c workElementName {get;set;}

    public ODP_Extension_Work_Element_Predecessor(ApexPages.StandardController controller) {
    }
    public pageReference readWorkElementName() {
        workElementName = [select Id,Predecessor_Stage_Work_Element_Name__c from Stage_Work_Element_Predecessor__c];
        return null;
    }
    
    
   
}