objects/Stage_Work_Element__c.object
<CustomObject>
    <fields>
        <fullName>Include__c</fullName>
        <formula>IF(Release_Stage_ID__r.Include__c  = TRUE &amp;&amp;  Release_Deliverable_ID__r.Include__c = TRUE ,TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release_Deliverable_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Deliverable ID</label>
        <referenceTo>Release_Deliverable__c</referenceTo>
        <relationshipLabel>Work Elements</relationshipLabel>
        <relationshipName>Stage_Work_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Name__c</fullName>
        <formula>Release_Stage_ID__r.Stage_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Work Element</label>
    <nameField>
        <displayFormat>WE-{0000000000}</displayFormat>
        <label>Work Element ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ODP_DeliverableDetailsController.cls
public with sharing class ODP_DeliverableDetailsController {
    public List<Stage_work_Element__c> workElementList {get;set;}
    public string SelectedWorkElementId { get; set; }
    Public String getURL{get;set;}
    public ODP_DeliverableDetailsController(ApexPages.StandardController controller) {
        getURL = ApexPages.currentPage().getParameters().get('Id'); 
        loadStageWorkElementsData();

    }
    
    private void loadStageWorkElementsData() {
    System.debug('Get URL :'+getURL);
        workElementList = [Select Id,Name,Stage_Name__c,Name__c,Status__c,Include__c,Release_Deliverable_ID__c from Stage_Work_Element__c where Release_Deliverable_ID__c= :getURL];
        
        System.debug('Work Element List :'+workElementList);
    }
     public void deleteWorkElement(){
         if (SelectedWorkElementId == null) {
      
         return;
      }
     
      // find the work element record within the collection
      Stage_Work_Element__c tobeDeleted = null;
      for(Stage_Work_Element__c a : workElementList)
       if (a.Id == SelectedWorkELementId) {
          tobeDeleted = a;
          break;
       }
      
      //if work element record found delete it
      if (tobeDeleted != null) {
       Delete tobeDeleted;
      }
     }    
    
    
}