objects/TibcoSecurity__c.object
<CustomObject>
    <fields>
        <fullName>TargetSystemName__c</fullName>
        <label>TargetSystemName</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TibcoPassword__c</fullName>
        <label>TibcoPassword</label>
        <length>80</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>TibcoSecurity</label>
    <nameField>
        <label>Tibco UserName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TibcoSecurities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SalesManagerRepPosTest.cls
@isTest
public class SalesManagerRepPosTest {
    static testMethod void testGetReports() 
    {
        
        Opportunity opp= new Opportunity();
        List<TibcoSecurity__c> lstTibcoSec = new List<TibcoSecurity__c>();
        TibcoSecurity__c tibcoSec = new TibcoSecurity__c(Name='tibadmin', TargetSystemName__c='SALESOPPTYREPORTS', TibcoPassword__c='tibadmin');
        lstTibcoSec.add(tibcoSec);
        insert lstTibcoSec;
        PageReference pageRef = new PageReference('/apex/SalesManagerReport');
        Test.setCurrentPageReference(pageRef);
        SalesManagerRepPos ctrller = new SalesManagerRepPos(new ApexPages.StandardController(opp));
    }
    
    static testMethod void testExportOperation() {
     Opportunity opp= new Opportunity();
         PageReference pageRef = new PageReference('/apex/SalesManagerReport');
    Test.setCurrentPageReference(pageRef);
    SalesManagerRepPos ctrller = new SalesManagerRepPos(new ApexPages.StandardController(opp));
    //ctrller.exportReportToExcel(); 
    PageReference pageRef1 = Page.SalesManagerReportssheet;
     Test.setCurrentPageReference(pageRef1);
}
}